"""Additive access-request schema. Does not grant portal permissions."""

import sqlite3

from database.store import now, schema_key_of, unwrap_store

MARKER = "acesso_solicitacoes_schema_v1"
STATUS_PENDING = "pendente"
STATUS_APPROVED = "aprovado"
STATUS_REJECTED = "recusado"
STATUSES = (STATUS_PENDING, STATUS_APPROVED, STATUS_REJECTED)
_READY = set()
COLUMNS = (
    "id,nome,email,gabinete,unidade_outro,status,created_at,processed_at,processed_by"
)
INDEX_SQL = (
    "CREATE INDEX IF NOT EXISTS access_requests_email_idx ON access_requests(email)",
    "CREATE UNIQUE INDEX IF NOT EXISTS access_requests_email_pendente_idx "
    "ON access_requests(email) WHERE status='pendente'",
)


class AccessRequestStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        if schema_key_of(self.store) not in _READY:
            self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        with self.store.connection(read_only=True) as c:
            marker = c.execute(
                "SELECT valor FROM configuracoes WHERE chave=?", (MARKER,)
            ).fetchone()
            exists = self._table_exists(c)
        if marker and exists:
            with self.store.connection() as c:
                c.execute("BEGIN IMMEDIATE")
                for statement in INDEX_SQL:
                    c.execute(statement)
            _READY.add(key)
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS access_requests ("
                f"id {identity},"
                "nome TEXT NOT NULL,"
                "email TEXT NOT NULL,"
                "gabinete TEXT NOT NULL,"
                "unidade_outro TEXT,"
                "status TEXT NOT NULL DEFAULT 'pendente' "
                "CHECK(status IN ('pendente','aprovado','recusado')),"
                "created_at TEXT NOT NULL,"
                "processed_at TEXT,"
                "processed_by TEXT)"
            )
            for statement in INDEX_SQL:
                c.execute(statement)
            c.execute(
                "INSERT INTO configuracoes VALUES(?,?) ON CONFLICT DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def _table_exists(self, c):
        if self.store.backend == "postgresql":
            row = c.execute(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema=current_schema() AND table_name='access_requests'"
            ).fetchone()
            return bool(row)
        row = c.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='access_requests'"
        ).fetchone()
        return bool(row)

    def get_pending_by_email(self, email):
        email = (email or "").strip().lower()
        if not email:
            return None
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {COLUMNS} FROM access_requests "
                "WHERE email=? AND status=? ORDER BY id DESC",
                (email, STATUS_PENDING),
            ).fetchone()
            return dict(row) if row else None

    def create(self, nome, email, gabinete, unidade_outro=None):
        stamp = now()
        extra = (unidade_outro or "").strip() or None
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            pending = c.execute(
                "SELECT id FROM access_requests WHERE email=? AND status=?",
                (email, STATUS_PENDING),
            ).fetchone()
            if pending:
                raise ValueError(
                    "Já existe uma solicitação de acesso pendente para este e-mail."
                )
            try:
                inserted = c.execute(
                    "INSERT INTO access_requests("
                    "nome,email,gabinete,unidade_outro,status,created_at) "
                    "VALUES(?,?,?,?,?,?)",
                    (nome, email, gabinete, extra, STATUS_PENDING, stamp),
                )
            except sqlite3.IntegrityError:
                raise ValueError(
                    "Já existe uma solicitação de acesso pendente para este e-mail."
                ) from None
            except Exception as exc:
                if "23505" in str(exc):
                    raise ValueError(
                        "Já existe uma solicitação de acesso pendente para este e-mail."
                    ) from None
                raise
            identifier = inserted.lastrowid
        return {
            "id": identifier,
            "nome": nome,
            "email": email,
            "gabinete": gabinete,
            "unidade_outro": extra,
            "status": STATUS_PENDING,
            "created_at": stamp,
            "processed_at": None,
            "processed_by": None,
        }

    def get(self, identifier):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {COLUMNS} FROM access_requests WHERE id=?",
                (identifier,),
            ).fetchone()
            return dict(row) if row else None


def ensure_schema(store):
    AccessRequestStore(store)
