"""Additive authorized-users schema on the existing Store connection."""

import re
from database.store import now
from services.oficios import GABINETES

PROFILES = ("ADMINISTRADOR", "USUARIO")
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
MARKER = "acesso_schema_v1"
GABINETE_LIST = ",".join("'" + code + "'" for code in GABINETES)
USER_COLUMNS = (
    "id,nome,email,perfil,ativo,pode_portarias,pode_agenda,pode_oficios,pode_admin,"
    "criado_em,atualizado_em"
)


def normalize_email(value):
    return (value or "").strip().lower()


def flag(value):
    return 1 if value else 0


class AccessStore:
    def __init__(self, store):
        self.store = store
        self.ensure_schema()

    def ensure_schema(self):
        with self.store.connection(read_only=True) as c:
            if c.execute(
                "SELECT valor FROM configuracoes WHERE chave=?", (MARKER,)
            ).fetchone():
                return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS usuarios_acesso ("
                f"id {identity},"
                "nome TEXT NOT NULL,"
                "email TEXT NOT NULL UNIQUE,"
                "perfil TEXT NOT NULL CHECK(perfil IN ('ADMINISTRADOR','USUARIO')),"
                "ativo INTEGER NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)),"
                "pode_portarias INTEGER NOT NULL DEFAULT 0 CHECK(pode_portarias IN (0,1)),"
                "pode_agenda INTEGER NOT NULL DEFAULT 0 CHECK(pode_agenda IN (0,1)),"
                "pode_oficios INTEGER NOT NULL DEFAULT 0 CHECK(pode_oficios IN (0,1)),"
                "pode_admin INTEGER NOT NULL DEFAULT 0 CHECK(pode_admin IN (0,1)),"
                "criado_em TEXT NOT NULL,"
                "atualizado_em TEXT NOT NULL)"
            )
            fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
            c.execute(
                "CREATE TABLE IF NOT EXISTS usuario_gabinetes ("
                f"usuario_id {fk} NOT NULL REFERENCES usuarios_acesso(id) ON DELETE CASCADE,"
                f"gabinete TEXT NOT NULL CHECK(gabinete IN ({GABINETE_LIST})),"
                "PRIMARY KEY(usuario_id, gabinete))"
            )
            c.execute(
                "INSERT INTO configuracoes VALUES(?,?) ON CONFLICT DO NOTHING",
                (MARKER, "1"),
            )

    def get_by_email(self, email):
        email = normalize_email(email)
        if not email:
            return None
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {USER_COLUMNS} FROM usuarios_acesso WHERE email=?",
                (email,),
            ).fetchone()
            return self._hydrate(c, row) if row else None

    def get(self, identifier):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {USER_COLUMNS} FROM usuarios_acesso WHERE id=?",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Usuário não encontrado.")
            return self._hydrate(c, row)

    def list_users(self):
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT {USER_COLUMNS} FROM usuarios_acesso ORDER BY nome,email"
            ).fetchall()
            return [self._hydrate(c, row) for row in rows]

    def save_user(self, payload, identifier=None):
        nome = (payload.get("nome") or "").strip()
        email = normalize_email(payload.get("email"))
        perfil = (payload.get("perfil") or "USUARIO").strip().upper()
        if perfil not in PROFILES:
            raise ValueError("Perfil inválido.")
        if not nome:
            raise ValueError("Informe o nome.")
        if not EMAIL_RE.match(email):
            raise ValueError("Informe um e-mail válido.")
        admin = perfil == "ADMINISTRADOR" or bool(payload.get("pode_admin"))
        if admin:
            perfil = "ADMINISTRADOR"
            flags = (1, 1, 1, 1)
            gabinetes = list(GABINETES)
        else:
            flags = (
                flag(payload.get("pode_portarias")),
                flag(payload.get("pode_agenda")),
                flag(payload.get("pode_oficios")),
                0,
            )
            gabinetes = []
            if flags[2]:
                requested = payload.get("gabinetes") or []
                unknown = [g for g in requested if g not in GABINETES]
                if unknown:
                    raise ValueError("Gabinete inválido.")
                gabinetes = [g for g in GABINETES if g in set(requested)]
        ativo = flag(True if payload.get("ativo", True) else False)
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            duplicate = c.execute(
                "SELECT id FROM usuarios_acesso WHERE email=?", (email,)
            ).fetchone()
            if duplicate and (identifier is None or duplicate["id"] != identifier):
                raise ValueError("Já existe um usuário com este e-mail.")
            if identifier is None:
                inserted = c.execute(
                    "INSERT INTO usuarios_acesso(nome,email,perfil,ativo,pode_portarias,"
                    "pode_agenda,pode_oficios,pode_admin,criado_em,atualizado_em) "
                    "VALUES(?,?,?,?,?,?,?,?,?,?)",
                    (nome, email, perfil, ativo, *flags, stamp, stamp),
                )
                identifier = inserted.lastrowid
                action = "acesso_criar_usuario"
            else:
                current = c.execute(
                    "SELECT id FROM usuarios_acesso WHERE id=?", (identifier,)
                ).fetchone()
                if not current:
                    raise ValueError("Usuário não encontrado.")
                c.execute(
                    "UPDATE usuarios_acesso SET nome=?,email=?,perfil=?,ativo=?,"
                    "pode_portarias=?,pode_agenda=?,pode_oficios=?,pode_admin=?,"
                    "atualizado_em=? WHERE id=?",
                    (nome, email, perfil, ativo, *flags, stamp, identifier),
                )
                action = "acesso_atualizar_usuario"
            c.execute("DELETE FROM usuario_gabinetes WHERE usuario_id=?", (identifier,))
            c.executemany(
                "INSERT INTO usuario_gabinetes VALUES(?,?)",
                [(identifier, code) for code in gabinetes],
            )
            self.store.event(
                c,
                action,
                {"id": identifier, "email": email, "perfil": perfil, "ativo": ativo},
            )
        return identifier

    def set_active(self, identifier, active):
        user = self.get(identifier)
        user["ativo"] = bool(active)
        return self.save_user(user, identifier)

    def _hydrate(self, c, row):
        record = dict(row)
        record["ativo"] = bool(record["ativo"])
        for key in ("pode_portarias", "pode_agenda", "pode_oficios", "pode_admin"):
            record[key] = bool(record[key])
        record["gabinetes"] = [
            r[0]
            for r in c.execute(
                "SELECT gabinete FROM usuario_gabinetes WHERE usuario_id=? ORDER BY gabinete",
                (record["id"],),
            )
        ]
        return record


def ensure_schema(store):
    AccessStore(store)
