"""Additive authorized-users schema on the existing Store connection."""

import re
from database.store import now, schema_key_of, unwrap_store
from services.oficios import GABINETES

PROFILES = ("ADMINISTRADOR", "USUARIO")
EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
MARKER = "acesso_schema_v1"
PROTECTED_ADMIN_EMAIL = "alpereira@tce.pb.gov.br"
PROTECTED_ADMIN_MESSAGE = (
    "Este administrador é protegido e não pode ter seu acesso administrativo removido."
)
LAST_ADMIN_MESSAGE = "O sistema deve manter pelo menos um administrador ativo."
_READY = set()
GABINETE_LIST = ",".join("'" + code + "'" for code in GABINETES)
USER_COLUMNS = (
    "id,nome,email,perfil,ativo,pode_portarias,pode_agenda,pode_oficios,pode_memorandos,pode_admin,"
    "protegido,criado_em,atualizado_em"
)


def normalize_email(value):
    return (value or "").strip().lower()


def flag(value):
    return 1 if value else 0


class AccessStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        if schema_key_of(self.store) not in _READY:
            self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        with self.store.connection(read_only=True) as c:
            marker = c.execute(
                "SELECT valor FROM configuracoes WHERE chave=?", (MARKER,)
            ).fetchone()
            columns = self._table_columns(c)
        if marker and "pode_memorandos" in columns and "protegido" in columns:
            with self.store.connection() as c:
                c.execute("BEGIN IMMEDIATE")
                self._mark_protected_admin(c)
            _READY.add(key)
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS usuarios_acesso ("
                f"id {identity},"
                "nome TEXT NOT NULL,"
                "email TEXT NOT NULL UNIQUE,"
                "perfil TEXT NOT NULL CHECK(perfil IN ('ADMINISTRADOR','USUARIO')),"
                "ativo INTEGER NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)),"
                "pode_portarias INTEGER NOT NULL DEFAULT 0 CHECK(pode_portarias IN (0,1)),"
                "pode_agenda INTEGER NOT NULL DEFAULT 0 CHECK(pode_agenda IN (0,1)),"
                "pode_oficios INTEGER NOT NULL DEFAULT 0 CHECK(pode_oficios IN (0,1)),"
                "pode_memorandos INTEGER NOT NULL DEFAULT 0 CHECK(pode_memorandos IN (0,1)),"
                "pode_admin INTEGER NOT NULL DEFAULT 0 CHECK(pode_admin IN (0,1)),"
                "protegido INTEGER NOT NULL DEFAULT 0 CHECK(protegido IN (0,1)),"
                "criado_em TEXT NOT NULL,"
                "atualizado_em TEXT NOT NULL)"
            )
            # Existing installations predate the additive permission column.
            if self.store.backend == "postgresql":
                columns = {
                    r[0]
                    for r in c.execute(
                        "SELECT column_name FROM information_schema.columns "
                        "WHERE table_schema=current_schema() AND table_name='usuarios_acesso'"
                    )
                }
            else:
                columns = {r[1] for r in c.execute("PRAGMA table_info(usuarios_acesso)")}
            if "pode_memorandos" not in columns:
                c.execute(
                    "ALTER TABLE usuarios_acesso ADD COLUMN pode_memorandos INTEGER NOT NULL DEFAULT 0"
                )
            if "protegido" not in columns:
                c.execute(
                    "ALTER TABLE usuarios_acesso ADD COLUMN protegido INTEGER NOT NULL DEFAULT 0"
                )
            c.execute("UPDATE usuarios_acesso SET pode_memorandos=1 WHERE perfil='ADMINISTRADOR'")
            fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
            c.execute(
                "CREATE TABLE IF NOT EXISTS usuario_gabinetes ("
                f"usuario_id {fk} NOT NULL REFERENCES usuarios_acesso(id) ON DELETE CASCADE,"
                f"gabinete TEXT NOT NULL CHECK(gabinete IN ({GABINETE_LIST})),"
                "PRIMARY KEY(usuario_id, gabinete))"
            )
            self._mark_protected_admin(c)
            c.execute(
                "INSERT INTO configuracoes VALUES(?,?) ON CONFLICT DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def _table_columns(self, c):
        if self.store.backend == "postgresql":
            return {
                r[0]
                for r in c.execute(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_schema=current_schema() AND table_name='usuarios_acesso'"
                )
            }
        return {r[1] for r in c.execute("PRAGMA table_info(usuarios_acesso)")}

    def _mark_protected_admin(self, c):
        c.execute(
            "UPDATE usuarios_acesso SET protegido=1, perfil='ADMINISTRADOR', ativo=1, "
            "pode_admin=1, pode_portarias=1, pode_agenda=1, pode_oficios=1, pode_memorandos=1 "
            "WHERE email=?",
            (PROTECTED_ADMIN_EMAIL,),
        )
        row = c.execute(
            "SELECT id FROM usuarios_acesso WHERE email=?",
            (PROTECTED_ADMIN_EMAIL,),
        ).fetchone()
        if not row:
            return
        identifier = row["id"]
        c.execute("DELETE FROM usuario_gabinetes WHERE usuario_id=?", (identifier,))
        c.executemany(
            "INSERT INTO usuario_gabinetes VALUES(?,?)",
            [(identifier, code) for code in GABINETES],
        )

    def get_by_email(self, email):
        email = normalize_email(email)
        if not email:
            return None
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {USER_COLUMNS} FROM usuarios_acesso WHERE email=?",
                (email,),
            ).fetchone()
            return self._hydrate(c, row) if row else None

    def get(self, identifier):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {USER_COLUMNS} FROM usuarios_acesso WHERE id=?",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Usuário não encontrado.")
            return self._hydrate(c, row)

    def list_users(self):
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT {USER_COLUMNS} FROM usuarios_acesso ORDER BY nome,email"
            ).fetchall()
            gabinetes = {}
            for item in c.execute(
                "SELECT usuario_id,gabinete FROM usuario_gabinetes ORDER BY gabinete"
            ):
                gabinetes.setdefault(item[0], []).append(item[1])
            users = []
            for row in rows:
                record = dict(row)
                record["ativo"] = bool(record["ativo"])
                for key in (
                    "pode_portarias",
                    "pode_agenda",
                    "pode_oficios",
                    "pode_memorandos",
                    "pode_admin",
                    "protegido",
                ):
                    record[key] = bool(record[key])
                record["gabinetes"] = gabinetes.get(record["id"], [])
                users.append(record)
            return users

    def save_user(self, payload, identifier=None):
        nome = (payload.get("nome") or "").strip()
        email = normalize_email(payload.get("email"))
        perfil = (payload.get("perfil") or "USUARIO").strip().upper()
        if perfil not in PROFILES:
            raise ValueError("Perfil inválido.")
        if not nome:
            raise ValueError("Informe o nome.")
        if not EMAIL_RE.match(email):
            raise ValueError("Informe um e-mail válido.")
        if perfil == "ADMINISTRADOR":
            flags = (1, 1, 1, 1, 1)
            gabinetes = list(GABINETES)
        else:
            flags = (
                flag(payload.get("pode_portarias")),
                flag(payload.get("pode_agenda")),
                flag(payload.get("pode_oficios")),
                flag(payload.get("pode_memorandos")),
                flag(payload.get("pode_admin")),
            )
            gabinetes = []
            if flags[2]:
                requested = payload.get("gabinetes") or []
                unknown = [g for g in requested if g not in GABINETES]
                if unknown:
                    raise ValueError("Gabinete inválido.")
                gabinetes = [g for g in GABINETES if g in set(requested)]
        ativo = flag(True if payload.get("ativo", True) else False)
        protegido = flag(email == PROTECTED_ADMIN_EMAIL)
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            duplicate = c.execute(
                "SELECT id FROM usuarios_acesso WHERE email=?", (email,)
            ).fetchone()
            if duplicate and (identifier is None or duplicate["id"] != identifier):
                raise ValueError("Já existe um usuário com este e-mail.")
            existing = None
            if identifier is not None:
                row = c.execute(
                    f"SELECT {USER_COLUMNS} FROM usuarios_acesso WHERE id=?",
                    (identifier,),
                ).fetchone()
                if not row:
                    raise ValueError("Usuário não encontrado.")
                existing = dict(row)
                existing["ativo"] = bool(existing["ativo"])
                existing["protegido"] = bool(existing.get("protegido"))
                existing["pode_admin"] = bool(existing["pode_admin"])
            self._reject_protected_changes(existing, email, perfil, ativo, flags[4])
            self._reject_last_administrator_loss(c, existing, perfil, ativo)
            if identifier is None:
                inserted = c.execute(
                    "INSERT INTO usuarios_acesso(nome,email,perfil,ativo,pode_portarias,"
                    "pode_agenda,pode_oficios,pode_memorandos,pode_admin,protegido,criado_em,atualizado_em) "
                    "VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",
                    (nome, email, perfil, ativo, *flags, protegido, stamp, stamp),
                )
                identifier = inserted.lastrowid
                action = "acesso_criar_usuario"
            else:
                c.execute(
                    "UPDATE usuarios_acesso SET nome=?,email=?,perfil=?,ativo=?,"
                    "pode_portarias=?,pode_agenda=?,pode_oficios=?,pode_memorandos=?,pode_admin=?,"
                    "atualizado_em=? WHERE id=?",
                    (nome, email, perfil, ativo, *flags, stamp, identifier),
                )
                if email == PROTECTED_ADMIN_EMAIL:
                    self._mark_protected_admin(c)
                action = "acesso_atualizar_usuario"
            c.execute("DELETE FROM usuario_gabinetes WHERE usuario_id=?", (identifier,))
            c.executemany(
                "INSERT INTO usuario_gabinetes VALUES(?,?)",
                [(identifier, code) for code in gabinetes],
            )
            self.store.event(
                c,
                action,
                {"id": identifier, "email": email, "perfil": perfil, "ativo": ativo},
            )
        return identifier

    def _reject_protected_changes(self, existing, email, perfil, ativo, pode_admin):
        protected = bool(existing and existing.get("protegido")) or email == PROTECTED_ADMIN_EMAIL
        if not protected:
            return
        if existing is None:
            if perfil != "ADMINISTRADOR" or not ativo or not pode_admin:
                raise ValueError(PROTECTED_ADMIN_MESSAGE)
            return
        if (
            perfil != "ADMINISTRADOR"
            or not ativo
            or not pode_admin
            or email != existing["email"]
        ):
            raise ValueError(PROTECTED_ADMIN_MESSAGE)

    def _reject_last_administrator_loss(self, c, existing, perfil, ativo):
        if not existing:
            return
        was_admin = existing["perfil"] == "ADMINISTRADOR" and existing["ativo"]
        stays_admin = perfil == "ADMINISTRADOR" and ativo
        if not was_admin or stays_admin:
            return
        remaining = c.execute(
            "SELECT COUNT(*) FROM usuarios_acesso "
            "WHERE perfil='ADMINISTRADOR' AND ativo=1 AND id!=?",
            (existing["id"],),
        ).fetchone()[0]
        if remaining == 0:
            raise ValueError(LAST_ADMIN_MESSAGE)

    def set_active(self, identifier, active):
        user = self.get(identifier)
        user["ativo"] = bool(active)
        return self.save_user(user, identifier)

    def active_administrator_count(self, exclude_id=None):
        with self.store.connection(read_only=True) as c:
            if exclude_id is None:
                row = c.execute(
                    "SELECT COUNT(*) FROM usuarios_acesso "
                    "WHERE perfil='ADMINISTRADOR' AND ativo=1"
                ).fetchone()
            else:
                row = c.execute(
                    "SELECT COUNT(*) FROM usuarios_acesso "
                    "WHERE perfil='ADMINISTRADOR' AND ativo=1 AND id!=?",
                    (exclude_id,),
                ).fetchone()
            return row[0]

    def delete_user(self, identifier, *, actor_id=None):
        user = self.get(identifier)
        if user.get("protegido"):
            raise ValueError(PROTECTED_ADMIN_MESSAGE)
        if actor_id is not None and identifier == actor_id:
            raise ValueError("Não é permitido excluir o próprio cadastro.")
        if (
            user["perfil"] == "ADMINISTRADOR"
            and user["ativo"]
            and self.active_administrator_count(exclude_id=identifier) == 0
        ):
            raise ValueError("Não é possível excluir o último administrador ativo.")
        snapshot = {
            "id": user["id"],
            "email": user["email"],
            "nome": user["nome"],
            "perfil": user["perfil"],
        }
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            current = c.execute(
                f"SELECT {USER_COLUMNS} FROM usuarios_acesso WHERE id=?",
                (identifier,),
            ).fetchone()
            if not current:
                raise ValueError("Usuário não encontrado.")
            if current["perfil"] == "ADMINISTRADOR" and current["ativo"]:
                remaining = c.execute(
                    "SELECT COUNT(*) FROM usuarios_acesso "
                    "WHERE perfil='ADMINISTRADOR' AND ativo=1 AND id!=?",
                    (identifier,),
                ).fetchone()[0]
                if remaining == 0:
                    raise ValueError(
                        "Não é possível excluir o último administrador ativo."
                    )
            c.execute("DELETE FROM usuarios_acesso WHERE id=?", (identifier,))
            leftover = c.execute(
                "SELECT COUNT(*) FROM usuario_gabinetes WHERE usuario_id=?",
                (identifier,),
            ).fetchone()[0]
            if leftover:
                raise ValueError("Não foi possível remover os gabinetes do usuário.")
            self.store.event(c, "acesso_excluir_usuario", snapshot)
        return snapshot

    def _hydrate(self, c, row):
        record = dict(row)
        record["ativo"] = bool(record["ativo"])
        for key in ("pode_portarias", "pode_agenda", "pode_oficios", "pode_memorandos", "pode_admin", "protegido"):
            record[key] = bool(record.get(key))
        record["gabinetes"] = [
            r[0]
            for r in c.execute(
                "SELECT gabinete FROM usuario_gabinetes WHERE usuario_id=? ORDER BY gabinete",
                (record["id"],),
            )
        ]
        return record


def ensure_schema(store):
    AccessStore(store)
