"""Per-user presentation state for alerts derived from live records.

This table intentionally stores no alert payload.  The originating module stays
authoritative; a row merely says how one user has attended to one stable logical
alert key.
"""

from datetime import datetime, timezone

from database.store import now, schema_key_of, unwrap_store


MARKER = "alert_attention_schema_v1"
_READY = set()


class AlertAttentionStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        user_type = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS alertas_atencao (id {identity},"
                f"usuario_id {user_type} NOT NULL REFERENCES usuarios_acesso(id) ON DELETE CASCADE,"
                "chave_alerta TEXT NOT NULL, lido_em TEXT, adiado_ate TEXT, "
                "criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL, "
                "UNIQUE(usuario_id,chave_alerta))"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS alertas_atencao_usuario_adiado_idx "
                "ON alertas_atencao(usuario_id,adiado_ate)"
            )
            c.execute(
                "INSERT INTO configuracoes(chave,valor) VALUES(?,?) "
                "ON CONFLICT(chave) DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def states(self, user_id, keys):
        keys = tuple(dict.fromkeys(str(key) for key in keys if key))
        if not keys:
            return {}
        placeholders = ",".join("?" for _ in keys)
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                "SELECT chave_alerta,lido_em,adiado_ate FROM alertas_atencao "
                f"WHERE usuario_id=? AND chave_alerta IN ({placeholders})",
                (user_id, *keys),
            ).fetchall()
        return {row["chave_alerta"]: dict(row) for row in rows}

    def mark_read(self, user_id, key, *, read=True):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                "INSERT INTO alertas_atencao(usuario_id,chave_alerta,lido_em,adiado_ate,criado_em,atualizado_em) "
                "VALUES(?,?,?,?,?,?) ON CONFLICT(usuario_id,chave_alerta) DO UPDATE SET "
                "lido_em=excluded.lido_em, atualizado_em=excluded.atualizado_em",
                (user_id, str(key), stamp if read else None, None, stamp, stamp),
            )

    def mark_all_read(self, user_id, keys):
        # Only live, authorized keys supplied by the caller are ever changed.
        keys = tuple(dict.fromkeys(str(key) for key in keys if key))
        if not keys:
            return
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.executemany(
                "INSERT INTO alertas_atencao(usuario_id,chave_alerta,lido_em,adiado_ate,criado_em,atualizado_em) "
                "VALUES(?,?,?,?,?,?) ON CONFLICT(usuario_id,chave_alerta) DO UPDATE SET "
                "lido_em=excluded.lido_em, atualizado_em=excluded.atualizado_em",
                [(user_id, key, stamp, None, stamp, stamp) for key in keys],
            )

    def snooze(self, user_id, key, until):
        if not isinstance(until, datetime) or until.tzinfo is None:
            raise ValueError("Informe data e horário válidos para o adiamento.")
        stamp = now()
        wake = until.astimezone(timezone.utc).isoformat()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                "INSERT INTO alertas_atencao(usuario_id,chave_alerta,lido_em,adiado_ate,criado_em,atualizado_em) "
                "VALUES(?,?,?,?,?,?) ON CONFLICT(usuario_id,chave_alerta) DO UPDATE SET "
                "adiado_ate=excluded.adiado_ate, atualizado_em=excluded.atualizado_em",
                (user_id, str(key), None, wake, stamp, stamp),
            )


def ensure_schema(store):
    AlertAttentionStore(store)
