"""Additive append-only audit events for SQLite and PostgreSQL."""

from database.store import schema_key_of, unwrap_store

MARKER = "auditoria_schema_v1"
_READY = set()
PAGE_SIZE = 50
EXPORT_LIMIT = 5000
COLUMNS = (
    "id,usuario_id,usuario_email,usuario_nome,sessao_id,evento,modulo,acao,"
    "entidade_tipo,entidade_id,resultado,detalhes_json,criado_em"
)

INDEX_SQL = (
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_criado_em_idx "
    "ON auditoria_eventos(criado_em DESC, id DESC)",
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_usuario_id_idx "
    "ON auditoria_eventos(usuario_id)",
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_usuario_email_idx "
    "ON auditoria_eventos(usuario_email)",
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_modulo_idx "
    "ON auditoria_eventos(modulo)",
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_evento_idx "
    "ON auditoria_eventos(evento)",
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_acao_idx "
    "ON auditoria_eventos(acao)",
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_resultado_idx "
    "ON auditoria_eventos(resultado)",
    "CREATE INDEX IF NOT EXISTS auditoria_eventos_sessao_idx "
    "ON auditoria_eventos(sessao_id)",
)


class AuditStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        if schema_key_of(self.store) not in _READY:
            self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        with self.store.connection(read_only=True) as c:
            marker = c.execute(
                "SELECT valor FROM configuracoes WHERE chave=?", (MARKER,)
            ).fetchone()
            exists = self._table_exists(c)
        if marker and exists:
            with self.store.connection() as c:
                c.execute("BEGIN IMMEDIATE")
                for statement in INDEX_SQL:
                    c.execute(statement)
            _READY.add(key)
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS auditoria_eventos ("
                f"id {identity},"
                f"usuario_id {fk},"
                "usuario_email TEXT NOT NULL DEFAULT '',"
                "usuario_nome TEXT NOT NULL DEFAULT '',"
                "sessao_id TEXT,"
                "evento TEXT NOT NULL,"
                "modulo TEXT NOT NULL DEFAULT '',"
                "acao TEXT NOT NULL DEFAULT '',"
                "entidade_tipo TEXT,"
                "entidade_id TEXT,"
                "resultado TEXT NOT NULL DEFAULT 'OK',"
                "detalhes_json TEXT,"
                "criado_em TEXT NOT NULL)"
            )
            for statement in INDEX_SQL:
                c.execute(statement)
            c.execute(
                "INSERT INTO configuracoes VALUES(?,?) ON CONFLICT DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def _table_exists(self, c):
        if self.store.backend == "postgresql":
            row = c.execute(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema=current_schema() AND table_name='auditoria_eventos'"
            ).fetchone()
            return bool(row)
        row = c.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='auditoria_eventos'"
        ).fetchone()
        return bool(row)

    def insert(self, row):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            inserted = c.execute(
                "INSERT INTO auditoria_eventos("
                "usuario_id,usuario_email,usuario_nome,sessao_id,evento,modulo,acao,"
                "entidade_tipo,entidade_id,resultado,detalhes_json,criado_em) "
                "VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    row.get("usuario_id"),
                    row.get("usuario_email") or "",
                    row.get("usuario_nome") or "",
                    row.get("sessao_id"),
                    row["evento"],
                    row.get("modulo") or "",
                    row.get("acao") or "",
                    row.get("entidade_tipo"),
                    None if row.get("entidade_id") is None else str(row.get("entidade_id")),
                    row.get("resultado") or "OK",
                    row.get("detalhes_json"),
                    row["criado_em"],
                ),
            )
            return inserted.lastrowid

    def _filters(self, filters):
        clauses = []
        args = []
        start = (filters or {}).get("inicio")
        end = (filters or {}).get("fim")
        if start:
            clauses.append("criado_em>=?")
            args.append(start)
        if end:
            clauses.append("criado_em<=?")
            args.append(end)
        email = (filters or {}).get("usuario_email")
        if email:
            clauses.append("usuario_email=?")
            args.append(email)
        usuario_id = (filters or {}).get("usuario_id")
        if usuario_id:
            clauses.append("usuario_id=?")
            args.append(usuario_id)
        modulo = (filters or {}).get("modulo")
        if modulo:
            clauses.append("modulo=?")
            args.append(modulo)
        evento = (filters or {}).get("evento")
        if evento:
            clauses.append("evento=?")
            args.append(evento)
        acao = (filters or {}).get("acao")
        if acao:
            clauses.append("acao=?")
            args.append(acao)
        resultado = (filters or {}).get("resultado")
        if resultado:
            clauses.append("resultado=?")
            args.append(resultado)
        if (filters or {}).get("somente_admin"):
            clauses.append("modulo=?")
            args.append("admin")
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        return where, args

    def count(self, filters=None):
        where, args = self._filters(filters)
        with self.store.connection(read_only=True) as c:
            return c.execute(
                "SELECT COUNT(*) FROM auditoria_eventos" + where, args
            ).fetchone()[0]

    def list_events(self, filters=None, *, limit=PAGE_SIZE, offset=0):
        where, args = self._filters(filters)
        limit = max(1, min(int(limit), EXPORT_LIMIT))
        offset = max(0, int(offset))
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT {COLUMNS} FROM auditoria_eventos{where} "
                "ORDER BY criado_em DESC, id DESC LIMIT ? OFFSET ?",
                (*args, limit, offset),
            ).fetchall()
            return [dict(r) for r in rows]

    def get(self, identifier):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {COLUMNS} FROM auditoria_eventos WHERE id=?",
                (identifier,),
            ).fetchone()
            return dict(row) if row else None

    def period_summary(self, start, end):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT "
                "COUNT(DISTINCT CASE WHEN evento='SESSAO_INICIADA' AND usuario_id IS NOT NULL "
                "THEN usuario_id END),"
                "SUM(CASE WHEN evento='SESSAO_INICIADA' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN evento NOT IN ('SESSAO_INICIADA','ACESSO_AUTORIZADO') "
                "THEN 1 ELSE 0 END) "
                "FROM auditoria_eventos WHERE criado_em>=? AND criado_em<=?",
                (start, end),
            ).fetchone()
        users, sessions, actions = row[0] or 0, row[1] or 0, row[2] or 0
        return {
            "usuarios": int(users),
            "sessoes": int(sessions),
            "acoes": int(actions),
        }

    def latest_access(self):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT usuario_nome,usuario_email,criado_em FROM auditoria_eventos "
                "WHERE evento='SESSAO_INICIADA' ORDER BY criado_em DESC, id DESC LIMIT 1"
            ).fetchone()
            if not row:
                return None
            return {
                "nome": row[0],
                "email": row[1],
                "criado_em": row[2],
            }

    def top_module(self, start=None, end=None):
        clauses = ["evento='MODULO_ACESSADO'", "modulo!=''"]
        args = []
        if start:
            clauses.append("criado_em>=?")
            args.append(start)
        if end:
            clauses.append("criado_em<=?")
            args.append(end)
        where = " WHERE " + " AND ".join(clauses)
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT modulo, COUNT(*) AS n FROM auditoria_eventos"
                + where
                + " GROUP BY modulo ORDER BY n DESC, modulo LIMIT 1",
                args,
            ).fetchone()
            if not row:
                return None
            return {"modulo": row[0], "quantidade": row[1]}

    def user_rows(self, filters=None):
        where, args = self._filters(filters)
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                "SELECT usuario_id,usuario_email,usuario_nome,"
                "MIN(criado_em) AS primeira_atividade,"
                "MAX(criado_em) AS ultima_atividade,"
                "MIN(CASE WHEN evento='SESSAO_INICIADA' THEN criado_em END) AS primeiro_acesso,"
                "MAX(CASE WHEN evento='SESSAO_INICIADA' THEN criado_em END) AS ultimo_acesso,"
                "SUM(CASE WHEN evento='SESSAO_INICIADA' THEN 1 ELSE 0 END) AS sessoes "
                "FROM auditoria_eventos"
                + where
                + " GROUP BY usuario_id,usuario_email,usuario_nome "
                "ORDER BY MAX(CASE WHEN evento='SESSAO_INICIADA' THEN criado_em END) DESC, "
                "MAX(criado_em) DESC",
                args,
            ).fetchall()
            emails = [r[1] for r in rows if r[1]]
            modules = {}
            days = {}
            if emails:
                placeholders = ",".join("?" * len(emails))
                extra = list(args)
                extra.extend(emails)
                for item in c.execute(
                    "SELECT usuario_email,modulo,criado_em FROM auditoria_eventos"
                    + where
                    + (" AND " if where else " WHERE ")
                    + f"usuario_email IN ({placeholders})",
                    extra,
                ):
                    email = item[0]
                    if item[1]:
                        modules.setdefault(email, set()).add(item[1])
                    days.setdefault(email, set()).add((item[2] or "")[:10])
            result = []
            for row in rows:
                record = dict(row)
                email = record["usuario_email"]
                record["modulos"] = sorted(modules.get(email, ()))
                record["dias_distintos"] = len(days.get(email, ()))
                record["sessoes"] = int(record["sessoes"] or 0)
                result.append(record)
            return result

    def user_timeline(self, email, *, limit=80):
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT {COLUMNS} FROM auditoria_eventos WHERE usuario_email=? "
                "ORDER BY criado_em DESC, id DESC LIMIT ?",
                (email, limit),
            ).fetchall()
            return [dict(r) for r in rows]

    def session_bounds(self, sessao_id):
        if not sessao_id:
            return None
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT MIN(criado_em), MAX(criado_em) FROM auditoria_eventos "
                "WHERE sessao_id=?",
                (sessao_id,),
            ).fetchone()
            if not row or not row[0]:
                return None
            return {"inicio": row[0], "fim": row[1]}

    def distinct_values(self, column):
        if column not in ("modulo", "evento", "acao", "resultado", "usuario_email"):
            raise ValueError("Coluna inválida.")
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT DISTINCT {column} FROM auditoria_eventos "
                f"WHERE {column} IS NOT NULL AND {column}!='' ORDER BY {column}"
            ).fetchall()
            return [r[0] for r in rows]


def ensure_schema(store):
    AuditStore(store)
