"""Administrative internship placements backed by the Memorandos people catalog."""

from datetime import date

from database.store import now, schema_key_of, unwrap_store

MARKER = "estagiarios_schema_v1"
# Siglas próprias deste cadastro. Os nomes foram confirmados nos catálogos de
# Ofícios/Tramita; MTTF e BLTC são a grafia administrativa desta tela.
GABINETES = {
    "MTTF": "Marcílio Toscano Franca Filho",
    "ESPO": "Elvira Samara Pereira de Oliveira",
    "BLTC": "Bradson Tibério Luna Camelo",
    "SBBQ": "Sheyla Barreto Braga de Queiroz",
    "IBMF": "Isabella Barbosa Marinho Falcão",
    "MASN": "Manoel Antônio dos Santos Neto",
    "LAF": "Luciano Andrade Farias",
}
LOTACOES = tuple(GABINETES)
LEGACY_LOTACOES = ("PROGE",)
_READY = set()


def limite_padrao(inicio):
    """Return two calendar years after *inicio*, including leap-day handling."""
    try:
        return inicio.replace(year=inicio.year + 2)
    except ValueError:
        return inicio.replace(year=inicio.year + 2, day=28)


class EstagiariosStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        with self.store.connection(read_only=True) as c:
            marked = c.execute("SELECT 1 FROM configuracoes WHERE chave=?", (MARKER,)).fetchone()
        identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.store.backend == "postgresql" else "INTEGER PRIMARY KEY"
        person_id = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS estagiarios_lotacoes ("
                f"id {identity}, pessoa_id {person_id} NOT NULL REFERENCES servidores(id), "
                "lotacao TEXT NOT NULL, data_inicio TEXT NOT NULL, data_limite TEXT NOT NULL, "
                "data_encerramento TEXT, ativo INTEGER NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)), "
                "criado_em TEXT NOT NULL, criado_por TEXT NOT NULL DEFAULT '', "
                "atualizado_em TEXT NOT NULL, atualizado_por TEXT NOT NULL DEFAULT '', "
                "CHECK(lotacao IN ('MTTF','ESPO','BLTC','SBBQ','IBMF','MASN','LAF')), "
                "CHECK(data_limite >= data_inicio), "
                "CHECK(data_encerramento IS NULL OR data_encerramento >= data_inicio))"
            )
            c.execute("CREATE INDEX IF NOT EXISTS estagiarios_lotacoes_ativos_idx ON estagiarios_lotacoes(lotacao,ativo)")
            c.execute("CREATE INDEX IF NOT EXISTS estagiarios_lotacoes_pessoa_idx ON estagiarios_lotacoes(pessoa_id,ativo)")
            # Earlier installations accepted PROGE. Preserve those historic rows
            # for correction, but protect the revised seven-cabinet rule at the
            # database boundary as well as in the service layer.
            if self.store.backend == "postgresql":
                c.execute(
                    "CREATE OR REPLACE FUNCTION estagiarios_rejeitar_proge() "
                    "RETURNS trigger AS $$ BEGIN "
                    "IF NEW.lotacao='PROGE' AND (TG_OP='INSERT' OR NEW.lotacao IS DISTINCT FROM OLD.lotacao) "
                    "THEN RAISE EXCEPTION 'PROGE não é uma lotação válida para estagiários'; END IF; "
                    "RETURN NEW; END; $$ LANGUAGE plpgsql"
                )
                c.execute("DROP TRIGGER IF EXISTS estagiarios_rejeitar_proge ON estagiarios_lotacoes")
                c.execute(
                    "CREATE TRIGGER estagiarios_rejeitar_proge BEFORE INSERT OR UPDATE OF lotacao "
                    "ON estagiarios_lotacoes FOR EACH ROW EXECUTE FUNCTION estagiarios_rejeitar_proge()"
                )
            else:
                c.execute(
                    "CREATE TRIGGER IF NOT EXISTS estagiarios_rejeitar_proge_insert "
                    "BEFORE INSERT ON estagiarios_lotacoes WHEN NEW.lotacao='PROGE' "
                    "BEGIN SELECT RAISE(ABORT,'PROGE não é uma lotação válida para estagiários'); END"
                )
                c.execute(
                    "CREATE TRIGGER IF NOT EXISTS estagiarios_rejeitar_proge_update "
                    "BEFORE UPDATE OF lotacao ON estagiarios_lotacoes WHEN NEW.lotacao='PROGE' "
                    "BEGIN SELECT RAISE(ABORT,'PROGE não é uma lotação válida para estagiários'); END"
                )
            c.execute("INSERT INTO configuracoes VALUES(?,?) ON CONFLICT DO NOTHING", (MARKER, "1"))
        _READY.add(key)

    @staticmethod
    def _require_admin(administrator):
        if not administrator:
            raise ValueError("Apenas administradores podem gerenciar estagiários.")

    @staticmethod
    def _validate(lotacao, inicio, limite, encerramento=None):
        if lotacao not in LOTACOES:
            raise ValueError("Lotação inválida.")
        if limite < inicio:
            raise ValueError("A data limite não pode anteceder o início.")
        if encerramento and encerramento < inicio:
            raise ValueError("O encerramento não pode anteceder o início.")

    def eligible_people(self):
        """Only explicit internship classifications from the shared people catalog."""
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                "SELECT id,nome,matricula_original,cargo,setor FROM servidores "
                "WHERE ativo=1 AND upper(cargo) LIKE ? ORDER BY nome",
                ("%ESTAG%",),
            )
            return [dict(row) for row in rows]

    def list(self, *, include_inactive=True):
        where = "" if include_inactive else " WHERE e.ativo=1"
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                "SELECT e.id,e.pessoa_id,e.lotacao,e.data_inicio,e.data_limite,e.data_encerramento,e.ativo,"
                "e.criado_em,e.criado_por,e.atualizado_em,e.atualizado_por,"
                "s.nome,s.matricula_original,s.cargo,s.setor "
                "FROM estagiarios_lotacoes e JOIN servidores s ON s.id=e.pessoa_id" + where +
                " ORDER BY e.lotacao,e.ativo DESC,e.data_inicio DESC,e.id DESC"
            )
            return [dict(row) for row in rows]

    def summary(self, today=None):
        today = today or date.today()
        active = [row for row in self.list(include_inactive=False) if row["lotacao"] in LOTACOES]
        ending = sum(1 for row in active if (date.fromisoformat(row["data_limite"]) - today).days <= 60)
        return {"total": len(LOTACOES) * 2, "ocupadas": len(active), "disponiveis": len(LOTACOES) * 2 - len(active), "encerramentos_proximos": ending}

    def current_composition(self):
        """Current, valid placements grouped by the seven internship cabinets."""
        active = self.list(include_inactive=False)
        return {
            code: [row for row in active if row["lotacao"] == code]
            for code in LOTACOES
        }

    def legacy_proge_active(self):
        """Legacy rows must be corrected manually; they never fill a current seat."""
        return [
            row for row in self.list(include_inactive=False)
            if row["lotacao"] in LEGACY_LOTACOES
        ]

    def _assert_active_constraints(self, c, pessoa_id, lotacao, *, exclude_id=None):
        suffix = " AND id<>?" if exclude_id is not None else ""
        args = [lotacao] + ([exclude_id] if exclude_id is not None else [])
        occupied = c.execute("SELECT COUNT(*) FROM estagiarios_lotacoes WHERE lotacao=? AND ativo=1" + suffix, args).fetchone()[0]
        if occupied >= 2:
            raise ValueError("Esta lotação já possui duas posições ativas.")
        args = [pessoa_id] + ([exclude_id] if exclude_id is not None else [])
        if c.execute("SELECT 1 FROM estagiarios_lotacoes WHERE pessoa_id=? AND ativo=1" + suffix, args).fetchone():
            raise ValueError("Este estagiário já possui vínculo ativo em outra lotação.")

    def _lock_active_placements(self, c):
        # PostgreSQL has no SQLite-style BEGIN IMMEDIATE. Serialize the short
        # check-and-write window so concurrent administrators cannot create a
        # third active seat (or duplicate a person) between validation and insert.
        if self.store.backend == "postgresql":
            c.execute("LOCK TABLE estagiarios_lotacoes IN EXCLUSIVE MODE")

    def create(self, pessoa_id, lotacao, inicio, limite=None, *, actor_email="", administrator=False):
        self._require_admin(administrator)
        inicio = date.fromisoformat(str(inicio))
        limite = limite_padrao(inicio)
        self._validate(lotacao, inicio, limite)
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            self._lock_active_placements(c)
            if not c.execute("SELECT 1 FROM servidores WHERE id=? AND ativo=1 AND upper(cargo) LIKE ?", (pessoa_id, "%ESTAG%")).fetchone():
                raise ValueError("Selecione uma pessoa ativa classificada como estagiária na Base de Servidores.")
            self._assert_active_constraints(c, pessoa_id, lotacao)
            inserted = c.execute(
                "INSERT INTO estagiarios_lotacoes(pessoa_id,lotacao,data_inicio,data_limite,ativo,criado_em,criado_por,atualizado_em,atualizado_por) VALUES(?,?,?,?,1,?,?,?,?)",
                (pessoa_id, lotacao, inicio.isoformat(), limite.isoformat(), stamp, actor_email, stamp, actor_email),
            )
            return inserted.lastrowid

    def update(self, identifier, lotacao, inicio, limite, *, actor_email="", administrator=False):
        self._require_admin(administrator)
        inicio = date.fromisoformat(str(inicio))
        limite = limite_padrao(inicio)
        self._validate(lotacao, inicio, limite)
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            self._lock_active_placements(c)
            row = c.execute("SELECT pessoa_id,ativo FROM estagiarios_lotacoes WHERE id=?", (identifier,)).fetchone()
            if not row:
                raise ValueError("Vínculo não encontrado.")
            if row["ativo"]:
                self._assert_active_constraints(c, row["pessoa_id"], lotacao, exclude_id=identifier)
            c.execute("UPDATE estagiarios_lotacoes SET lotacao=?,data_inicio=?,data_limite=?,atualizado_em=?,atualizado_por=? WHERE id=?", (lotacao, inicio.isoformat(), limite.isoformat(), now(), actor_email, identifier))

    def close(self, identifier, encerramento, *, actor_email="", administrator=False):
        self._require_admin(administrator)
        encerramento = date.fromisoformat(str(encerramento))
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            self._lock_active_placements(c)
            row = c.execute("SELECT data_inicio,ativo FROM estagiarios_lotacoes WHERE id=?", (identifier,)).fetchone()
            if not row:
                raise ValueError("Vínculo não encontrado.")
            if not row["ativo"]:
                raise ValueError("Este vínculo já está encerrado.")
            if encerramento < date.fromisoformat(row["data_inicio"]):
                raise ValueError("O encerramento não pode anteceder o início.")
            c.execute("UPDATE estagiarios_lotacoes SET ativo=0,data_encerramento=?,atualizado_em=?,atualizado_por=? WHERE id=?", (encerramento.isoformat(), now(), actor_email, identifier))

    def replace(self, identifier, pessoa_id, inicio, limite=None, *, actor_email="", administrator=False):
        self._require_admin(administrator)
        inicio = date.fromisoformat(str(inicio))
        limite = limite_padrao(inicio)
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            self._lock_active_placements(c)
            old = c.execute("SELECT lotacao,data_inicio,ativo FROM estagiarios_lotacoes WHERE id=?", (identifier,)).fetchone()
            if not old or not old["ativo"]:
                raise ValueError("Selecione um vínculo ativo para substituir.")
            if inicio < date.fromisoformat(old["data_inicio"]):
                raise ValueError("O início da substituição não pode anteceder o vínculo atual.")
            if not c.execute("SELECT 1 FROM servidores WHERE id=? AND ativo=1 AND upper(cargo) LIKE ?", (pessoa_id, "%ESTAG%")).fetchone():
                raise ValueError("Selecione uma pessoa ativa classificada como estagiária na Base de Servidores.")
            self._assert_active_constraints(c, pessoa_id, old["lotacao"], exclude_id=identifier)
            stamp = now()
            c.execute("UPDATE estagiarios_lotacoes SET ativo=0,data_encerramento=?,atualizado_em=?,atualizado_por=? WHERE id=?", (inicio.isoformat(), stamp, actor_email, identifier))
            created = c.execute("INSERT INTO estagiarios_lotacoes(pessoa_id,lotacao,data_inicio,data_limite,ativo,criado_em,criado_por,atualizado_em,atualizado_por) VALUES(?,?,?,?,1,?,?,?,?)", (pessoa_id, old["lotacao"], inicio.isoformat(), limite.isoformat(), stamp, actor_email, stamp, actor_email))
            return created.lastrowid
