"""Technical telemetry for one logical IA operation. No prompts or documents."""

from datetime import datetime, timedelta, timezone

from database.store import now, schema_key_of, unwrap_store

MARKER = "ia_telemetria_schema_v1"
_READY = set()
_CAMPOS = (
    "modulo",
    "operacao",
    "modelo_principal",
    "modelo_final",
    "tentativas",
    "retry",
    "fallback",
    "sucesso",
    "http_status",
    "categoria_erro",
    "duracao_ms",
    "viu_429",
    "viu_500",
    "viu_503",
)


def ensure_schema(store):
    store = unwrap_store(store)
    key = schema_key_of(store)
    if key in _READY:
        return
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if store.backend == "postgresql"
        else "INTEGER PRIMARY KEY"
    )
    with store.connection() as connection:
        connection.execute("BEGIN IMMEDIATE")
        connection.execute(
            f"CREATE TABLE IF NOT EXISTS ia_telemetria ("
            f"id {identity}, criado_em TEXT NOT NULL, "
            "modulo TEXT NOT NULL, operacao TEXT NOT NULL, "
            "modelo_principal TEXT NOT NULL, modelo_final TEXT, "
            "tentativas INTEGER NOT NULL, retry INTEGER NOT NULL, "
            "fallback INTEGER NOT NULL, sucesso INTEGER NOT NULL, "
            "http_status INTEGER, categoria_erro TEXT NOT NULL DEFAULT '', "
            "duracao_ms INTEGER NOT NULL, "
            "viu_429 INTEGER NOT NULL DEFAULT 0, "
            "viu_500 INTEGER NOT NULL DEFAULT 0, "
            "viu_503 INTEGER NOT NULL DEFAULT 0)"
        )
        connection.execute(
            "CREATE INDEX IF NOT EXISTS ia_telemetria_criado_em_idx "
            "ON ia_telemetria(criado_em)"
        )
        connection.execute(
            "INSERT INTO configuracoes(chave,valor) VALUES(?,?) "
            "ON CONFLICT(chave) DO NOTHING",
            (MARKER, "1"),
        )
    _READY.add(key)


def registrar(store, evento):
    """Persist one summary row. The caller isolates any failure."""
    store = unwrap_store(store)
    ensure_schema(store)
    values = [_texto(evento.get(campo), 80) for campo in ("modulo", "operacao")]
    values.append(_texto(evento.get("modelo_principal"), 80))
    values.append(_texto(evento.get("modelo_final"), 80))
    values.append(_inteiro(evento.get("tentativas")))
    values.extend(_bit(evento.get(campo)) for campo in ("retry", "fallback", "sucesso"))
    status = evento.get("http_status")
    values.append(None if status is None else _inteiro(status))
    values.append(_texto(evento.get("categoria_erro"), 40))
    values.append(_inteiro(evento.get("duracao_ms")))
    values.extend(
        _bit(evento.get(campo)) for campo in ("viu_429", "viu_500", "viu_503")
    )
    columns = ", ".join(_CAMPOS)
    placeholders = ", ".join("?" * len(_CAMPOS))
    with store.connection() as connection:
        connection.execute(
            f"INSERT INTO ia_telemetria (criado_em, {columns}) "
            f"VALUES (?, {placeholders})",
            (now(), *values),
        )


def resumo(store, horas):
    """Aggregate one window. Empty windows stay at zero."""
    store = unwrap_store(store)
    ensure_schema(store)
    inicio = (datetime.now(timezone.utc) - timedelta(hours=horas)).isoformat()
    with store.connection(read_only=True) as connection:
        row = connection.execute(
            "SELECT COUNT(*), "
            "SUM(CASE WHEN sucesso=1 THEN 1 ELSE 0 END), "
            "SUM(CASE WHEN sucesso=1 AND tentativas=1 THEN 1 ELSE 0 END), "
            "SUM(CASE WHEN retry=1 THEN 1 ELSE 0 END), "
            "SUM(CASE WHEN fallback=1 THEN 1 ELSE 0 END), "
            "SUM(CASE WHEN sucesso=0 THEN 1 ELSE 0 END), "
            "SUM(CASE WHEN viu_503=1 THEN 1 ELSE 0 END), "
            "AVG(duracao_ms) "
            "FROM ia_telemetria WHERE criado_em>=?",
            (inicio,),
        ).fetchone()
    total = int(row[0] or 0)
    sucesso = int(row[1] or 0)
    return {
        "total": total,
        "sucesso": sucesso,
        "taxa_sucesso": None if total == 0 else round(100 * sucesso / total),
        "primeira_tentativa": int(row[2] or 0),
        "retry": int(row[3] or 0),
        "fallback": int(row[4] or 0),
        "falhas": int(row[5] or 0),
        "viu_503": int(row[6] or 0),
        "duracao_media_ms": None if total == 0 else int(row[7] or 0),
    }


def _texto(value, limit):
    return " ".join(str(value or "").split())[:limit]


def _inteiro(value):
    return int(value or 0)


def _bit(value):
    return 1 if value else 0
