"""Persistent, versioned institutional reports independent from Tramita rows."""

import json
from threading import RLock

from database.store import now, unwrap_store


REPORT_TYPES = ("TRIMESTRAL", "ANUAL")
REPORT_STATUSES = ("RASCUNHO", "EM_REVISAO", "FINALIZADO", "ENVIADO")
_SCHEMA_LOCK = RLock()


class InstitutionalReportsStore:
    """Store immutable report snapshots; indicator calculations remain elsewhere."""

    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        with _SCHEMA_LOCK:
            if not getattr(self.store, "_institutional_reports_schema_ready", False):
                self._ensure_report_schema()
            self._ensure_pdf_schema()
            self._ensure_distribution_schema()

    def _ensure_report_schema(self):
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        snapshot_type = "JSONB" if self.store.backend == "postgresql" else "TEXT"
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            connection.execute(
                f"CREATE TABLE IF NOT EXISTS relatorios_institucionais ("
                f"id {identity}, tipo TEXT NOT NULL CHECK(tipo IN "
                "('TRIMESTRAL','ANUAL')), ano INTEGER NOT NULL, trimestre INTEGER, "
                "data_inicio TEXT NOT NULL, data_fim TEXT NOT NULL, "
                "periodo_parcial INTEGER NOT NULL DEFAULT 0 CHECK(periodo_parcial IN (0,1)), "
                "descricao_periodo TEXT NOT NULL DEFAULT '', "
                "status TEXT NOT NULL DEFAULT 'RASCUNHO' CHECK(status IN "
                "('RASCUNHO','EM_REVISAO','FINALIZADO','ENVIADO')), "
                "versao INTEGER NOT NULL CHECK(versao>=1), data_corte TEXT NOT NULL, "
                f"snapshot_dados {snapshot_type} NOT NULL, "
                f"conteudo_estruturado {snapshot_type} NOT NULL, "
                "criado_por TEXT NOT NULL DEFAULT '', criado_em TEXT NOT NULL, "
                "atualizado_por TEXT, atualizado_em TEXT, finalizado_por TEXT, "
                "finalizado_em TEXT, ativo INTEGER NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)), "
                "CHECK((tipo='TRIMESTRAL' AND trimestre BETWEEN 1 AND 4) "
                "OR (tipo='ANUAL' AND trimestre IS NULL)))"
            )
            connection.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS relatorios_institucionais_periodo_versao_uq "
                "ON relatorios_institucionais(tipo,ano,COALESCE(trimestre,0),versao)"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS relatorios_institucionais_consulta_idx "
                "ON relatorios_institucionais(tipo,ano,trimestre,status,versao)"
            )
        self.store._institutional_reports_schema_ready = True

    def _ensure_pdf_schema(self):
        """Official PDF bytes live beside the version, never in an ephemeral path."""
        if getattr(self.store, "_institutional_pdf_schema_ready", False):
            return
        binary = "BYTEA" if self.store.backend == "postgresql" else "BLOB"
        key = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            connection.execute(
                f"CREATE TABLE IF NOT EXISTS relatorios_institucionais_pdf ("
                f"relatorio_id {key} PRIMARY KEY REFERENCES relatorios_institucionais(id), "
                "nome_arquivo TEXT NOT NULL, "
                f"conteudo {binary} NOT NULL, sha256 TEXT NOT NULL, "
                "tamanho INTEGER NOT NULL, gerado_por TEXT NOT NULL DEFAULT '', "
                "gerado_em TEXT NOT NULL)"
            )
        self.store._institutional_pdf_schema_ready = True

    def _ensure_distribution_schema(self):
        """Distribution history points at the official PDF; it does not copy it."""
        if getattr(self.store, "_institutional_distribution_schema_ready", False):
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        key = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            connection.execute(
                f"CREATE TABLE IF NOT EXISTS relatorios_institucionais_envios ("
                f"id {identity}, relatorio_id {key} NOT NULL "
                "REFERENCES relatorios_institucionais(id), "
                f"origem_envio_id {key}, tipo TEXT NOT NULL, ano INTEGER NOT NULL, "
                "trimestre INTEGER, versao INTEGER NOT NULL, "
                "status_envio TEXT NOT NULL CHECK(status_envio IN "
                "('PREPARADO','ENVIANDO','ENVIADO','PARCIAL','FALHA')), "
                "remetente TEXT NOT NULL, assunto TEXT NOT NULL, corpo TEXT NOT NULL, "
                "pdf_nome TEXT NOT NULL, pdf_sha256 TEXT NOT NULL, "
                "pdf_tamanho INTEGER NOT NULL, criado_por TEXT NOT NULL DEFAULT '', "
                "criado_em TEXT NOT NULL, enviado_por TEXT NOT NULL DEFAULT '', "
                "enviado_em TEXT, provedor_mensagem_id TEXT NOT NULL DEFAULT '', "
                "erro_resumo TEXT NOT NULL DEFAULT '', "
                "chave_idempotencia TEXT NOT NULL UNIQUE)"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS relatorios_institucionais_envios_relatorio_idx "
                "ON relatorios_institucionais_envios(relatorio_id,id)"
            )
            connection.execute(
                f"CREATE TABLE IF NOT EXISTS relatorios_institucionais_envio_destinatarios ("
                f"id {identity}, envio_id {key} NOT NULL "
                "REFERENCES relatorios_institucionais_envios(id), "
                f"procurador_id {key}, procurador TEXT NOT NULL, email TEXT NOT NULL, "
                "status TEXT NOT NULL CHECK(status IN ('PENDENTE','ENVIADO','FALHA')), "
                "provedor_mensagem_id TEXT NOT NULL DEFAULT '', enviado_em TEXT, "
                "erro TEXT NOT NULL DEFAULT '')"
            )
            connection.execute(
                "CREATE INDEX IF NOT EXISTS "
                "relatorios_institucionais_envio_destinatarios_envio_idx "
                "ON relatorios_institucionais_envio_destinatarios(envio_id,id)"
            )
        self.store._institutional_distribution_schema_ready = True

    @staticmethod
    def _period_clause(tipo, ano, trimestre):
        if tipo not in REPORT_TYPES:
            raise ValueError("Tipo de relatório institucional inválido.")
        if tipo == "TRIMESTRAL" and trimestre not in (1, 2, 3, 4):
            raise ValueError("Relatório trimestral exige trimestre entre 1 e 4.")
        if tipo == "ANUAL" and trimestre is not None:
            raise ValueError("Relatório anual não aceita trimestre.")
        clause = "tipo=? AND ano=? AND " + (
            "trimestre=?" if trimestre is not None else "trimestre IS NULL"
        )
        params = (tipo, int(ano), *((int(trimestre),) if trimestre is not None else ()))
        return clause, params

    @staticmethod
    def _row(row):
        if not row:
            return None
        item = dict(row)
        for field in ("snapshot_dados", "conteudo_estruturado"):
            value = item.get(field)
            if isinstance(value, str):
                item[field] = json.loads(value)
        item["periodo_parcial"] = bool(item["periodo_parcial"])
        item["ativo"] = bool(item["ativo"])
        return item

    def list_for_period(self, tipo, ano, trimestre=None):
        clause, params = self._period_clause(tipo, ano, trimestre)
        with self.store.connection(read_only=True) as connection:
            return [
                self._row(row)
                for row in connection.execute(
                    "SELECT * FROM relatorios_institucionais WHERE "
                    + clause
                    + " AND ativo=1 ORDER BY versao DESC",
                    params,
                )
            ]

    def latest_for_period(self, tipo, ano, trimestre=None):
        rows = self.list_for_period(tipo, ano, trimestre)
        return rows[0] if rows else None

    def get(self, identifier):
        with self.store.connection(read_only=True) as connection:
            return self._row(
                connection.execute(
                    "SELECT * FROM relatorios_institucionais WHERE id=?", (identifier,)
                ).fetchone()
            )

    def create(
        self,
        *,
        tipo,
        ano,
        trimestre,
        data_inicio,
        data_fim,
        periodo_parcial,
        descricao_periodo,
        snapshot_dados,
        conteudo_estruturado,
        actor,
    ):
        """Create v1 only when no version exists; prevent accidental draft copies."""
        clause, params = self._period_clause(tipo, ano, trimestre)
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            existing = connection.execute(
                "SELECT id,status FROM relatorios_institucionais WHERE "
                + clause
                + " AND ativo=1 ORDER BY versao DESC",
                params,
            ).fetchall()
            if any(row["status"] in ("RASCUNHO", "EM_REVISAO") for row in existing):
                raise ValueError(
                    "Já existe um relatório em elaboração para este período."
                )
            if existing:
                raise ValueError(
                    "Finalize a versão existente antes de criar uma nova versão."
                )
            return self._insert(
                connection,
                tipo,
                ano,
                trimestre,
                data_inicio,
                data_fim,
                periodo_parcial,
                descricao_periodo,
                1,
                snapshot_dados,
                conteudo_estruturado,
                actor,
            )

    def create_new_version(
        self,
        *,
        tipo,
        ano,
        trimestre,
        data_inicio,
        data_fim,
        periodo_parcial,
        descricao_periodo,
        snapshot_dados,
        conteudo_estruturado,
        actor,
    ):
        clause, params = self._period_clause(tipo, ano, trimestre)
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            rows = connection.execute(
                "SELECT versao,status FROM relatorios_institucionais WHERE "
                + clause
                + " AND ativo=1 ORDER BY versao DESC",
                params,
            ).fetchall()
            if not rows or rows[0]["status"] not in ("FINALIZADO", "ENVIADO"):
                raise ValueError(
                    "Nova versão só pode ser criada a partir de relatório finalizado."
                )
            return self._insert(
                connection,
                tipo,
                ano,
                trimestre,
                data_inicio,
                data_fim,
                periodo_parcial,
                descricao_periodo,
                int(rows[0]["versao"]) + 1,
                snapshot_dados,
                conteudo_estruturado,
                actor,
            )

    def _insert(
        self,
        connection,
        tipo,
        ano,
        trimestre,
        data_inicio,
        data_fim,
        periodo_parcial,
        descricao_periodo,
        version,
        snapshot_dados,
        conteudo_estruturado,
        actor,
    ):
        stamp = now()
        inserted = connection.execute(
            "INSERT INTO relatorios_institucionais("
            "tipo,ano,trimestre,data_inicio,data_fim,periodo_parcial,descricao_periodo,"
            "status,versao,data_corte,snapshot_dados,conteudo_estruturado,criado_por,criado_em,"
            "atualizado_por,atualizado_em) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (
                tipo,
                int(ano),
                trimestre,
                data_inicio,
                data_fim,
                int(bool(periodo_parcial)),
                descricao_periodo or "",
                "RASCUNHO",
                version,
                stamp,
                json.dumps(snapshot_dados, ensure_ascii=False, sort_keys=True),
                json.dumps(conteudo_estruturado, ensure_ascii=False, sort_keys=True),
                actor or "",
                stamp,
                actor or "",
                stamp,
            ),
        )
        return self._row(
            connection.execute(
                "SELECT * FROM relatorios_institucionais WHERE id=?",
                (inserted.lastrowid,),
            ).fetchone()
        )

    def finalize(self, identifier, actor):
        """Freeze a draft/review version. Snapshot fields are never updated."""
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            row = connection.execute(
                "SELECT status FROM relatorios_institucionais WHERE id=? AND ativo=1",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Relatório institucional não encontrado.")
            if row["status"] not in ("RASCUNHO", "EM_REVISAO"):
                raise ValueError(
                    "Apenas relatórios em elaboração podem ser finalizados."
                )
            stamp = now()
            connection.execute(
                "UPDATE relatorios_institucionais SET status='FINALIZADO', finalizado_por=?, "
                "finalizado_em=?, atualizado_por=?, atualizado_em=? WHERE id=?",
                (actor or "", stamp, actor or "", stamp, identifier),
            )
        return self.get(identifier)

    def save_content(self, identifier, content, actor, *, status=None):
        """Persist textual content only while the immutable snapshot is editable."""
        if status is not None and status not in ("RASCUNHO", "EM_REVISAO"):
            raise ValueError("Status de edição inválido.")
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            row = connection.execute(
                "SELECT status FROM relatorios_institucionais WHERE id=? AND ativo=1",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Relatório institucional não encontrado.")
            if row["status"] not in ("RASCUNHO", "EM_REVISAO"):
                raise ValueError(
                    "Relatório finalizado é somente leitura; crie uma nova versão."
                )
            stamp = now()
            connection.execute(
                "UPDATE relatorios_institucionais SET conteudo_estruturado=?, status=?, "
                "atualizado_por=?, atualizado_em=? WHERE id=?",
                (
                    json.dumps(content, ensure_ascii=False, sort_keys=True),
                    status or row["status"],
                    actor or "",
                    stamp,
                    identifier,
                ),
            )
        return self.get(identifier)

    def pdf_artifact(self, identifier):
        """Return the official PDF of one version, or None when it was not stored."""
        with self.store.connection(read_only=True) as connection:
            row = connection.execute(
                "SELECT relatorio_id, nome_arquivo, conteudo, sha256, tamanho, "
                "gerado_por, gerado_em FROM relatorios_institucionais_pdf "
                "WHERE relatorio_id=?",
                (identifier,),
            ).fetchone()
        if not row:
            return None
        item = dict(row)
        item["conteudo"] = bytes(item["conteudo"])
        return item

    def save_pdf_artifact(
        self, identifier, *, nome_arquivo, conteudo, sha256, tamanho, actor
    ):
        """Replace the official PDF only after the new bytes already exist."""
        stamp = now()
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            existing = connection.execute(
                "SELECT status FROM relatorios_institucionais WHERE id=? AND ativo=1",
                (identifier,),
            ).fetchone()
            if not existing:
                raise ValueError("Relatório institucional não encontrado.")
            if existing["status"] not in ("FINALIZADO", "ENVIADO"):
                raise ValueError("Somente a versão finalizada possui PDF oficial.")
            connection.execute(
                "INSERT INTO relatorios_institucionais_pdf("
                "relatorio_id, nome_arquivo, conteudo, sha256, tamanho, gerado_por, "
                "gerado_em) VALUES(?,?,?,?,?,?,?) "
                "ON CONFLICT(relatorio_id) DO UPDATE SET "
                "nome_arquivo=excluded.nome_arquivo, conteudo=excluded.conteudo, "
                "sha256=excluded.sha256, tamanho=excluded.tamanho, "
                "gerado_por=excluded.gerado_por, gerado_em=excluded.gerado_em",
                (
                    identifier,
                    nome_arquivo,
                    conteudo,
                    sha256,
                    int(tamanho),
                    actor or "",
                    stamp,
                ),
            )
        return self.pdf_artifact(identifier)

    def pdf_metadata(self, identifier):
        """Official PDF identity without the bytes. Listing must stay light."""
        with self.store.connection(read_only=True) as connection:
            row = connection.execute(
                "SELECT relatorio_id, nome_arquivo, sha256, tamanho, gerado_por, "
                "gerado_em FROM relatorios_institucionais_pdf WHERE relatorio_id=?",
                (identifier,),
            ).fetchone()
        return dict(row) if row else None

    def distribution_by_key(self, idempotency_key):
        with self.store.connection(read_only=True) as connection:
            row = connection.execute(
                "SELECT id FROM relatorios_institucionais_envios "
                "WHERE chave_idempotencia=?",
                (idempotency_key,),
            ).fetchone()
        if not row:
            return None
        return self.distribution(row["id"])

    def distribution(self, identifier):
        with self.store.connection(read_only=True) as connection:
            return self._distribution_in(connection, identifier)

    def list_distributions(self, relatorio_id):
        """History for one version. Recipients are frozen; the PDF blob is not read."""
        with self.store.connection(read_only=True) as connection:
            rows = connection.execute(
                "SELECT id FROM relatorios_institucionais_envios "
                "WHERE relatorio_id=? ORDER BY id DESC",
                (relatorio_id,),
            ).fetchall()
            items = []
            for row in rows:
                item = self._distribution_in(connection, row["id"])
                if item:
                    items.append(item)
            return items

    def distribution_hashes(self, relatorio_id):
        with self.store.connection(read_only=True) as connection:
            rows = connection.execute(
                "SELECT DISTINCT pdf_sha256 FROM relatorios_institucionais_envios "
                "WHERE relatorio_id=?",
                (relatorio_id,),
            ).fetchall()
        return [row["pdf_sha256"] for row in rows if row["pdf_sha256"]]

    def distribution_summaries(self, relatorio_id):
        """Send history without recipient rows and without the PDF blob."""
        with self.store.connection(read_only=True) as connection:
            rows = connection.execute(
                "SELECT e.id, e.status_envio, e.pdf_sha256, e.pdf_nome, e.criado_em, "
                "e.enviado_em, e.origem_envio_id, e.erro_resumo, e.remetente, "
                "(SELECT COUNT(*) FROM relatorios_institucionais_envio_destinatarios d "
                "WHERE d.envio_id=e.id) AS destinatarios "
                "FROM relatorios_institucionais_envios e "
                "WHERE e.relatorio_id=? ORDER BY e.id DESC",
                (relatorio_id,),
            ).fetchall()
        return [dict(row) for row in rows]

    def list_latest_versions(self):
        """Latest version of each period, without PDF bytes."""
        with self.store.connection(read_only=True) as connection:
            rows = connection.execute(
                "SELECT r.id, r.tipo, r.ano, r.trimestre, r.versao, r.status, "
                "r.periodo_parcial, r.data_corte, r.atualizado_em, r.snapshot_dados, "
                "r.conteudo_estruturado, p.nome_arquivo AS pdf_nome, "
                "p.sha256 AS pdf_sha256, p.tamanho AS pdf_tamanho, "
                "(SELECT e.status_envio FROM relatorios_institucionais_envios e "
                "WHERE e.relatorio_id=r.id ORDER BY e.id DESC LIMIT 1) AS ultimo_envio "
                "FROM relatorios_institucionais r "
                "LEFT JOIN relatorios_institucionais_pdf p ON p.relatorio_id=r.id "
                "WHERE r.ativo=1 AND r.versao=("
                "SELECT MAX(r2.versao) FROM relatorios_institucionais r2 "
                "WHERE r2.tipo=r.tipo AND r2.ano=r.ano "
                "AND COALESCE(r2.trimestre, 0)=COALESCE(r.trimestre, 0) AND r2.ativo=1) "
                "ORDER BY r.ano DESC, r.tipo, COALESCE(r.trimestre, 0), r.versao"
            ).fetchall()
        items = []
        for row in rows:
            item = dict(row)
            for field in ("snapshot_dados", "conteudo_estruturado"):
                value = item.get(field)
                if isinstance(value, str):
                    item[field] = json.loads(value)
            item["periodo_parcial"] = bool(item.get("periodo_parcial"))
            items.append(item)
        return items

    def begin_distribution(self, header, recipients):
        """Create the operation once. The same confirmation key returns the original."""
        stamp = now()
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            existing = connection.execute(
                "SELECT id FROM relatorios_institucionais_envios "
                "WHERE chave_idempotencia=?",
                (header["chave_idempotencia"],),
            ).fetchone()
            if existing:
                return self._distribution_in(connection, existing["id"])
            inserted = connection.execute(
                "INSERT INTO relatorios_institucionais_envios("
                "relatorio_id, origem_envio_id, tipo, ano, trimestre, versao, "
                "status_envio, remetente, assunto, corpo, pdf_nome, pdf_sha256, "
                "pdf_tamanho, criado_por, criado_em, chave_idempotencia) "
                "VALUES(?,?,?,?,?,?, 'PREPARADO',?,?,?,?,?,?,?,?,?)",
                (
                    header["relatorio_id"],
                    header.get("origem_envio_id"),
                    header["tipo"],
                    int(header["ano"]),
                    header.get("trimestre"),
                    int(header["versao"]),
                    header["remetente"],
                    header["assunto"],
                    header["corpo"],
                    header["pdf_nome"],
                    header["pdf_sha256"],
                    int(header["pdf_tamanho"]),
                    header.get("criado_por") or "",
                    stamp,
                    header["chave_idempotencia"],
                ),
            )
            envio_id = inserted.lastrowid
            for person in recipients:
                connection.execute(
                    "INSERT INTO relatorios_institucionais_envio_destinatarios("
                    "envio_id, procurador_id, procurador, email, status) "
                    "VALUES(?,?,?,?, 'PENDENTE')",
                    (
                        envio_id,
                        person.get("procurador_id"),
                        person["procurador"],
                        person["email"],
                    ),
                )
            return self._distribution_in(connection, envio_id)

    def claim_distribution(self, identifier):
        """PREPARADO becomes ENVIANDO for exactly one caller."""
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            updated = connection.execute(
                "UPDATE relatorios_institucionais_envios SET status_envio='ENVIANDO' "
                "WHERE id=? AND status_envio='PREPARADO'",
                (identifier,),
            )
            if getattr(updated, "rowcount", 0) != 1:
                return None
            return self._distribution_in(connection, identifier)

    def record_recipient(self, identifier, *, status, provider_id="", error=""):
        stamp = now() if status == "ENVIADO" else None
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            connection.execute(
                "UPDATE relatorios_institucionais_envio_destinatarios "
                "SET status=?, provedor_mensagem_id=?, enviado_em=?, erro=? "
                "WHERE id=?",
                (status, provider_id or "", stamp, error or "", identifier),
            )

    def close_distribution(self, identifier, *, status, actor, error=""):
        if status not in ("ENVIANDO", "ENVIADO", "PARCIAL", "FALHA"):
            raise ValueError("Status de distribuição inválido.")
        stamp = now() if status in ("ENVIADO", "PARCIAL", "FALHA") else None
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            connection.execute(
                "UPDATE relatorios_institucionais_envios SET status_envio=?, "
                "enviado_por=?, enviado_em=?, erro_resumo=? WHERE id=?",
                (status, actor or "", stamp, error or "", identifier),
            )
        return self.distribution(identifier)

    def mark_distributed(self, identifier, actor):
        """FINALIZADO becomes ENVIADO. Finalization metadata stays in place."""
        stamp = now()
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            current = connection.execute(
                "SELECT status FROM relatorios_institucionais WHERE id=? AND ativo=1",
                (identifier,),
            ).fetchone()
            if not current:
                raise ValueError("Relatório institucional não encontrado.")
            if current["status"] == "ENVIADO":
                pass
            elif current["status"] != "FINALIZADO":
                raise ValueError(
                    "Somente relatório finalizado pode ser marcado como enviado."
                )
            else:
                connection.execute(
                    "UPDATE relatorios_institucionais SET status='ENVIADO', "
                    "atualizado_por=?, atualizado_em=? "
                    "WHERE id=? AND status='FINALIZADO'",
                    (actor or "", stamp, identifier),
                )
        return self.get(identifier)

    def _distribution_in(self, connection, identifier):
        row = connection.execute(
            "SELECT id, relatorio_id, origem_envio_id, tipo, ano, trimestre, versao, "
            "status_envio, remetente, assunto, corpo, pdf_nome, pdf_sha256, "
            "pdf_tamanho, criado_por, criado_em, enviado_por, enviado_em, "
            "provedor_mensagem_id, erro_resumo, chave_idempotencia "
            "FROM relatorios_institucionais_envios WHERE id=?",
            (identifier,),
        ).fetchone()
        if not row:
            return None
        item = dict(row)
        item["destinatarios"] = [
            dict(person)
            for person in connection.execute(
                "SELECT id, envio_id, procurador_id, procurador, email, status, "
                "provedor_mensagem_id, enviado_em, erro "
                "FROM relatorios_institucionais_envio_destinatarios "
                "WHERE envio_id=? ORDER BY id",
                (identifier,),
            ).fetchall()
        ]
        return item
