"""Persistent, versioned institutional reports independent from Tramita rows."""

import json
from threading import RLock

from database.store import now, unwrap_store


REPORT_TYPES = ("TRIMESTRAL", "ANUAL")
REPORT_STATUSES = ("RASCUNHO", "EM_REVISAO", "FINALIZADO", "ENVIADO")
_SCHEMA_LOCK = RLock()


class InstitutionalReportsStore:
    """Store immutable report snapshots; indicator calculations remain elsewhere."""

    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        with _SCHEMA_LOCK:
            if getattr(self.store, "_institutional_reports_schema_ready", False):
                return
            identity = (
                "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                if self.store.backend == "postgresql"
                else "INTEGER PRIMARY KEY"
            )
            snapshot_type = "JSONB" if self.store.backend == "postgresql" else "TEXT"
            with self.store.connection() as connection:
                connection.execute("BEGIN IMMEDIATE")
                connection.execute(
                    f"CREATE TABLE IF NOT EXISTS relatorios_institucionais ("
                    f"id {identity}, tipo TEXT NOT NULL CHECK(tipo IN "
                    "('TRIMESTRAL','ANUAL')), ano INTEGER NOT NULL, trimestre INTEGER, "
                    "data_inicio TEXT NOT NULL, data_fim TEXT NOT NULL, "
                    "periodo_parcial INTEGER NOT NULL DEFAULT 0 CHECK(periodo_parcial IN (0,1)), "
                    "descricao_periodo TEXT NOT NULL DEFAULT '', "
                    "status TEXT NOT NULL DEFAULT 'RASCUNHO' CHECK(status IN "
                    "('RASCUNHO','EM_REVISAO','FINALIZADO','ENVIADO')), "
                    "versao INTEGER NOT NULL CHECK(versao>=1), data_corte TEXT NOT NULL, "
                    f"snapshot_dados {snapshot_type} NOT NULL, "
                    f"conteudo_estruturado {snapshot_type} NOT NULL, "
                    "criado_por TEXT NOT NULL DEFAULT '', criado_em TEXT NOT NULL, "
                    "atualizado_por TEXT, atualizado_em TEXT, finalizado_por TEXT, "
                    "finalizado_em TEXT, ativo INTEGER NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)), "
                    "CHECK((tipo='TRIMESTRAL' AND trimestre BETWEEN 1 AND 4) "
                    "OR (tipo='ANUAL' AND trimestre IS NULL)))"
                )
                connection.execute(
                    "CREATE UNIQUE INDEX IF NOT EXISTS relatorios_institucionais_periodo_versao_uq "
                    "ON relatorios_institucionais(tipo,ano,COALESCE(trimestre,0),versao)"
                )
                connection.execute(
                    "CREATE INDEX IF NOT EXISTS relatorios_institucionais_consulta_idx "
                    "ON relatorios_institucionais(tipo,ano,trimestre,status,versao)"
                )
            self.store._institutional_reports_schema_ready = True

    @staticmethod
    def _period_clause(tipo, ano, trimestre):
        if tipo not in REPORT_TYPES:
            raise ValueError("Tipo de relatório institucional inválido.")
        if tipo == "TRIMESTRAL" and trimestre not in (1, 2, 3, 4):
            raise ValueError("Relatório trimestral exige trimestre entre 1 e 4.")
        if tipo == "ANUAL" and trimestre is not None:
            raise ValueError("Relatório anual não aceita trimestre.")
        clause = "tipo=? AND ano=? AND " + (
            "trimestre=?" if trimestre is not None else "trimestre IS NULL"
        )
        params = (tipo, int(ano), *((int(trimestre),) if trimestre is not None else ()))
        return clause, params

    @staticmethod
    def _row(row):
        if not row:
            return None
        item = dict(row)
        for field in ("snapshot_dados", "conteudo_estruturado"):
            value = item.get(field)
            if isinstance(value, str):
                item[field] = json.loads(value)
        item["periodo_parcial"] = bool(item["periodo_parcial"])
        item["ativo"] = bool(item["ativo"])
        return item

    def list_for_period(self, tipo, ano, trimestre=None):
        clause, params = self._period_clause(tipo, ano, trimestre)
        with self.store.connection(read_only=True) as connection:
            return [
                self._row(row)
                for row in connection.execute(
                    "SELECT * FROM relatorios_institucionais WHERE "
                    + clause
                    + " AND ativo=1 ORDER BY versao DESC",
                    params,
                )
            ]

    def latest_for_period(self, tipo, ano, trimestre=None):
        rows = self.list_for_period(tipo, ano, trimestre)
        return rows[0] if rows else None

    def get(self, identifier):
        with self.store.connection(read_only=True) as connection:
            return self._row(
                connection.execute(
                    "SELECT * FROM relatorios_institucionais WHERE id=?", (identifier,)
                ).fetchone()
            )

    def create(
        self,
        *,
        tipo,
        ano,
        trimestre,
        data_inicio,
        data_fim,
        periodo_parcial,
        descricao_periodo,
        snapshot_dados,
        conteudo_estruturado,
        actor,
    ):
        """Create v1 only when no version exists; prevent accidental draft copies."""
        clause, params = self._period_clause(tipo, ano, trimestre)
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            existing = connection.execute(
                "SELECT id,status FROM relatorios_institucionais WHERE "
                + clause
                + " AND ativo=1 ORDER BY versao DESC",
                params,
            ).fetchall()
            if any(row["status"] in ("RASCUNHO", "EM_REVISAO") for row in existing):
                raise ValueError(
                    "Já existe um relatório em elaboração para este período."
                )
            if existing:
                raise ValueError(
                    "Finalize a versão existente antes de criar uma nova versão."
                )
            return self._insert(
                connection,
                tipo,
                ano,
                trimestre,
                data_inicio,
                data_fim,
                periodo_parcial,
                descricao_periodo,
                1,
                snapshot_dados,
                conteudo_estruturado,
                actor,
            )

    def create_new_version(
        self,
        *,
        tipo,
        ano,
        trimestre,
        data_inicio,
        data_fim,
        periodo_parcial,
        descricao_periodo,
        snapshot_dados,
        conteudo_estruturado,
        actor,
    ):
        clause, params = self._period_clause(tipo, ano, trimestre)
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            rows = connection.execute(
                "SELECT versao,status FROM relatorios_institucionais WHERE "
                + clause
                + " AND ativo=1 ORDER BY versao DESC",
                params,
            ).fetchall()
            if not rows or rows[0]["status"] not in ("FINALIZADO", "ENVIADO"):
                raise ValueError(
                    "Nova versão só pode ser criada a partir de relatório finalizado."
                )
            return self._insert(
                connection,
                tipo,
                ano,
                trimestre,
                data_inicio,
                data_fim,
                periodo_parcial,
                descricao_periodo,
                int(rows[0]["versao"]) + 1,
                snapshot_dados,
                conteudo_estruturado,
                actor,
            )

    def _insert(
        self,
        connection,
        tipo,
        ano,
        trimestre,
        data_inicio,
        data_fim,
        periodo_parcial,
        descricao_periodo,
        version,
        snapshot_dados,
        conteudo_estruturado,
        actor,
    ):
        stamp = now()
        inserted = connection.execute(
            "INSERT INTO relatorios_institucionais("
            "tipo,ano,trimestre,data_inicio,data_fim,periodo_parcial,descricao_periodo,"
            "status,versao,data_corte,snapshot_dados,conteudo_estruturado,criado_por,criado_em,"
            "atualizado_por,atualizado_em) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (
                tipo,
                int(ano),
                trimestre,
                data_inicio,
                data_fim,
                int(bool(periodo_parcial)),
                descricao_periodo or "",
                "RASCUNHO",
                version,
                stamp,
                json.dumps(snapshot_dados, ensure_ascii=False, sort_keys=True),
                json.dumps(conteudo_estruturado, ensure_ascii=False, sort_keys=True),
                actor or "",
                stamp,
                actor or "",
                stamp,
            ),
        )
        return self._row(
            connection.execute(
                "SELECT * FROM relatorios_institucionais WHERE id=?",
                (inserted.lastrowid,),
            ).fetchone()
        )

    def finalize(self, identifier, actor):
        """Freeze a draft/review version. Snapshot fields are never updated."""
        with self.store.connection() as connection:
            connection.execute("BEGIN IMMEDIATE")
            row = connection.execute(
                "SELECT status FROM relatorios_institucionais WHERE id=? AND ativo=1",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Relatório institucional não encontrado.")
            if row["status"] not in ("RASCUNHO", "EM_REVISAO"):
                raise ValueError(
                    "Apenas relatórios em elaboração podem ser finalizados."
                )
            stamp = now()
            connection.execute(
                "UPDATE relatorios_institucionais SET status='FINALIZADO', finalizado_por=?, "
                "finalizado_em=?, atualizado_por=?, atualizado_em=? WHERE id=?",
                (actor or "", stamp, actor or "", stamp, identifier),
            )
        return self.get(identifier)
