"""Notas internas e encaminhamentos associados por referência a registros existentes."""

from datetime import date

from database.access import AccessStore
from database.store import now, schema_key_of, unwrap_store
from services.oficios import GABINETES

MARKER = "colaboracao_interna_schema_v1"
_READY = set()

ORIGINS = {
    "oficio_enviado": ("oficios", "oficios", "id", "ENVIADO"),
    "oficio_recebido": ("oficios", "oficios", "id", "RECEBIDO"),
    "memorando": ("memorandos", "memorandos", "id", None),
    "representacao": ("representacoes", "representacoes", "id", None),
    "ouvidoria": ("ouvidoria", "ouvidoria_manifestacoes", "id", None),
}


class InternalCollaborationStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        with self.store.connection(read_only=True) as c:
            marker = c.execute(
                "SELECT 1 FROM configuracoes WHERE chave=?", (MARKER,)
            ).fetchone()
            if self.store.backend == "postgresql":
                tables = {
                    row[0]
                    for row in c.execute(
                        "SELECT table_name FROM information_schema.tables "
                        "WHERE table_schema=current_schema() AND table_name IN "
                        "('notas_internas','encaminhamentos_internos')"
                    )
                }
            else:
                tables = {
                    row[0]
                    for row in c.execute(
                        "SELECT name FROM sqlite_master WHERE type='table' AND name IN "
                        "('notas_internas','encaminhamentos_internos')"
                    )
                }
        if marker and tables == {"notas_internas", "encaminhamentos_internos"}:
            _READY.add(key)
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        user_fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS notas_internas ("
                f"id {identity},origem_modulo TEXT NOT NULL,origem_id TEXT NOT NULL,"
                f"autor_id {user_fk} REFERENCES usuarios_acesso(id) ON DELETE SET NULL,"
                "autor_nome TEXT NOT NULL,texto TEXT NOT NULL,criado_em TEXT NOT NULL)"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS encaminhamentos_internos ("
                f"id {identity},origem_modulo TEXT NOT NULL,origem_id TEXT NOT NULL,"
                f"remetente_id {user_fk} REFERENCES usuarios_acesso(id) ON DELETE SET NULL,"
                "remetente_nome TEXT NOT NULL,"
                f"destinatario_id {user_fk} REFERENCES usuarios_acesso(id) ON DELETE SET NULL,"
                "destinatario_nome TEXT NOT NULL DEFAULT '',destinatario_gabinete TEXT,"
                "providencia TEXT NOT NULL,prazo TEXT,status TEXT NOT NULL DEFAULT 'PENDENTE' "
                "CHECK(status IN ('PENDENTE','CIENTE','CONCLUIDO')),criado_em TEXT NOT NULL,"
                f"ciente_em TEXT,ciente_por_id {user_fk} REFERENCES usuarios_acesso(id) ON DELETE SET NULL,"
                "ciente_por_nome TEXT NOT NULL DEFAULT '',"
                f"concluido_em TEXT,concluido_por_id {user_fk} REFERENCES usuarios_acesso(id) ON DELETE SET NULL,"
                "concluido_por_nome TEXT NOT NULL DEFAULT '')"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS notas_internas_origem_idx "
                "ON notas_internas(origem_modulo,origem_id,criado_em,id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS encaminhamentos_origem_idx "
                "ON encaminhamentos_internos(origem_modulo,origem_id,criado_em,id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS encaminhamentos_dest_status_idx "
                "ON encaminhamentos_internos(destinatario_id,status)"
            )
            c.execute(
                "INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def _origin(self, c, module, identifier):
        if module not in ORIGINS:
            raise ValueError("Módulo de origem inválido.")
        permission, table, key, direction = ORIGINS[module]
        identifier = str(identifier)
        if table == "oficios":
            row = c.execute(
                "SELECT id,direcao,serie FROM oficios WHERE id=?", (identifier,)
            ).fetchone()
            if not row or row["direcao"] != direction:
                raise ValueError("Registro de origem não encontrado.")
        else:
            row = c.execute(
                f"SELECT {key} FROM {table} WHERE {key}=?", (identifier,)
            ).fetchone()
            if not row:
                raise ValueError("Registro de origem não encontrado.")
        return permission, row

    def _principal(self, identifier):
        try:
            record = AccessStore(self.store).get(int(identifier))
        except (TypeError, ValueError):
            raise ValueError("Usuário não autorizado.") from None
        if not record["ativo"]:
            raise ValueError("Usuário não autorizado.")
        from services.access import principal_from_record

        return principal_from_record(record)

    def _origin_offices(self, c, module, origin_row):
        if module == "oficio_enviado":
            return {origin_row["serie"]} if origin_row["serie"] else set()
        if module != "oficio_recebido":
            return set()
        return {
            row[0]
            for row in c.execute(
                "SELECT s.sigla FROM oficio_destinatarios d "
                "JOIN oficio_series s ON s.membro_id=d.membro_id WHERE d.oficio_id=?",
                (origin_row["id"],),
            )
        }

    def _can_access(self, c, principal, module, origin_row, origin_offices=None):
        from services.access import has_permission

        permission = ORIGINS[module][0]
        if not has_permission(principal, permission):
            return False
        if not module.startswith("oficio_") or principal.administrator:
            return True
        offices = (
            self._origin_offices(c, module, origin_row)
            if origin_offices is None
            else origin_offices
        )
        return bool(offices.intersection(principal.gabinetes))

    def _authorized_origin(self, c, module, identifier, actor_id):
        permission, row = self._origin(c, module, identifier)
        principal = self._principal(actor_id)
        if not self._can_access(c, principal, module, row):
            raise ValueError("Acesso não autorizado a este registro.")
        return principal, permission, row

    def add_note(self, module, identifier, actor_id, text):
        text = (text or "").strip()
        if not text or len(text) > 4000:
            raise ValueError("Informe uma nota com até 4.000 caracteres.")
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            actor, _, _ = self._authorized_origin(c, module, identifier, actor_id)
            inserted = c.execute(
                "INSERT INTO notas_internas(origem_modulo,origem_id,autor_id,autor_nome,texto,criado_em) "
                "VALUES(?,?,?,?,?,?)",
                (module, str(identifier), actor.id, actor.nome, text, now()),
            )
            return inserted.lastrowid

    def list_notes(self, module, identifier, actor_id):
        with self.store.connection(read_only=True) as c:
            self._authorized_origin(c, module, identifier, actor_id)
            return [
                dict(row)
                for row in c.execute(
                    "SELECT id,autor_id,autor_nome,texto,criado_em FROM notas_internas "
                    "WHERE origem_modulo=? AND origem_id=? ORDER BY criado_em,id",
                    (module, str(identifier)),
                )
            ]

    def eligible_users(self, module, identifier, actor_id):
        with self.store.connection(read_only=True) as c:
            self._authorized_origin(c, module, identifier, actor_id)
            _, origin_row = self._origin(c, module, identifier)
            origin_offices = self._origin_offices(c, module, origin_row)
            result = []
            for user in AccessStore(self.store).list_users():
                if not user["ativo"]:
                    continue
                from services.access import principal_from_record

                candidate = principal_from_record(user)
                if self._can_access(
                    c, candidate, module, origin_row, origin_offices=origin_offices
                ):
                    result.append(
                        {
                            "id": user["id"],
                            "nome": user["nome"],
                            "email": user["email"],
                        }
                    )
            return result

    def create_forwarding(
        self,
        module,
        identifier,
        actor_id,
        message,
        *,
        recipient_id=None,
        cabinet=None,
        due=None,
    ):
        message = (message or "").strip()
        cabinet = (cabinet or "").strip() or None
        if not message or len(message) > 2000:
            raise ValueError("Informe a providência com até 2.000 caracteres.")
        if not recipient_id and not cabinet:
            raise ValueError("Selecione um usuário e/ou gabinete destinatário.")
        if cabinet and cabinet not in GABINETES:
            raise ValueError("Gabinete destinatário inválido.")
        if due:
            date.fromisoformat(due)
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            actor, _, origin_row = self._authorized_origin(
                c, module, identifier, actor_id
            )
            recipient = None
            if recipient_id:
                recipient = self._principal(recipient_id)
                if not self._can_access(c, recipient, module, origin_row):
                    raise ValueError("O destinatário não possui acesso a este registro.")
            inserted = c.execute(
                "INSERT INTO encaminhamentos_internos("
                "origem_modulo,origem_id,remetente_id,remetente_nome,destinatario_id,"
                "destinatario_nome,destinatario_gabinete,providencia,prazo,status,criado_em) "
                "VALUES(?,?,?,?,?,?,?,?,?,'PENDENTE',?)",
                (
                    module,
                    str(identifier),
                    actor.id,
                    actor.nome,
                    recipient.id if recipient else None,
                    recipient.nome if recipient else "",
                    cabinet,
                    message,
                    due,
                    now(),
                ),
            )
            return inserted.lastrowid

    def list_forwardings(self, module, identifier, actor_id):
        with self.store.connection(read_only=True) as c:
            actor, _, _ = self._authorized_origin(c, module, identifier, actor_id)
            return [
                {**dict(row), "pode_agir": self._can_receive(actor, row)}
                for row in c.execute(
                    "SELECT * FROM encaminhamentos_internos WHERE origem_modulo=? "
                    "AND origem_id=? ORDER BY criado_em DESC,id DESC",
                    (module, str(identifier)),
                )
            ]

    def _can_receive(self, principal, row):
        if row["remetente_id"] == principal.id:
            return False
        return bool(
            principal.administrator
            or (row["destinatario_id"] and row["destinatario_id"] == principal.id)
            or (
                row["destinatario_gabinete"]
                and row["destinatario_gabinete"] in principal.gabinetes
            )
        )

    def mark_acknowledged(self, forwarding_id, actor_id):
        return self._advance(forwarding_id, actor_id, "CIENTE")

    def conclude(self, forwarding_id, actor_id):
        return self._advance(forwarding_id, actor_id, "CONCLUIDO")

    def _advance(self, forwarding_id, actor_id, target):
        if target not in ("CIENTE", "CONCLUIDO"):
            raise ValueError("Estado inválido.")
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            row = c.execute(
                "SELECT * FROM encaminhamentos_internos WHERE id=?", (forwarding_id,)
            ).fetchone()
            if not row:
                raise ValueError("Encaminhamento não encontrado.")
            actor, _, _ = self._authorized_origin(
                c, row["origem_modulo"], row["origem_id"], actor_id
            )
            if not self._can_receive(actor, row):
                raise ValueError("Somente o destinatário pode registrar esta ação.")
            stamp = now()
            if target == "CIENTE":
                if row["status"] != "PENDENTE":
                    raise ValueError("Este encaminhamento já recebeu ciência.")
                c.execute(
                    "UPDATE encaminhamentos_internos SET status='CIENTE',ciente_em=?,"
                    "ciente_por_id=?,ciente_por_nome=? WHERE id=?",
                    (stamp, actor.id, actor.nome, forwarding_id),
                )
            else:
                if row["status"] == "CONCLUIDO":
                    raise ValueError("Este encaminhamento já foi concluído.")
                c.execute(
                    "UPDATE encaminhamentos_internos SET status='CONCLUIDO',"
                    "ciente_em=COALESCE(ciente_em,?),ciente_por_id=COALESCE(ciente_por_id,?),"
                    "ciente_por_nome=CASE WHEN ciente_por_nome='' THEN ? ELSE ciente_por_nome END,"
                    "concluido_em=?,concluido_por_id=?,concluido_por_nome=? WHERE id=?",
                    (
                        stamp,
                        actor.id,
                        actor.nome,
                        stamp,
                        actor.id,
                        actor.nome,
                        forwarding_id,
                    ),
                )
            return target

    @staticmethod
    def delete_origin(connection, module, identifier):
        connection.execute(
            "DELETE FROM notas_internas WHERE origem_modulo=? AND origem_id=?",
            (module, str(identifier)),
        )
        connection.execute(
            "DELETE FROM encaminhamentos_internos WHERE origem_modulo=? AND origem_id=?",
            (module, str(identifier)),
        )


def ensure_schema(store):
    InternalCollaborationStore(store)
