"""Trusted DDL for the retired per-user alert presentation state.

The live Alerts module no longer creates or reads this table, but older deployed
schemas can retain it. Backup/restore preserves it when present without making
it mandatory for current installations.
"""

from database.store import unwrap_store


def ensure_backup_schema(store):
    store = unwrap_store(store)
    identity = (
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if store.backend == "postgresql"
        else "INTEGER PRIMARY KEY"
    )
    user_type = "BIGINT" if store.backend == "postgresql" else "INTEGER"
    with store.connection() as connection:
        connection.execute(
            f"CREATE TABLE IF NOT EXISTS alertas_atencao (id {identity},"
            f"usuario_id {user_type} NOT NULL REFERENCES usuarios_acesso(id) ON DELETE CASCADE,"
            "chave_alerta TEXT NOT NULL, lido_em TEXT, adiado_ate TEXT, "
            "criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL, "
            "UNIQUE(usuario_id,chave_alerta))"
        )
        connection.execute(
            "CREATE INDEX IF NOT EXISTS alertas_atencao_usuario_adiado_idx "
            "ON alertas_atencao(usuario_id,adiado_ate)"
        )