"""Extensible persistence for memoranda. All final-document facts are snapshots."""
from datetime import date
import hashlib
import json
import uuid

from database.store import encode, now, schema_key_of, unwrap_store
from services.memorandos import STATUS_FINALIZADO, STATUS_RASCUNHO, TIPO_SUBSTITUICAO, fingerprint, normalize, normalized_registration, substitution_status, validate

MARKER = "memorandos_schema_v1"
_READY = set()


class MemorandosStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY: return
        with self.store.connection(read_only=True) as c:
            if c.execute("SELECT 1 FROM configuracoes WHERE chave=?", (MARKER,)).fetchone():
                _READY.add(key); return
        binary = "BYTEA" if self.store.backend == "postgresql" else "BLOB"
        identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.store.backend == "postgresql" else "INTEGER PRIMARY KEY"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            statements = [
                f"CREATE TABLE IF NOT EXISTS servidores (id {identity}, nome TEXT NOT NULL, nome_normalizado TEXT NOT NULL, matricula_original TEXT NOT NULL DEFAULT '', matricula_normalizada TEXT, cargo TEXT NOT NULL DEFAULT '', setor TEXT NOT NULL DEFAULT '', genero TEXT, ativo INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL)",
                f"CREATE TABLE IF NOT EXISTS servidores_importacoes (id {identity}, usuario_email TEXT NOT NULL, arquivo_nome TEXT NOT NULL, arquivo_hash TEXT NOT NULL, processado_em TEXT NOT NULL, total_processado INTEGER NOT NULL, incluidos INTEGER NOT NULL, atualizados INTEGER NOT NULL, inconsistentes INTEGER NOT NULL)",
                "CREATE UNIQUE INDEX IF NOT EXISTS servidores_matricula_unica ON servidores(matricula_normalizada) WHERE matricula_normalizada IS NOT NULL",
                "CREATE INDEX IF NOT EXISTS servidores_pesquisa_idx ON servidores(nome_normalizado,matricula_normalizada)",
                "CREATE TABLE IF NOT EXISTS memorandos (id TEXT PRIMARY KEY, tipo TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('RASCUNHO','FINALIZADO','CANCELADO')), criado_por TEXT NOT NULL, criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL, finalizado_em TEXT, numero_oficial TEXT NOT NULL DEFAULT '', payload TEXT NOT NULL)",
                "CREATE TABLE IF NOT EXISTS memorandos_substituicao (memorando_id TEXT PRIMARY KEY REFERENCES memorandos(id) ON DELETE CASCADE, data_inicio TEXT NOT NULL, data_fim TEXT NOT NULL, gabinete_procurador_id INTEGER REFERENCES procuradores(id), gabinete_snapshot TEXT NOT NULL, natureza_funcao TEXT NOT NULL, motivo TEXT NOT NULL, motivo_texto TEXT NOT NULL, signatario_id INTEGER REFERENCES procuradores(id), signatario_nome TEXT NOT NULL, signatario_cargo TEXT NOT NULL)",
                f"CREATE TABLE IF NOT EXISTS memorandos_substituicao_etapas (id {identity}, memorando_id TEXT NOT NULL REFERENCES memorandos(id) ON DELETE CASCADE, ordem INTEGER NOT NULL, substituido_servidor_id INTEGER REFERENCES servidores(id), substituido_snapshot TEXT NOT NULL, substituto_servidor_id INTEGER REFERENCES servidores(id), substituto_snapshot TEXT NOT NULL, UNIQUE(memorando_id,ordem))",
                f"CREATE TABLE IF NOT EXISTS memorandos_arquivos (id TEXT PRIMARY KEY, memorando_id TEXT NOT NULL REFERENCES memorandos(id) ON DELETE CASCADE, nome TEXT NOT NULL, tipo TEXT NOT NULL, tamanho INTEGER NOT NULL, sha256 TEXT NOT NULL, criado_em TEXT NOT NULL, conteudo {binary} NOT NULL)",
                "CREATE INDEX IF NOT EXISTS memorandos_lista_idx ON memorandos(status,atualizado_em DESC)",
                "CREATE INDEX IF NOT EXISTS memorandos_etapas_idx ON memorandos_substituicao_etapas(memorando_id,ordem)",
            ]
            for statement in statements: c.execute(statement)
            c.execute("INSERT INTO configuracoes VALUES(?,?) ON CONFLICT DO NOTHING", (MARKER,"1"))
        _READY.add(key)

    def servers(self, search="", limit=500):
        term = "%" + normalize(search) + "%"
        with self.store.connection(read_only=True) as c:
            return [dict(r) for r in c.execute("SELECT id,nome,matricula_original,cargo,setor,genero,ativo FROM servidores WHERE ativo=1 AND (nome_normalizado LIKE ? OR COALESCE(matricula_normalizada,'') LIKE ?) ORDER BY nome LIMIT ?", (term,term,limit))]

    def all_servers(self, include_inactive=False):
        where = "" if include_inactive else " WHERE ativo=1"
        with self.store.connection(read_only=True) as c:
            return [dict(r) for r in c.execute("SELECT id,nome,matricula_original,matricula_normalizada,cargo,setor,genero,ativo FROM servidores" + where + " ORDER BY nome")]

    def update_server(self, identifier, values, *, actor_email, administrator=False):
        if not administrator:
            raise ValueError("Acesso não autorizado à base de servidores.")
        name = (values.get("nome") or "").strip()
        gender = values.get("genero") or None
        if not name or gender not in (None, "Masculino", "Feminino"):
            raise ValueError("Nome ou gênero inválido.")
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            found = c.execute("SELECT id FROM servidores WHERE id=?", (identifier,)).fetchone()
            if not found: raise ValueError("Servidor não encontrado.")
            c.execute("UPDATE servidores SET nome=?,nome_normalizado=?,cargo=?,setor=?,genero=?,ativo=?,atualizado_em=? WHERE id=?", (name,normalize(name),(values.get("cargo") or "").strip(),(values.get("setor") or "").strip(),gender,1 if values.get("ativo",True) else 0,now(),identifier))
            self.store.event(c,"memorandos_editar_servidor",{"id":identifier,"usuario":actor_email})

    def preview_import(self, rows):
        report = {"total": len(rows), "novos": 0, "atualizados": 0, "sem_matricula": [], "matriculas_zero": [], "duplicidades": [], "inconsistentes": []}
        seen = set()
        with self.store.connection(read_only=True) as c:
            existing = {r[0] for r in c.execute("SELECT matricula_normalizada FROM servidores WHERE matricula_normalizada IS NOT NULL")}
        for number, raw in enumerate(rows, 2):
            name = str(raw.get("nome") or "").strip(); registration = normalized_registration(raw.get("matricula")); original = str(raw.get("matricula") or "").strip()
            if not name: report["inconsistentes"].append(number); continue
            if not original: report["sem_matricula"].append(number); continue
            if not registration: report["matriculas_zero"].append(number); continue
            if registration in seen: report["duplicidades"].append(number); continue
            seen.add(registration); report["atualizados" if registration in existing else "novos"] += 1
        return report

    def import_servers(self, rows, *, actor_email, filename, content_hash, administrator=False):
        if not administrator:
            raise ValueError("Acesso não autorizado à base de servidores.")
        report = self.preview_import(rows)
        stamp = now(); included = updated = inconsistent = 0
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            for raw in rows:
                name = str(raw.get("nome") or "").strip(); original = str(raw.get("matricula") or "").strip(); registration = normalized_registration(original)
                if not name or not registration: inconsistent += 1; continue
                values = (name, normalize(name), original, registration, str(raw.get("cargo") or "").strip(), str(raw.get("setor") or "").strip(), stamp)
                exists = c.execute("SELECT id FROM servidores WHERE matricula_normalizada=?", (registration,)).fetchone()
                if exists:
                    c.execute("UPDATE servidores SET nome=?,nome_normalizado=?,matricula_original=?,cargo=?,setor=?,atualizado_em=? WHERE id=?", (*values[:3],values[4],values[5],stamp,exists[0])); updated += 1
                else:
                    c.execute("INSERT INTO servidores(nome,nome_normalizado,matricula_original,matricula_normalizada,cargo,setor,criado_em,atualizado_em) VALUES(?,?,?,?,?,?,?,?)", (*values[:6],stamp,stamp)); included += 1
            c.execute("INSERT INTO servidores_importacoes(usuario_email,arquivo_nome,arquivo_hash,processado_em,total_processado,incluidos,atualizados,inconsistentes) VALUES(?,?,?,?,?,?,?,?)", (actor_email,filename,content_hash,stamp,len(rows),included,updated,inconsistent))
            self.store.event(c,"memorandos_importar_servidores", {"usuario": actor_email,"total":len(rows),"incluidos":included,"atualizados":updated,"inconsistentes":inconsistent})
        return {**report,"incluidos":included,"atualizados":updated,"inconsistentes":inconsistent}

    def save_draft(self, record, *, actor_email, identifier=None):
        validate(record); identifier = identifier or uuid.uuid4().hex; stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE"); old = c.execute("SELECT status,criado_em FROM memorandos WHERE id=?",(identifier,)).fetchone()
            if old and old["status"] != STATUS_RASCUNHO: raise ValueError("Memorando finalizado não pode ser alterado.")
            c.execute("INSERT INTO memorandos VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,atualizado_em=excluded.atualizado_em", (identifier,TIPO_SUBSTITUICAO,STATUS_RASCUNHO,actor_email,old["criado_em"] if old else stamp,stamp,None,"",encode(record)))
            c.execute("DELETE FROM memorandos_substituicao_etapas WHERE memorando_id=?",(identifier,)); c.execute("DELETE FROM memorandos_substituicao WHERE memorando_id=?",(identifier,))
            c.execute("INSERT INTO memorandos_substituicao VALUES(?,?,?,?,?,?,?,?,?,?,?)", (identifier,record["data_inicio"],record["data_fim"],record.get("gabinete_procurador_id"),record.get("gabinete_snapshot",""),record["natureza_funcao"],record["motivo"],record.get("motivo_texto", ""),record.get("signatario_id"),record["signatario_nome"],record["signatario_cargo"]))
            for order, step in enumerate(record["etapas"]): c.execute("INSERT INTO memorandos_substituicao_etapas(memorando_id,ordem,substituido_servidor_id,substituido_snapshot,substituto_servidor_id,substituto_snapshot) VALUES(?,?,?,?,?,?)", (identifier,order,step["substituido"].get("servidor_id"),encode(step["substituido"]),step["substituto"].get("servidor_id"),encode(step["substituto"])))
            self.store.event(c,"memorandos_salvar_rascunho",{"id":identifier,"usuario":actor_email})
        return identifier

    def get(self, identifier):
        with self.store.connection(read_only=True) as c:
            row=c.execute("SELECT * FROM memorandos WHERE id=?",(identifier,)).fetchone()
            if not row: raise ValueError("Memorando não encontrado.")
            return {**json.loads(row["payload"]), **dict(row), "situacao": substitution_status(dict(row)|json.loads(row["payload"]))}

    def finalize(self, identifier, *, preview_hash, pdf_bytes, filename):
        record=self.get(identifier)
        if record["status"] != STATUS_RASCUNHO or preview_hash != fingerprint({k:v for k,v in record.items() if k not in ("id","status","criado_por","criado_em","atualizado_em","finalizado_em","numero_oficial","payload","situacao")}): raise ValueError("Gere nova prévia antes de finalizar.")
        if not pdf_bytes.startswith(b"%PDF-"): raise ValueError("PDF definitivo inválido.")
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE"); current=c.execute("SELECT status FROM memorandos WHERE id=?",(identifier,)).fetchone()
            if not current or current[0]!=STATUS_RASCUNHO: raise ValueError("Rascunho indisponível.")
            c.execute("INSERT INTO memorandos_arquivos VALUES(?,?,?,?,?,?,?,?)",(uuid.uuid4().hex,identifier,filename,"application/pdf",len(pdf_bytes),hashlib.sha256(pdf_bytes).hexdigest(),now(),pdf_bytes))
            c.execute("UPDATE memorandos SET status=?,finalizado_em=?,atualizado_em=? WHERE id=?",(STATUS_FINALIZADO,now(),now(),identifier)); self.store.event(c,"memorandos_finalizar",{"id":identifier})
        return self.get(identifier)

    def set_official_number(self, identifier, number, actor_email):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE"); r=c.execute("SELECT status FROM memorandos WHERE id=?",(identifier,)).fetchone()
            if not r or r[0]!=STATUS_FINALIZADO: raise ValueError("Somente memorando finalizado recebe número oficial.")
            c.execute("UPDATE memorandos SET numero_oficial=?,atualizado_em=? WHERE id=?",(number.strip(),now(),identifier)); self.store.event(c,"memorandos_numero_oficial",{"id":identifier,"usuario":actor_email})

    def list(self, status=None, search="", server="", cabinet="", official_number="", start=None, end=None, offset=0, limit=50):
        clauses=["1=1"]; values=[]
        if status: clauses.append("m.status=?"); values.append(status)
        if search: clauses.append("LOWER(m.payload) LIKE LOWER(?)"); values.append("%"+search+"%")
        if server: clauses.append("LOWER(m.payload) LIKE LOWER(?)"); values.append("%"+server+"%")
        if cabinet: clauses.append("LOWER(s.gabinete_snapshot) LIKE LOWER(?)"); values.append("%"+cabinet+"%")
        if official_number: clauses.append("LOWER(m.numero_oficial) LIKE LOWER(?)"); values.append("%"+official_number+"%")
        if start: clauses.append("s.data_fim>=?"); values.append(start)
        if end: clauses.append("s.data_inicio<=?"); values.append(end)
        if not 0 <= offset or not 1 <= limit <= 200: raise ValueError("Página inválida.")
        with self.store.connection(read_only=True) as c:
            rows=[dict(r) for r in c.execute("SELECT m.id,m.status,m.criado_por,m.criado_em,m.atualizado_em,m.finalizado_em,m.numero_oficial,m.payload,s.data_inicio,s.data_fim,s.gabinete_snapshot,s.motivo,s.motivo_texto,s.natureza_funcao,s.signatario_nome,s.signatario_cargo FROM memorandos m JOIN memorandos_substituicao s ON s.memorando_id=m.id WHERE "+" AND ".join(clauses)+" ORDER BY m.atualizado_em DESC,m.id LIMIT ? OFFSET ?",values+[limit,offset])]
        for r in rows:
            p=json.loads(r.pop("payload")); r["cadeia"]=" → ".join([p["etapas"][0]["substituido"]["nome"]]+[x["substituto"]["nome"] for x in p["etapas"]]); r["situacao"]=substitution_status(r|p)
        return rows

    def overlaps(self, record, exclude_id=None):
        """A warning-only lookup; final validation never blocks legitimate overlap."""
        names = {normalize(person["nome"]) for step in record["etapas"] for person in (step["substituido"], step["substituto"])}
        candidates = self.list(start=record["data_inicio"], end=record["data_fim"], limit=200)
        return [row for row in candidates if row["id"] != exclude_id and any(normalize(name) in normalize(row["cadeia"]) for name in names)]

    def file(self, identifier):
        with self.store.connection(read_only=True) as c:
            r=c.execute("SELECT nome,conteudo FROM memorandos_arquivos WHERE memorando_id=? ORDER BY criado_em DESC LIMIT 1",(identifier,)).fetchone()
            return (r["nome"],bytes(r["conteudo"])) if r else None
