"""Additive e-mail notification schema. Message snapshots stay in this table."""

import json

from database.store import now, schema_key_of, unwrap_store

MARKER = "notificacoes_email_schema_v1"
_READY = set()
COLUMNS = (
    "id,evento,entidade_tipo,entidade_id,chave_idempotencia,status,remetente,"
    "destinatarios_snapshot,assunto_snapshot,corpo_snapshot,criado_por,criado_em,"
    "atualizado_em,enviado_em,tentativas,provedor_mensagem_id,erro"
)


def _loads(value, fallback):
    if not value:
        return fallback
    try:
        return json.loads(value)
    except (TypeError, ValueError):
        return fallback


def _row(row):
    if row is None:
        return None
    item = dict(row)
    item["destinatarios_snapshot"] = _loads(item.get("destinatarios_snapshot"), [])
    item["corpo_snapshot"] = _loads(item.get("corpo_snapshot"), {})
    item["tentativas"] = int(item.get("tentativas") or 0)
    return item


class NotificationsStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        with self.store.connection(read_only=True) as c:
            marker = c.execute(
                "SELECT 1 FROM configuracoes WHERE chave=?", (MARKER,)
            ).fetchone()
        if marker:
            _READY.add(key)
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        member = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS notificacoes_email ("
                f"id {identity},"
                "evento TEXT NOT NULL,"
                "entidade_tipo TEXT NOT NULL,"
                "entidade_id TEXT NOT NULL,"
                "chave_idempotencia TEXT NOT NULL UNIQUE,"
                "status TEXT NOT NULL CHECK(status IN ('DRAFT','SENDING','SENT','FAILED')),"
                "remetente TEXT NOT NULL DEFAULT '',"
                "destinatarios_snapshot TEXT NOT NULL DEFAULT '[]',"
                "assunto_snapshot TEXT NOT NULL DEFAULT '',"
                "corpo_snapshot TEXT NOT NULL DEFAULT '{}',"
                "criado_por TEXT NOT NULL DEFAULT '',"
                "criado_em TEXT NOT NULL,"
                "atualizado_em TEXT NOT NULL,"
                "enviado_em TEXT,"
                "tentativas INTEGER NOT NULL DEFAULT 0,"
                "provedor_mensagem_id TEXT,"
                "erro TEXT NOT NULL DEFAULT '')"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS notificacoes_email_entidade_idx "
                "ON notificacoes_email(entidade_tipo, entidade_id)"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS notificacao_destinatarios ("
                f"id {identity},"
                "evento TEXT NOT NULL,"
                "membro_tipo TEXT NOT NULL CHECK(membro_tipo IN ('PROCURADOR','SERVIDOR')),"
                f"membro_id {member} NOT NULL,"
                "email TEXT NOT NULL DEFAULT '',"
                "ativo INTEGER NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)),"
                "UNIQUE(evento, membro_tipo, membro_id))"
            )
            c.execute(
                "INSERT INTO configuracoes(chave,valor) VALUES(?,?) "
                "ON CONFLICT(chave) DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def get_by_key(self, key):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {COLUMNS} FROM notificacoes_email WHERE chave_idempotencia=?",
                (key,),
            ).fetchone()
        return _row(row)

    def ensure_draft(self, values):
        stamp = now()
        key = values["chave_idempotencia"]
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                "INSERT INTO notificacoes_email(evento,entidade_tipo,entidade_id,"
                "chave_idempotencia,status,criado_por,criado_em,atualizado_em) "
                "VALUES(?,?,?,?, 'DRAFT',?,?,?) ON CONFLICT(chave_idempotencia) DO NOTHING",
                (
                    values["evento"],
                    values["entidade_tipo"],
                    str(values["entidade_id"]),
                    key,
                    values.get("criado_por") or "",
                    stamp,
                    stamp,
                ),
            )
            row = c.execute(
                f"SELECT {COLUMNS} FROM notificacoes_email WHERE chave_idempotencia=?",
                (key,),
            ).fetchone()
        return _row(row)

    def claim(self, identifier, snapshot):
        """Move DRAFT or FAILED to SENDING. Returns the row only when this call wins."""
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            updated = c.execute(
                "UPDATE notificacoes_email SET status='SENDING', tentativas=tentativas+1,"
                "remetente=?,destinatarios_snapshot=?,assunto_snapshot=?,corpo_snapshot=?,"
                "erro='',atualizado_em=? WHERE id=? AND status IN ('DRAFT','FAILED')",
                (
                    snapshot["remetente"],
                    json.dumps(snapshot["destinatarios"], ensure_ascii=False),
                    snapshot["assunto"],
                    json.dumps(snapshot["corpo"], ensure_ascii=False),
                    stamp,
                    identifier,
                ),
            )
            if getattr(updated, "rowcount", 0) != 1:
                return None
            row = c.execute(
                f"SELECT {COLUMNS} FROM notificacoes_email WHERE id=?",
                (identifier,),
            ).fetchone()
        return _row(row)

    def mark_sent(self, identifier, provider_message_id):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            updated = c.execute(
                "UPDATE notificacoes_email SET status='SENT', enviado_em=?,"
                "provedor_mensagem_id=?,erro='',atualizado_em=? "
                "WHERE id=? AND status='SENDING'",
                (stamp, provider_message_id or "", stamp, identifier),
            )
            if getattr(updated, "rowcount", 0) != 1:
                return None
            row = c.execute(
                f"SELECT {COLUMNS} FROM notificacoes_email WHERE id=?",
                (identifier,),
            ).fetchone()
        return _row(row)

    def mark_failed(self, identifier, error):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            updated = c.execute(
                "UPDATE notificacoes_email SET status='FAILED', erro=?, atualizado_em=? "
                "WHERE id=? AND status='SENDING'",
                ((error or "")[:300], stamp, identifier),
            )
            if getattr(updated, "rowcount", 0) != 1:
                return None
            row = c.execute(
                f"SELECT {COLUMNS} FROM notificacoes_email WHERE id=?",
                (identifier,),
            ).fetchone()
        return _row(row)

    def recipients(self, evento, *, active_only=False):
        clause = " AND d.ativo=1" if active_only else ""
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                "SELECT d.id, d.evento, d.membro_tipo, d.membro_id, d.email, d.ativo,"
                " CASE WHEN d.membro_tipo='PROCURADOR' THEN p.nome ELSE s.nome END AS nome,"
                " CASE WHEN d.membro_tipo='PROCURADOR' THEN COALESCE(NULLIF(p.funcao,''), p.cargo_base, '')"
                " ELSE COALESCE(s.cargo, '') END AS cargo"
                " FROM notificacao_destinatarios d"
                " LEFT JOIN procuradores p ON d.membro_tipo='PROCURADOR' AND p.id=d.membro_id"
                " LEFT JOIN servidores s ON d.membro_tipo='SERVIDOR' AND s.id=d.membro_id"
                " WHERE d.evento=?" + clause + " ORDER BY d.membro_tipo, nome, d.id",
                (evento,),
            ).fetchall()
        items = []
        for row in rows:
            item = dict(row)
            item["ativo"] = bool(item.get("ativo"))
            item["email"] = (item.get("email") or "").strip().lower()
            items.append(item)
        return items

    def count_active(self, evento):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT COUNT(*) FROM notificacao_destinatarios WHERE evento=? AND ativo=1",
                (evento,),
            ).fetchone()
        return int(row[0] if row else 0)

    def save_recipient(self, evento, membro_tipo, membro_id, email, ativo):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                "INSERT INTO notificacao_destinatarios(evento,membro_tipo,membro_id,email,ativo) "
                "VALUES(?,?,?,?,?) ON CONFLICT(evento, membro_tipo, membro_id) "
                "DO UPDATE SET email=excluded.email, ativo=excluded.ativo",
                (evento, membro_tipo, int(membro_id), email, 1 if ativo else 0),
            )
        return next(
            item
            for item in self.recipients(evento)
            if item["membro_tipo"] == membro_tipo and int(item["membro_id"]) == int(membro_id)
        )
