"""Additive Ouvidoria schema. Listing never selects document bytes."""

import uuid

from database.store import now, schema_key_of, unwrap_store

MARKER = "ouvidoria_schema_v1"
_READY = set()
COLUMNS = (
    "id,numero_interno,tipo,forma_recebimento,data_recebimento,titulo,resumo,"
    "representado,tema,classificacao_acesso,prioridade,situacao,resultado,"
    "conclusao_analise,manifestante_identificado,manifestante_nome,"
    "manifestante_email,manifestante_telefone,observacoes,procurador_responsavel_id,"
    "representacao_id,criado_em,criado_por,atualizado_em,atualizado_por"
)
MEMBER_COLUMNS = "id,manifestacao_id,membro_tipo,membro_id,papel,criado_em"
PROGRESS_COLUMNS = "id,manifestacao_id,data,tipo,descricao,criado_em,criado_por"
ACTION_COLUMNS = (
    "id,manifestacao_id,tipo,data,descricao,responsavel_id,status,criado_em,criado_por"
)
DOCUMENT_META = (
    "id,manifestacao_id,providencia_id,andamento_id,tipo_documento,descricao,"
    "data_documento,nome_arquivo,mime_type,tamanho,criado_em,criado_por"
)


def _flag(value):
    return 1 if value else 0


class OuvidoriaStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        binary = "BYTEA" if self.store.backend == "postgresql" else "BLOB"
        fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                "CREATE TABLE IF NOT EXISTS ouvidoria_sequencias ("
                "ano INTEGER PRIMARY KEY CHECK(ano BETWEEN 1000 AND 9999),"
                "ultimo INTEGER NOT NULL CHECK(ultimo>=0))"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS ouvidoria_manifestacoes ("
                f"id {identity},"
                "numero_interno TEXT NOT NULL UNIQUE,"
                "tipo TEXT NOT NULL,"
                "forma_recebimento TEXT NOT NULL,"
                "data_recebimento TEXT NOT NULL,"
                "titulo TEXT NOT NULL,"
                "resumo TEXT NOT NULL DEFAULT '',"
                "representado TEXT NOT NULL DEFAULT '',"
                "tema TEXT NOT NULL DEFAULT '',"
                "classificacao_acesso TEXT NOT NULL DEFAULT 'RESTRITA',"
                "prioridade TEXT NOT NULL DEFAULT 'NORMAL',"
                "situacao TEXT NOT NULL,"
                "resultado TEXT,"
                "conclusao_analise TEXT NOT NULL DEFAULT '',"
                "manifestante_identificado INTEGER NOT NULL DEFAULT 0 "
                "CHECK(manifestante_identificado IN (0,1)),"
                "manifestante_nome TEXT NOT NULL DEFAULT '',"
                "manifestante_email TEXT NOT NULL DEFAULT '',"
                "manifestante_telefone TEXT NOT NULL DEFAULT '',"
                "observacoes TEXT NOT NULL DEFAULT '',"
                f"procurador_responsavel_id {fk},"
                f"representacao_id {fk} REFERENCES representacoes(id) ON DELETE SET NULL,"
                "criado_em TEXT NOT NULL,"
                "criado_por TEXT NOT NULL,"
                "atualizado_em TEXT NOT NULL,"
                "atualizado_por TEXT NOT NULL)"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS ouvidoria_integrantes ("
                f"id {identity},"
                f"manifestacao_id {fk} NOT NULL REFERENCES ouvidoria_manifestacoes(id) ON DELETE CASCADE,"
                "membro_tipo TEXT NOT NULL CHECK(membro_tipo IN ('PROCURADOR','SERVIDOR')),"
                f"membro_id {fk} NOT NULL,"
                "papel TEXT NOT NULL,"
                "criado_em TEXT NOT NULL,"
                "UNIQUE(manifestacao_id,membro_tipo,membro_id,papel))"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS ouvidoria_andamentos ("
                f"id {identity},"
                f"manifestacao_id {fk} NOT NULL REFERENCES ouvidoria_manifestacoes(id) ON DELETE CASCADE,"
                "data TEXT NOT NULL,"
                "tipo TEXT NOT NULL,"
                "descricao TEXT NOT NULL DEFAULT '',"
                "criado_em TEXT NOT NULL,"
                "criado_por TEXT NOT NULL)"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS ouvidoria_providencias ("
                f"id {identity},"
                f"manifestacao_id {fk} NOT NULL REFERENCES ouvidoria_manifestacoes(id) ON DELETE CASCADE,"
                "tipo TEXT NOT NULL,"
                "data TEXT NOT NULL,"
                "descricao TEXT NOT NULL DEFAULT '',"
                f"responsavel_id {fk},"
                "status TEXT NOT NULL DEFAULT 'REGISTRADA',"
                "criado_em TEXT NOT NULL,"
                "criado_por TEXT NOT NULL)"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS ouvidoria_documentos ("
                f"id TEXT PRIMARY KEY,"
                f"manifestacao_id {fk} NOT NULL REFERENCES ouvidoria_manifestacoes(id) ON DELETE CASCADE,"
                f"providencia_id {fk} REFERENCES ouvidoria_providencias(id) ON DELETE SET NULL,"
                f"andamento_id {fk} REFERENCES ouvidoria_andamentos(id) ON DELETE SET NULL,"
                "tipo_documento TEXT NOT NULL,"
                "descricao TEXT NOT NULL DEFAULT '',"
                "data_documento TEXT,"
                "nome_arquivo TEXT NOT NULL,"
                "mime_type TEXT NOT NULL,"
                "tamanho INTEGER NOT NULL,"
                f"arquivo {binary} NOT NULL,"
                "criado_em TEXT NOT NULL,"
                "criado_por TEXT NOT NULL)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_manifestacoes_sit_idx "
                "ON ouvidoria_manifestacoes(situacao, data_recebimento DESC, id DESC)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_manifestacoes_resp_idx "
                "ON ouvidoria_manifestacoes(procurador_responsavel_id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_manifestacoes_rep_idx "
                "ON ouvidoria_manifestacoes(representacao_id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_manifestacoes_res_idx "
                "ON ouvidoria_manifestacoes(resultado)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_integrantes_man_idx "
                "ON ouvidoria_integrantes(manifestacao_id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_andamentos_man_idx "
                "ON ouvidoria_andamentos(manifestacao_id, data DESC, id DESC)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_providencias_man_idx "
                "ON ouvidoria_providencias(manifestacao_id, data DESC)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS ouvidoria_documentos_man_idx "
                "ON ouvidoria_documentos(manifestacao_id, criado_em DESC)"
            )
            c.execute(
                "INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def _hydrate(self, record):
        record["manifestante_identificado"] = bool(record.get("manifestante_identificado"))
        return record

    def create(self, record, members, actor, files=None):
        stamp = now()
        year = int(record["data_recebimento"][:4])
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            seq = c.execute(
                "SELECT ultimo FROM ouvidoria_sequencias WHERE ano=?", (year,)
            ).fetchone()
            nxt = (seq[0] if seq else 0) + 1
            c.execute(
                "INSERT INTO ouvidoria_sequencias(ano,ultimo) VALUES(?,?) "
                "ON CONFLICT(ano) DO UPDATE SET ultimo=excluded.ultimo",
                (year, nxt),
            )
            number = f"OUVI-{year}-{nxt:03d}"
            inserted = c.execute(
                "INSERT INTO ouvidoria_manifestacoes(numero_interno,tipo,forma_recebimento,"
                "data_recebimento,titulo,resumo,representado,tema,classificacao_acesso,"
                "prioridade,situacao,resultado,conclusao_analise,manifestante_identificado,"
                "manifestante_nome,manifestante_email,manifestante_telefone,observacoes,"
                "procurador_responsavel_id,representacao_id,criado_em,criado_por,"
                "atualizado_em,atualizado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    number,
                    record["tipo"],
                    record["forma_recebimento"],
                    record["data_recebimento"],
                    record["titulo"],
                    record.get("resumo") or "",
                    record.get("representado") or "",
                    record.get("tema") or "",
                    record["classificacao_acesso"],
                    record["prioridade"],
                    record["situacao"],
                    record.get("resultado"),
                    record.get("conclusao_analise") or "",
                    _flag(record.get("manifestante_identificado")),
                    record.get("manifestante_nome") or "",
                    record.get("manifestante_email") or "",
                    record.get("manifestante_telefone") or "",
                    record.get("observacoes") or "",
                    record.get("procurador_responsavel_id"),
                    None,
                    stamp,
                    actor,
                    stamp,
                    actor,
                ),
            )
            identifier = inserted.lastrowid
            self._replace_members(c, identifier, members, stamp)
            self._add_progress(c, identifier, record["data_recebimento"], "CRIADA", "", stamp, actor)
            for meta, content in files or []:
                self._insert_document(c, identifier, meta, content, stamp, actor)
        return self.get(identifier)

    def update(self, identifier, record, members, actor, transfer_note=None):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if not c.execute(
                "SELECT id FROM ouvidoria_manifestacoes WHERE id=?", (identifier,)
            ).fetchone():
                raise ValueError("Notícia de fato não encontrada.")
            c.execute(
                "UPDATE ouvidoria_manifestacoes SET tipo=?,forma_recebimento=?,data_recebimento=?,"
                "titulo=?,resumo=?,representado=?,tema=?,classificacao_acesso=?,prioridade=?,"
                "situacao=?,resultado=?,conclusao_analise=?,manifestante_identificado=?,"
                "manifestante_nome=?,manifestante_email=?,manifestante_telefone=?,observacoes=?,"
                "procurador_responsavel_id=?,atualizado_em=?,atualizado_por=? WHERE id=?",
                (
                    record["tipo"],
                    record["forma_recebimento"],
                    record["data_recebimento"],
                    record["titulo"],
                    record.get("resumo") or "",
                    record.get("representado") or "",
                    record.get("tema") or "",
                    record["classificacao_acesso"],
                    record["prioridade"],
                    record["situacao"],
                    record.get("resultado"),
                    record.get("conclusao_analise") or "",
                    _flag(record.get("manifestante_identificado")),
                    record.get("manifestante_nome") or "",
                    record.get("manifestante_email") or "",
                    record.get("manifestante_telefone") or "",
                    record.get("observacoes") or "",
                    record.get("procurador_responsavel_id"),
                    stamp,
                    actor,
                    identifier,
                ),
            )
            self._replace_members(c, identifier, members, stamp)
            if transfer_note:
                self._add_progress(
                    c, identifier, stamp[:10], "RESPONSAVEL_ALTERADO", transfer_note, stamp, actor
                )
        return self.get(identifier)

    def link_representation(self, identifier, representacao_id, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            row = c.execute(
                "SELECT representacao_id FROM ouvidoria_manifestacoes WHERE id=?",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Notícia de fato não encontrada.")
            if row["representacao_id"]:
                raise ValueError("Esta notícia de fato já possui Projeto de Representação vinculado.")
            c.execute(
                "UPDATE ouvidoria_manifestacoes SET representacao_id=?,resultado=?,"
                "atualizado_em=?,atualizado_por=? WHERE id=?",
                (representacao_id, "PROJETO_REPRESENTACAO", stamp, actor, identifier),
            )
            self._add_progress(
                c, identifier, stamp[:10], "PROJETO_REPRESENTACAO", "", stamp, actor
            )
        return self.get(identifier)

    def add_progress(self, identifier, data, tipo, descricao, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if not c.execute(
                "SELECT id FROM ouvidoria_manifestacoes WHERE id=?", (identifier,)
            ).fetchone():
                raise ValueError("Notícia de fato não encontrada.")
            self._add_progress(c, identifier, data, tipo, descricao, stamp, actor)
            c.execute(
                "UPDATE ouvidoria_manifestacoes SET atualizado_em=?,atualizado_por=? WHERE id=?",
                (stamp, actor, identifier),
            )
        return self.progress(identifier)

    def add_action(self, identifier, payload, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if not c.execute(
                "SELECT id FROM ouvidoria_manifestacoes WHERE id=?", (identifier,)
            ).fetchone():
                raise ValueError("Notícia de fato não encontrada.")
            inserted = c.execute(
                "INSERT INTO ouvidoria_providencias(manifestacao_id,tipo,data,descricao,"
                "responsavel_id,status,criado_em,criado_por) VALUES(?,?,?,?,?,?,?,?)",
                (
                    identifier,
                    payload["tipo"],
                    payload["data"],
                    payload.get("descricao") or "",
                    payload.get("responsavel_id"),
                    payload.get("status") or "REGISTRADA",
                    stamp,
                    actor,
                ),
            )
            action_id = inserted.lastrowid
            self._add_progress(c, identifier, payload["data"], "PROVIDENCIA", "", stamp, actor)
            c.execute(
                "UPDATE ouvidoria_manifestacoes SET atualizado_em=?,atualizado_por=? WHERE id=?",
                (stamp, actor, identifier),
            )
        return action_id

    def update_action(self, identifier, action_id, payload, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if not c.execute(
                "SELECT id FROM ouvidoria_providencias WHERE id=? AND manifestacao_id=?",
                (action_id, identifier),
            ).fetchone():
                raise ValueError("Providência não encontrada.")
            c.execute(
                "UPDATE ouvidoria_providencias SET tipo=?,data=?,descricao=?,"
                "responsavel_id=?,status=? WHERE id=?",
                (
                    payload["tipo"],
                    payload["data"],
                    payload.get("descricao") or "",
                    payload.get("responsavel_id"),
                    payload.get("status") or "REGISTRADA",
                    action_id,
                ),
            )
            c.execute(
                "UPDATE ouvidoria_manifestacoes SET atualizado_em=?,atualizado_por=? WHERE id=?",
                (stamp, actor, identifier),
            )
        return action_id

    def add_document(self, identifier, meta, content, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if not c.execute(
                "SELECT id FROM ouvidoria_manifestacoes WHERE id=?", (identifier,)
            ).fetchone():
                raise ValueError("Notícia de fato não encontrada.")
            file_id = self._insert_document(c, identifier, meta, content, stamp, actor)
            c.execute(
                "UPDATE ouvidoria_manifestacoes SET atualizado_em=?,atualizado_por=? WHERE id=?",
                (stamp, actor, identifier),
            )
        return file_id

    def delete(self, identifier):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            row = c.execute(
                "SELECT representacao_id, situacao FROM ouvidoria_manifestacoes WHERE id=?",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Notícia de fato não encontrada.")
            if row["representacao_id"]:
                raise ValueError(
                    "Esta notícia de fato não pode ser excluída definitivamente porque possui Representação vinculada."
                )
            if row["situacao"] in ("ENCERRADA", "ARQUIVADA"):
                raise ValueError(
                    "Esta notícia de fato não pode ser excluída definitivamente porque já foi encerrada ou arquivada."
                )
            docs = c.execute(
                "SELECT COUNT(*) FROM ouvidoria_documentos WHERE manifestacao_id=?",
                (identifier,),
            ).fetchone()[0]
            acts = c.execute(
                "SELECT COUNT(*) FROM ouvidoria_providencias WHERE manifestacao_id=?",
                (identifier,),
            ).fetchone()[0]
            extra = c.execute(
                "SELECT COUNT(*) FROM ouvidoria_andamentos WHERE manifestacao_id=? "
                "AND tipo NOT IN ("
                "'CRIADA','ENCAMINHADA_OUVIDOR',"
                "'PROJETO_REPRESENTACAO','PROJETO_REPRESENTACAO_EXCLUIDO'"
                ")",
                (identifier,),
            ).fetchone()[0]
            if docs:
                raise ValueError(
                    "Esta notícia de fato não pode ser excluída definitivamente porque já possui documentos anexados."
                )
            if acts:
                raise ValueError(
                    "Esta notícia de fato não pode ser excluída definitivamente porque já possui providências registradas."
                )
            if extra:
                raise ValueError(
                    "Esta notícia de fato não pode ser excluída definitivamente porque já possui histórico de andamentos que deve ser preservado."
                )
            c.execute("DELETE FROM ouvidoria_manifestacoes WHERE id=?", (identifier,))
        return True

    def get(self, identifier):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {COLUMNS} FROM ouvidoria_manifestacoes WHERE id=?",
                (identifier,),
            ).fetchone()
            if not row:
                return None
            record = self._hydrate(dict(row))
            record["integrantes"] = [
                dict(item)
                for item in c.execute(
                    f"SELECT {MEMBER_COLUMNS} FROM ouvidoria_integrantes "
                    "WHERE manifestacao_id=? ORDER BY papel,id",
                    (identifier,),
                )
            ]
            return record

    def by_representation(self, representacao_id):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT id,numero_interno,titulo FROM ouvidoria_manifestacoes "
                "WHERE representacao_id=?",
                (representacao_id,),
            ).fetchone()
            return dict(row) if row else None

    def list(self, filters=None, limit=50, offset=0):
        """Lista metadados. Nunca seleciona o conteúdo binário do documento."""
        filters = filters or {}
        clauses = []
        args = []
        mapping = {
            "situacao": "situacao",
            "resultado": "resultado",
            "tipo": "tipo",
            "forma_recebimento": "forma_recebimento",
            "classificacao_acesso": "classificacao_acesso",
            "prioridade": "prioridade",
        }
        for key, column in mapping.items():
            if filters.get(key):
                clauses.append(column + "=?")
                args.append(filters[key])
        if filters.get("ano"):
            clauses.append("substr(data_recebimento,1,4)=?")
            args.append(str(filters["ano"]))
        if filters.get("representado"):
            clauses.append("LOWER(representado) LIKE LOWER(?)")
            args.append("%" + filters["representado"].strip() + "%")
        if filters.get("numero_interno"):
            clauses.append("LOWER(numero_interno) LIKE LOWER(?)")
            args.append("%" + filters["numero_interno"].strip() + "%")
        if filters.get("procurador_responsavel_id"):
            clauses.append("procurador_responsavel_id=?")
            args.append(filters["procurador_responsavel_id"])
        text = (filters.get("pesquisa") or "").strip()
        if text:
            clauses.append(
                "(LOWER(titulo) LIKE LOWER(?) OR LOWER(resumo) LIKE LOWER(?) "
                "OR LOWER(representado) LIKE LOWER(?) OR LOWER(numero_interno) LIKE LOWER(?))"
            )
            args.extend(["%" + text + "%"] * 4)
        if filters.get("procurador_id"):
            clauses.append(
                "EXISTS (SELECT 1 FROM ouvidoria_integrantes i WHERE i.manifestacao_id="
                "ouvidoria_manifestacoes.id AND i.membro_tipo='PROCURADOR' AND i.membro_id=? "
                "AND i.papel=?)"
            )
            args.extend([filters["procurador_id"], filters.get("procurador_papel") or "PROCURADOR_PARTICIPANTE"])
        if filters.get("assessor_id"):
            clauses.append(
                "EXISTS (SELECT 1 FROM ouvidoria_integrantes i WHERE i.manifestacao_id="
                "ouvidoria_manifestacoes.id AND i.membro_tipo='SERVIDOR' AND i.membro_id=? "
                "AND i.papel='ASSESSOR')"
            )
            args.append(filters["assessor_id"])
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT {COLUMNS} FROM ouvidoria_manifestacoes{where} "
                "ORDER BY data_recebimento DESC, id DESC LIMIT ? OFFSET ?",
                (*args, limit, offset),
            ).fetchall()
            records = [self._hydrate(dict(row)) for row in rows]
            ids = [row["id"] for row in records]
            members = {}
            latest = {}
            if ids:
                placeholders = ",".join("?" * len(ids))
                for item in c.execute(
                    f"SELECT {MEMBER_COLUMNS} FROM ouvidoria_integrantes "
                    f"WHERE manifestacao_id IN ({placeholders}) ORDER BY papel,id",
                    ids,
                ):
                    members.setdefault(item["manifestacao_id"], []).append(dict(item))
                for item in c.execute(
                    "SELECT manifestacao_id,data,tipo,descricao FROM ("
                    "SELECT manifestacao_id,data,tipo,descricao,"
                    "ROW_NUMBER() OVER (PARTITION BY manifestacao_id "
                    "ORDER BY data DESC, id DESC) AS rn "
                    f"FROM ouvidoria_andamentos WHERE manifestacao_id IN ({placeholders})"
                    ") ranked WHERE rn=1",
                    ids,
                ):
                    latest[item["manifestacao_id"]] = dict(item)
            for record in records:
                record["integrantes"] = members.get(record["id"], [])
                record["ultimo_andamento"] = latest.get(record["id"])
            return records

    def overview(self):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT "
                "SUM(CASE WHEN situacao='RECEBIDA' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN situacao IN ('TRIAGEM','ANALISE') THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN situacao='AGUARDANDO_PROVIDENCIA' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN situacao='PROVIDENCIA_ANDAMENTO' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN representacao_id IS NOT NULL THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN situacao='ARQUIVADA' THEN 1 ELSE 0 END) "
                "FROM ouvidoria_manifestacoes"
            ).fetchone()
        keys = (
            "recebidas",
            "analise",
            "aguardando",
            "providencia",
            "representacao",
            "arquivadas",
        )
        return dict(zip(keys, [int(value or 0) for value in row]))

    def progress(self, identifier):
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    f"SELECT {PROGRESS_COLUMNS} FROM ouvidoria_andamentos "
                    "WHERE manifestacao_id=? ORDER BY data DESC, id DESC",
                    (identifier,),
                )
            ]

    def actions(self, identifier):
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    f"SELECT {ACTION_COLUMNS} FROM ouvidoria_providencias "
                    "WHERE manifestacao_id=? ORDER BY data DESC, id DESC",
                    (identifier,),
                )
            ]

    def documents(self, identifier):
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    f"SELECT {DOCUMENT_META} FROM ouvidoria_documentos "
                    "WHERE manifestacao_id=? ORDER BY COALESCE(data_documento,criado_em) DESC, id DESC",
                    (identifier,),
                )
            ]

    def download(self, file_id):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT nome_arquivo,mime_type,arquivo FROM ouvidoria_documentos WHERE id=?",
                (file_id,),
            ).fetchone()
            if not row:
                raise ValueError("Documento não encontrado.")
            return {
                "nome": row["nome_arquivo"],
                "tipo": row["mime_type"],
                "conteudo": bytes(row["arquivo"]),
            }

    def _replace_members(self, c, identifier, members, stamp):
        c.execute(
            "DELETE FROM ouvidoria_integrantes WHERE manifestacao_id=?", (identifier,)
        )
        for member in members:
            c.execute(
                "INSERT INTO ouvidoria_integrantes(manifestacao_id,membro_tipo,membro_id,papel,criado_em) "
                "VALUES(?,?,?,?,?)",
                (
                    identifier,
                    member["membro_tipo"],
                    member["membro_id"],
                    member["papel"],
                    stamp,
                ),
            )

    def _insert_document(self, c, identifier, meta, content, stamp, actor):
        file_id = uuid.uuid4().hex
        c.execute(
            "INSERT INTO ouvidoria_documentos(id,manifestacao_id,providencia_id,andamento_id,"
            "tipo_documento,descricao,data_documento,nome_arquivo,mime_type,tamanho,arquivo,"
            "criado_em,criado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",
            (
                file_id,
                identifier,
                meta.get("providencia_id"),
                meta.get("andamento_id"),
                meta["tipo_documento"],
                meta.get("descricao") or "",
                meta.get("data_documento"),
                meta["nome_arquivo"],
                meta["mime_type"],
                len(content),
                content,
                stamp,
                actor,
            ),
        )
        return file_id

    def _add_progress(self, c, identifier, data, tipo, descricao, stamp, actor):
        c.execute(
            "INSERT INTO ouvidoria_andamentos(manifestacao_id,data,tipo,descricao,criado_em,criado_por) "
            "VALUES(?,?,?,?,?,?)",
            (identifier, data, tipo, descricao or "", stamp, actor),
        )


def ensure_schema(store):
    OuvidoriaStore(store)
