"""Isolated, additive persistence for Petições; list queries omit PDF bytes."""
import uuid
from database.store import now, schema_key_of, unwrap_store

_READY = set()

class PeticoesStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY: return
        identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.store.backend == "postgresql" else "INTEGER PRIMARY KEY"
        fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        binary = "BYTEA" if self.store.backend == "postgresql" else "BLOB"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes (id {identity},numero_tramita TEXT NOT NULL UNIQUE,data_protocolo TEXT NOT NULL,destinatario_tipo TEXT NOT NULL,destinatario TEXT NOT NULL,natureza TEXT NOT NULL,assunto TEXT NOT NULL,objeto TEXT NOT NULL,origem TEXT NOT NULL DEFAULT '',processo_tc TEXT NOT NULL DEFAULT '',situacao TEXT NOT NULL DEFAULT 'PROTOCOLADA' CHECK(situacao IN ('PROTOCOLADA','EM_ACOMPANHAMENTO','CONCLUIDA')),resultado_global TEXT NOT NULL DEFAULT '',observacoes TEXT NOT NULL DEFAULT '',concluida_em TEXT,criado_em TEXT NOT NULL,criado_por TEXT NOT NULL,atualizado_em TEXT NOT NULL,atualizado_por TEXT NOT NULL)")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_signatarios (peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,procurador_id {fk} NOT NULL REFERENCES procuradores(id),PRIMARY KEY(peticao_id,procurador_id))")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_pedidos (id {identity},peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,descricao TEXT NOT NULL,ordem INTEGER NOT NULL CHECK(ordem>0),situacao_resultado TEXT NOT NULL DEFAULT 'PENDENTE' CHECK(situacao_resultado IN ('PENDENTE','ACOLHIDO','ACOLHIDO_PARCIALMENTE','INDEFERIDO','PREJUDICADO','OUTRO')),resultado TEXT NOT NULL DEFAULT '',data_resultado TEXT,criado_em TEXT NOT NULL,atualizado_em TEXT NOT NULL,UNIQUE(peticao_id,ordem))")
            columns = {row[0] for row in c.execute("SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='peticoes_pedidos'")} if self.store.backend == "postgresql" else {row[1] for row in c.execute("PRAGMA table_info(peticoes_pedidos)")}
            for column, definition in (("excluido", "INTEGER NOT NULL DEFAULT 0 CHECK(excluido IN (0,1))"), ("excluido_em", "TEXT"), ("excluido_por", "TEXT NOT NULL DEFAULT ''"), ("motivo_exclusao", "TEXT NOT NULL DEFAULT ''")):
                if column not in columns: c.execute(f"ALTER TABLE peticoes_pedidos ADD COLUMN {column} {definition}")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_andamentos (id {identity},peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,data TEXT NOT NULL,descricao TEXT NOT NULL,criado_em TEXT NOT NULL,criado_por TEXT NOT NULL,excluido INTEGER NOT NULL DEFAULT 0 CHECK(excluido IN (0,1)),excluido_em TEXT,excluido_por TEXT NOT NULL DEFAULT '',motivo_exclusao TEXT NOT NULL DEFAULT '')")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_documentos (id TEXT PRIMARY KEY,peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,andamento_id {fk} REFERENCES peticoes_andamentos(id) ON DELETE CASCADE,tipo_documento TEXT NOT NULL DEFAULT 'PRINCIPAL',categoria TEXT NOT NULL DEFAULT '',nome TEXT NOT NULL,mime_type TEXT NOT NULL,tamanho INTEGER NOT NULL CHECK(tamanho>0),arquivo {binary} NOT NULL,criado_em TEXT NOT NULL,criado_por TEXT NOT NULL)")
            document_columns = {row[0] for row in c.execute("SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='peticoes_documentos'")} if self.store.backend == "postgresql" else {row[1] for row in c.execute("PRAGMA table_info(peticoes_documentos)")}
            for column, definition in (("andamento_id", f"{fk} REFERENCES peticoes_andamentos(id) ON DELETE CASCADE"), ("tipo_documento", "TEXT NOT NULL DEFAULT 'PRINCIPAL'"), ("categoria", "TEXT NOT NULL DEFAULT ''")):
                if column not in document_columns: c.execute(f"ALTER TABLE peticoes_documentos ADD COLUMN {column} {definition}")
            for sql in ("CREATE INDEX IF NOT EXISTS peticoes_lista_idx ON peticoes(situacao,data_protocolo DESC,id DESC)","CREATE INDEX IF NOT EXISTS peticoes_andamentos_idx ON peticoes_andamentos(peticao_id,data DESC,id DESC)","CREATE INDEX IF NOT EXISTS peticoes_pedidos_idx ON peticoes_pedidos(peticao_id,ordem)"): c.execute(sql)
        _READY.add(key)

    def _replace_relations(self, c, identifier, data, stamp, actor="sistema"):
        c.execute("DELETE FROM peticoes_signatarios WHERE peticao_id=?", (identifier,))
        c.executemany(
            "INSERT INTO peticoes_signatarios VALUES(?,?)",
            [(identifier, x) for x in data["signatarios"]],
        )
        previous = [
            row[0]
            for row in c.execute(
                "SELECT id FROM peticoes_pedidos WHERE peticao_id=? AND excluido=0",
                (identifier,),
            )
        ]
        if previous:
            offset = (
                c.execute(
                    "SELECT COALESCE(MAX(ordem),0) FROM peticoes_pedidos WHERE peticao_id=?",
                    (identifier,),
                ).fetchone()[0]
                or 0
            ) + 10000
            c.execute(
                "UPDATE peticoes_pedidos SET ordem=ordem+?,excluido=1,excluido_em=?,excluido_por=?,motivo_exclusao='Substituído na edição da Petição.',atualizado_em=? WHERE peticao_id=? AND excluido=0",
                (offset, stamp, actor, stamp, identifier),
            )
        c.executemany(
            "INSERT INTO peticoes_pedidos(peticao_id,descricao,ordem,criado_em,atualizado_em) VALUES(?,?,?,?,?)",
            [(identifier, text, order, stamp, stamp) for order, text in enumerate(data["pedidos"], 1)],
        )
        return previous

    def create(self,data,actor,upload):
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            try: row=c.execute("INSERT INTO peticoes(numero_tramita,data_protocolo,destinatario_tipo,destinatario,natureza,assunto,objeto,origem,processo_tc,observacoes,criado_em,criado_por,atualizado_em,atualizado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(data['numero_tramita'],data['data_protocolo'],data['destinatario_tipo'],data['destinatario'],data['natureza'],data['assunto'],data['objeto'],data.get('origem',''),data.get('processo_tc',''),data.get('observacoes',''),stamp,actor,stamp,actor))
            except Exception as exc:
                if 'unique' in str(exc).lower(): raise ValueError('Já existe uma Petição com este número Tramita.') from exc
                raise
            identifier=row.lastrowid; self._replace_relations(c,identifier,data,stamp)
            name,mime,content=upload; c.execute("INSERT INTO peticoes_documentos(id,peticao_id,andamento_id,tipo_documento,categoria,nome,mime_type,tamanho,arquivo,criado_em,criado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?)",(uuid.uuid4().hex,identifier,None,'PRINCIPAL','',name,mime,len(content),content,stamp,actor)); c.execute("INSERT INTO peticoes_andamentos(peticao_id,data,descricao,criado_em,criado_por) VALUES(?,?,?,?,?)",(identifier,data['data_protocolo'],'Petição protocolada.',stamp,actor))
        return self.get(identifier)

    def update(self,identifier,data,actor,upload=None):
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            try: result=c.execute("UPDATE peticoes SET numero_tramita=?,data_protocolo=?,destinatario_tipo=?,destinatario=?,natureza=?,assunto=?,objeto=?,origem=?,processo_tc=?,observacoes=?,atualizado_em=?,atualizado_por=? WHERE id=?",(data['numero_tramita'],data['data_protocolo'],data['destinatario_tipo'],data['destinatario'],data['natureza'],data['assunto'],data['objeto'],data.get('origem',''),data.get('processo_tc',''),data.get('observacoes',''),stamp,actor,identifier))
            except Exception as exc:
                if 'unique' in str(exc).lower(): raise ValueError('Já existe uma Petição com este número Tramita.') from exc
                raise
            if not getattr(result,'rowcount',1): raise ValueError('Petição não encontrada.')
            if "signatarios" in data:
                c.execute("DELETE FROM peticoes_signatarios WHERE peticao_id=?",(identifier,)); c.executemany("INSERT INTO peticoes_signatarios VALUES(?,?)",[(identifier,x) for x in data['signatarios']])
            removed = []
            if "pedidos" in data:
                signers = data.get(
                    "signatarios",
                    [x[0] for x in c.execute("SELECT procurador_id FROM peticoes_signatarios WHERE peticao_id=?", (identifier,))],
                )
                removed = self._replace_relations(
                    c, identifier, {"signatarios": signers, "pedidos": data["pedidos"]}, stamp, actor
                )
            if upload:
                name,mime,content=upload; c.execute("DELETE FROM peticoes_documentos WHERE peticao_id=? AND tipo_documento='PRINCIPAL'",(identifier,)); c.execute("INSERT INTO peticoes_documentos(id,peticao_id,andamento_id,tipo_documento,categoria,nome,mime_type,tamanho,arquivo,criado_em,criado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?)",(uuid.uuid4().hex,identifier,None,'PRINCIPAL','',name,mime,len(content),content,stamp,actor))
        return self.get(identifier), removed

    def get(self,identifier):
        with self.store.connection(read_only=True) as c:
            row=c.execute("SELECT id,numero_tramita,data_protocolo,destinatario_tipo,destinatario,natureza,assunto,objeto,origem,processo_tc,situacao,resultado_global,observacoes,concluida_em,criado_em,criado_por,atualizado_em,atualizado_por FROM peticoes WHERE id=?",(identifier,)).fetchone()
            if not row:return None
            data=dict(row); data['signatarios']=[x[0] for x in c.execute("SELECT procurador_id FROM peticoes_signatarios WHERE peticao_id=? ORDER BY procurador_id",(identifier,))]; data['pedidos']=[dict(x) for x in c.execute("SELECT id,descricao,ordem,situacao_resultado,resultado,data_resultado FROM peticoes_pedidos WHERE peticao_id=? AND excluido=0 ORDER BY ordem",(identifier,))]; return data

    def list(self,situacao=None):
        with self.store.connection(read_only=True) as c:
            sql="SELECT id,numero_tramita,data_protocolo,destinatario,natureza,assunto,situacao,resultado_global FROM peticoes"; args=()
            if situacao:sql+=" WHERE situacao=?";args=(situacao,)
            return [dict(x) for x in c.execute(sql+" ORDER BY data_protocolo DESC,id DESC LIMIT 100",args)]

    def list_resumo(self, *, situacoes=None, texto="", signatario_id=None, limit=15, offset=0):
        """Page of petition cards. One connection, no PDF bytes and no full timeline."""
        clauses, args = [], []
        if situacoes:
            clauses.append("situacao IN (" + ",".join("?" * len(situacoes)) + ")")
            args.extend(situacoes)
        term = str(texto or "").strip()
        if term:
            escaped = term.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
            like = f"%{escaped}%"
            clauses.append(
                "(numero_tramita LIKE ? ESCAPE '\\' OR assunto LIKE ? ESCAPE '\\' "
                "OR objeto LIKE ? ESCAPE '\\' OR destinatario LIKE ? ESCAPE '\\' "
                "OR origem LIKE ? ESCAPE '\\' OR processo_tc LIKE ? ESCAPE '\\')"
            )
            args.extend([like] * 6)
        if signatario_id:
            clauses.append(
                "EXISTS (SELECT 1 FROM peticoes_signatarios s "
                "WHERE s.peticao_id=peticoes.id AND s.procurador_id=?)"
            )
            args.append(signatario_id)
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        columns = (
            "id,numero_tramita,data_protocolo,destinatario_tipo,destinatario,natureza,"
            "assunto,objeto,origem,processo_tc,situacao,resultado_global"
        )
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT {columns} FROM peticoes{where} "
                "ORDER BY data_protocolo DESC, id DESC LIMIT ? OFFSET ?",
                (*args, limit, offset),
            ).fetchall()
            records = [dict(row) for row in rows]
            ids = [row["id"] for row in records]
            signers, latest, requests = {}, {}, {}
            if ids:
                placeholders = ",".join("?" * len(ids))
                for item in c.execute(
                    "SELECT s.peticao_id, p.id AS procurador_id, p.nome "
                    "FROM peticoes_signatarios s JOIN procuradores p ON p.id=s.procurador_id "
                    f"WHERE s.peticao_id IN ({placeholders}) ORDER BY p.nome",
                    ids,
                ):
                    signers.setdefault(item["peticao_id"], []).append(
                        {"id": item["procurador_id"], "nome": item["nome"]}
                    )
                for item in c.execute(
                    "SELECT peticao_id, data, descricao FROM ("
                    "SELECT peticao_id, data, descricao, "
                    "ROW_NUMBER() OVER (PARTITION BY peticao_id ORDER BY data DESC, id DESC) AS rn "
                    "FROM peticoes_andamentos "
                    f"WHERE peticao_id IN ({placeholders}) AND excluido=0"
                    ") ranked WHERE rn=1",
                    ids,
                ):
                    latest[item["peticao_id"]] = {
                        "data": item["data"],
                        "descricao": item["descricao"],
                    }
                for item in c.execute(
                    "SELECT peticao_id, id, descricao, ordem, situacao_resultado, resultado, "
                    "data_resultado, excluido FROM peticoes_pedidos "
                    f"WHERE peticao_id IN ({placeholders}) AND ("
                    "excluido=0 OR situacao_resultado!='PENDENTE' OR resultado!=''"
                    ") ORDER BY peticao_id, excluido, ordem",
                    ids,
                ):
                    bucket = requests.setdefault(
                        item["peticao_id"], {"ativos": [], "anteriores": []}
                    )
                    payload = dict(item)
                    if not payload["excluido"]:
                        bucket["ativos"].append(payload)
                    if payload["situacao_resultado"] != "PENDENTE" or str(
                        payload["resultado"] or ""
                    ).strip():
                        bucket["anteriores"].append(payload)
            for record in records:
                grouped = requests.get(record["id"], {"ativos": [], "anteriores": []})
                record["signatarios"] = signers.get(record["id"], [])
                record["ultimo_andamento"] = latest.get(record["id"])
                record["pedidos"] = grouped["ativos"]
                record["resultados_anteriores"] = grouped["anteriores"]
            return records
    def progress(self,identifier):
        with self.store.connection(read_only=True) as c:
            items=[dict(x) for x in c.execute("SELECT id,data,descricao,criado_em,criado_por FROM peticoes_andamentos WHERE peticao_id=? AND excluido=0 ORDER BY data DESC,id DESC",(identifier,))]
            if not items:return items
            ids=[item['id'] for item in items]; marks=','.join('?'*len(ids))
            documents={}
            for row in c.execute(f"SELECT id,andamento_id,categoria,nome,mime_type,tamanho FROM peticoes_documentos WHERE andamento_id IN ({marks}) ORDER BY criado_em,id",ids): documents.setdefault(row['andamento_id'],[]).append(dict(row))
            for item in items:item['documentos']=documents.get(item['id'],[])
            return items
    def add_progress(self,identifier,data,description,actor,documents=()):
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE"); row=c.execute("INSERT INTO peticoes_andamentos(peticao_id,data,descricao,criado_em,criado_por) VALUES(?,?,?,?,?)",(identifier,data,description,stamp,actor)); andamento_id=row.lastrowid
            for name,mime,content,categoria in documents:c.execute("INSERT INTO peticoes_documentos(id,peticao_id,andamento_id,tipo_documento,categoria,nome,mime_type,tamanho,arquivo,criado_em,criado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?)",(uuid.uuid4().hex,identifier,andamento_id,'RECEBIDO',categoria,name,mime,len(content),content,stamp,actor))
            c.execute("UPDATE peticoes SET situacao='EM_ACOMPANHAMENTO',atualizado_em=?,atualizado_por=? WHERE id=? AND situacao!='CONCLUIDA'",(stamp,actor,identifier)); return andamento_id
    def progress_documents(self, identifier):
        """Bytes only for the petition whose history the user explicitly opened."""
        with self.store.connection(read_only=True) as c:
            return [dict(row) for row in c.execute(
                "SELECT d.id,d.andamento_id,d.categoria,d.nome,d.mime_type,d.arquivo "
                "FROM peticoes_documentos d JOIN peticoes_andamentos a ON a.id=d.andamento_id "
                "WHERE d.peticao_id=? AND a.excluido=0 ORDER BY d.criado_em,d.id",
                (identifier,),
            )]
    def remove_progress(self,progress_id,actor,reason):
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE");row=c.execute("SELECT peticao_id FROM peticoes_andamentos WHERE id=? AND excluido=0",(progress_id,)).fetchone()
            if not row:raise ValueError('Andamento não encontrado.')
            c.execute("UPDATE peticoes_andamentos SET excluido=1,excluido_em=?,excluido_por=?,motivo_exclusao=? WHERE id=?",(stamp,actor,reason,progress_id));return row[0]
    def update_request_result(self,request_id,status,result,result_date):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE");row=c.execute("SELECT peticao_id FROM peticoes_pedidos WHERE id=?",(request_id,)).fetchone()
            if not row:raise ValueError('Pedido não encontrado.')
            c.execute("UPDATE peticoes_pedidos SET situacao_resultado=?,resultado=?,data_resultado=?,atualizado_em=? WHERE id=?",(status,result,result_date,now(),request_id));return row[0]
    def save_requests(self,identifier,requests,actor,reason="Removido na edição da Petição."):
        """Atomically replace request ordering while preserving each request result."""
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            existing={row['id']:dict(row) for row in c.execute("SELECT * FROM peticoes_pedidos WHERE peticao_id=? AND excluido=0",(identifier,))}
            offset=(c.execute("SELECT COALESCE(MAX(ordem),0) FROM peticoes_pedidos WHERE peticao_id=?",(identifier,)).fetchone()[0] or 0)+10000; c.execute("UPDATE peticoes_pedidos SET ordem=ordem+? WHERE peticao_id=? AND excluido=0",(offset,identifier))
            seen=set()
            for order,item in enumerate(requests,1):
                request_id=item.get('id')
                if request_id in existing:
                    c.execute("UPDATE peticoes_pedidos SET descricao=?,ordem=?,atualizado_em=? WHERE id=?",(item['descricao'],order,stamp,request_id));seen.add(request_id)
                else:c.execute("INSERT INTO peticoes_pedidos(peticao_id,descricao,ordem,criado_em,atualizado_em) VALUES(?,?,?,?,?)",(identifier,item['descricao'],order,stamp,stamp))
            removed = set(existing) - seen
            for request_id in removed:c.execute("UPDATE peticoes_pedidos SET excluido=1,excluido_em=?,excluido_por=?,motivo_exclusao=?,atualizado_em=? WHERE id=?",(stamp,actor,reason,stamp,request_id))
            return list(removed)
    def conclude(self,identifier,result,actor):
        stamp=now()
        with self.store.connection() as c:c.execute("BEGIN IMMEDIATE");c.execute("UPDATE peticoes SET situacao='CONCLUIDA',resultado_global=?,concluida_em=?,atualizado_em=?,atualizado_por=? WHERE id=?",(result,stamp[:10],stamp,actor,identifier))

    def save_resultado(self, identifier, result, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            updated = c.execute(
                "UPDATE peticoes SET resultado_global=?,atualizado_em=?,atualizado_por=? WHERE id=?",
                (result or "", stamp, actor, identifier),
            )
            if not getattr(updated, "rowcount", 1):
                raise ValueError("Petição não encontrada.")

    def resultados_anteriores(self, identifier):
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    "SELECT descricao,ordem,situacao_resultado,resultado,data_resultado,excluido "
                    "FROM peticoes_pedidos WHERE peticao_id=? AND ("
                    "situacao_resultado!='PENDENTE' OR resultado!='') "
                    "ORDER BY excluido, ordem, id",
                    (identifier,),
                )
            ]
    def document(self,identifier):
        with self.store.connection(read_only=True) as c:
            row=c.execute("SELECT nome,mime_type,arquivo FROM peticoes_documentos WHERE peticao_id=? AND tipo_documento='PRINCIPAL' ORDER BY criado_em LIMIT 1",(identifier,)).fetchone();return dict(row) if row else None
