"""Isolated, additive persistence for Petições; list queries omit PDF bytes."""
import uuid
from database.store import now, schema_key_of, unwrap_store

_READY = set()

class PeticoesStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY: return
        identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.store.backend == "postgresql" else "INTEGER PRIMARY KEY"
        fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        binary = "BYTEA" if self.store.backend == "postgresql" else "BLOB"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes (id {identity},numero_tramita TEXT NOT NULL UNIQUE,data_protocolo TEXT NOT NULL,destinatario_tipo TEXT NOT NULL,destinatario TEXT NOT NULL,natureza TEXT NOT NULL,assunto TEXT NOT NULL,objeto TEXT NOT NULL,origem TEXT NOT NULL DEFAULT '',processo_tc TEXT NOT NULL DEFAULT '',situacao TEXT NOT NULL DEFAULT 'PROTOCOLADA' CHECK(situacao IN ('PROTOCOLADA','EM_ACOMPANHAMENTO','CONCLUIDA')),resultado_global TEXT NOT NULL DEFAULT '',observacoes TEXT NOT NULL DEFAULT '',concluida_em TEXT,criado_em TEXT NOT NULL,criado_por TEXT NOT NULL,atualizado_em TEXT NOT NULL,atualizado_por TEXT NOT NULL)")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_signatarios (peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,procurador_id {fk} NOT NULL REFERENCES procuradores(id),PRIMARY KEY(peticao_id,procurador_id))")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_pedidos (id {identity},peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,descricao TEXT NOT NULL,ordem INTEGER NOT NULL CHECK(ordem>0),situacao_resultado TEXT NOT NULL DEFAULT 'PENDENTE' CHECK(situacao_resultado IN ('PENDENTE','ACOLHIDO','ACOLHIDO_PARCIALMENTE','INDEFERIDO','PREJUDICADO','OUTRO')),resultado TEXT NOT NULL DEFAULT '',data_resultado TEXT,criado_em TEXT NOT NULL,atualizado_em TEXT NOT NULL,UNIQUE(peticao_id,ordem))")
            columns = {row[0] for row in c.execute("SELECT column_name FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='peticoes_pedidos'")} if self.store.backend == "postgresql" else {row[1] for row in c.execute("PRAGMA table_info(peticoes_pedidos)")}
            for column, definition in (("excluido", "INTEGER NOT NULL DEFAULT 0 CHECK(excluido IN (0,1))"), ("excluido_em", "TEXT"), ("excluido_por", "TEXT NOT NULL DEFAULT ''"), ("motivo_exclusao", "TEXT NOT NULL DEFAULT ''")):
                if column not in columns: c.execute(f"ALTER TABLE peticoes_pedidos ADD COLUMN {column} {definition}")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_andamentos (id {identity},peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,data TEXT NOT NULL,descricao TEXT NOT NULL,criado_em TEXT NOT NULL,criado_por TEXT NOT NULL,excluido INTEGER NOT NULL DEFAULT 0 CHECK(excluido IN (0,1)),excluido_em TEXT,excluido_por TEXT NOT NULL DEFAULT '',motivo_exclusao TEXT NOT NULL DEFAULT '')")
            c.execute(f"CREATE TABLE IF NOT EXISTS peticoes_documentos (id TEXT PRIMARY KEY,peticao_id {fk} NOT NULL REFERENCES peticoes(id) ON DELETE CASCADE,nome TEXT NOT NULL,mime_type TEXT NOT NULL,tamanho INTEGER NOT NULL CHECK(tamanho>0),arquivo {binary} NOT NULL,criado_em TEXT NOT NULL,criado_por TEXT NOT NULL)")
            for sql in ("CREATE INDEX IF NOT EXISTS peticoes_lista_idx ON peticoes(situacao,data_protocolo DESC,id DESC)","CREATE INDEX IF NOT EXISTS peticoes_andamentos_idx ON peticoes_andamentos(peticao_id,data DESC,id DESC)","CREATE INDEX IF NOT EXISTS peticoes_pedidos_idx ON peticoes_pedidos(peticao_id,ordem)"): c.execute(sql)
        _READY.add(key)

    def _replace_relations(self,c,identifier,data,stamp):
        c.execute("DELETE FROM peticoes_signatarios WHERE peticao_id=?",(identifier,)); c.executemany("INSERT INTO peticoes_signatarios VALUES(?,?)",[(identifier,x) for x in data['signatarios']])
        offset=(c.execute("SELECT COALESCE(MAX(ordem),0) FROM peticoes_pedidos WHERE peticao_id=?",(identifier,)).fetchone()[0] or 0)+10000; c.execute("UPDATE peticoes_pedidos SET ordem=ordem+?,excluido=1,excluido_em=?,excluido_por='sistema',motivo_exclusao='Substituído na edição da Petição.',atualizado_em=? WHERE peticao_id=? AND excluido=0",(offset,stamp,stamp,identifier)); c.executemany("INSERT INTO peticoes_pedidos(peticao_id,descricao,ordem,criado_em,atualizado_em) VALUES(?,?,?,?,?)",[(identifier,x,n,stamp,stamp) for n,x in enumerate(data['pedidos'],1)])

    def create(self,data,actor,upload):
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            try: row=c.execute("INSERT INTO peticoes(numero_tramita,data_protocolo,destinatario_tipo,destinatario,natureza,assunto,objeto,origem,processo_tc,observacoes,criado_em,criado_por,atualizado_em,atualizado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(data['numero_tramita'],data['data_protocolo'],data['destinatario_tipo'],data['destinatario'],data['natureza'],data['assunto'],data['objeto'],data.get('origem',''),data.get('processo_tc',''),data.get('observacoes',''),stamp,actor,stamp,actor))
            except Exception as exc:
                if 'unique' in str(exc).lower(): raise ValueError('Já existe uma Petição com este número Tramita.') from exc
                raise
            identifier=row.lastrowid; self._replace_relations(c,identifier,data,stamp)
            name,mime,content=upload; c.execute("INSERT INTO peticoes_documentos VALUES(?,?,?,?,?,?,?,?)",(uuid.uuid4().hex,identifier,name,mime,len(content),content,stamp,actor)); c.execute("INSERT INTO peticoes_andamentos(peticao_id,data,descricao,criado_em,criado_por) VALUES(?,?,?,?,?)",(identifier,data['data_protocolo'],'Petição protocolada.',stamp,actor))
        return self.get(identifier)

    def update(self,identifier,data,actor,upload=None):
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            try: result=c.execute("UPDATE peticoes SET numero_tramita=?,data_protocolo=?,destinatario_tipo=?,destinatario=?,natureza=?,assunto=?,objeto=?,origem=?,processo_tc=?,observacoes=?,atualizado_em=?,atualizado_por=? WHERE id=?",(data['numero_tramita'],data['data_protocolo'],data['destinatario_tipo'],data['destinatario'],data['natureza'],data['assunto'],data['objeto'],data.get('origem',''),data.get('processo_tc',''),data.get('observacoes',''),stamp,actor,identifier))
            except Exception as exc:
                if 'unique' in str(exc).lower(): raise ValueError('Já existe uma Petição com este número Tramita.') from exc
                raise
            if not getattr(result,'rowcount',1): raise ValueError('Petição não encontrada.')
            if "signatarios" in data:
                c.execute("DELETE FROM peticoes_signatarios WHERE peticao_id=?",(identifier,)); c.executemany("INSERT INTO peticoes_signatarios VALUES(?,?)",[(identifier,x) for x in data['signatarios']])
            if "pedidos" in data:
                self._replace_relations(c,identifier,{"signatarios": data.get("signatarios", [x[0] for x in c.execute("SELECT procurador_id FROM peticoes_signatarios WHERE peticao_id=?",(identifier,))]),"pedidos":data["pedidos"]},stamp)
            if upload:
                name,mime,content=upload; c.execute("DELETE FROM peticoes_documentos WHERE peticao_id=?",(identifier,)); c.execute("INSERT INTO peticoes_documentos VALUES(?,?,?,?,?,?,?,?)",(uuid.uuid4().hex,identifier,name,mime,len(content),content,stamp,actor))
        return self.get(identifier)

    def get(self,identifier):
        with self.store.connection(read_only=True) as c:
            row=c.execute("SELECT id,numero_tramita,data_protocolo,destinatario_tipo,destinatario,natureza,assunto,objeto,origem,processo_tc,situacao,resultado_global,observacoes,concluida_em,criado_em,criado_por,atualizado_em,atualizado_por FROM peticoes WHERE id=?",(identifier,)).fetchone()
            if not row:return None
            data=dict(row); data['signatarios']=[x[0] for x in c.execute("SELECT procurador_id FROM peticoes_signatarios WHERE peticao_id=? ORDER BY procurador_id",(identifier,))]; data['pedidos']=[dict(x) for x in c.execute("SELECT id,descricao,ordem,situacao_resultado,resultado,data_resultado FROM peticoes_pedidos WHERE peticao_id=? AND excluido=0 ORDER BY ordem",(identifier,))]; return data

    def list(self,situacao=None):
        with self.store.connection(read_only=True) as c:
            sql="SELECT id,numero_tramita,data_protocolo,destinatario,natureza,assunto,situacao,resultado_global FROM peticoes"; args=()
            if situacao:sql+=" WHERE situacao=?";args=(situacao,)
            return [dict(x) for x in c.execute(sql+" ORDER BY data_protocolo DESC,id DESC LIMIT 100",args)]
    def progress(self,identifier):
        with self.store.connection(read_only=True) as c:return [dict(x) for x in c.execute("SELECT id,data,descricao,criado_em,criado_por FROM peticoes_andamentos WHERE peticao_id=? AND excluido=0 ORDER BY data DESC,id DESC",(identifier,))]
    def add_progress(self,identifier,data,description,actor):
        stamp=now()
        with self.store.connection() as c:c.execute("BEGIN IMMEDIATE");c.execute("INSERT INTO peticoes_andamentos(peticao_id,data,descricao,criado_em,criado_por) VALUES(?,?,?,?,?)",(identifier,data,description,stamp,actor));c.execute("UPDATE peticoes SET situacao='EM_ACOMPANHAMENTO',atualizado_em=?,atualizado_por=? WHERE id=? AND situacao!='CONCLUIDA'",(stamp,actor,identifier))
    def remove_progress(self,progress_id,actor,reason):
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE");row=c.execute("SELECT peticao_id FROM peticoes_andamentos WHERE id=? AND excluido=0",(progress_id,)).fetchone()
            if not row:raise ValueError('Andamento não encontrado.')
            c.execute("UPDATE peticoes_andamentos SET excluido=1,excluido_em=?,excluido_por=?,motivo_exclusao=? WHERE id=?",(stamp,actor,reason,progress_id));return row[0]
    def update_request_result(self,request_id,status,result,result_date):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE");row=c.execute("SELECT peticao_id FROM peticoes_pedidos WHERE id=?",(request_id,)).fetchone()
            if not row:raise ValueError('Pedido não encontrado.')
            c.execute("UPDATE peticoes_pedidos SET situacao_resultado=?,resultado=?,data_resultado=?,atualizado_em=? WHERE id=?",(status,result,result_date,now(),request_id));return row[0]
    def save_requests(self,identifier,requests,actor,reason="Removido na edição da Petição."):
        """Atomically replace request ordering while preserving each request result."""
        stamp=now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            existing={row['id']:dict(row) for row in c.execute("SELECT * FROM peticoes_pedidos WHERE peticao_id=? AND excluido=0",(identifier,))}
            offset=(c.execute("SELECT COALESCE(MAX(ordem),0) FROM peticoes_pedidos WHERE peticao_id=?",(identifier,)).fetchone()[0] or 0)+10000; c.execute("UPDATE peticoes_pedidos SET ordem=ordem+? WHERE peticao_id=? AND excluido=0",(offset,identifier))
            seen=set()
            for order,item in enumerate(requests,1):
                request_id=item.get('id')
                if request_id in existing:
                    c.execute("UPDATE peticoes_pedidos SET descricao=?,ordem=?,atualizado_em=? WHERE id=?",(item['descricao'],order,stamp,request_id));seen.add(request_id)
                else:c.execute("INSERT INTO peticoes_pedidos(peticao_id,descricao,ordem,criado_em,atualizado_em) VALUES(?,?,?,?,?)",(identifier,item['descricao'],order,stamp,stamp))
            removed = set(existing) - seen
            for request_id in removed:c.execute("UPDATE peticoes_pedidos SET excluido=1,excluido_em=?,excluido_por=?,motivo_exclusao=?,atualizado_em=? WHERE id=?",(stamp,actor,reason,stamp,request_id))
            return list(removed)
    def conclude(self,identifier,result,actor):
        stamp=now()
        with self.store.connection() as c:c.execute("BEGIN IMMEDIATE");c.execute("UPDATE peticoes SET situacao='CONCLUIDA',resultado_global=?,concluida_em=?,atualizado_em=?,atualizado_por=? WHERE id=?",(result,stamp[:10],stamp,actor,identifier))
    def document(self,identifier):
        with self.store.connection(read_only=True) as c:
            row=c.execute("SELECT nome,mime_type,arquivo FROM peticoes_documentos WHERE peticao_id=? ORDER BY criado_em LIMIT 1",(identifier,)).fetchone();return dict(row) if row else None
