-- Version 1: equivalent to SQLite user_version 2, in a private app schema.
-- All dates/payloads remain ISO/JSON TEXT to preserve the existing Store contract.
CREATE TABLE IF NOT EXISTS procuradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL, genero TEXT NOT NULL, cargo_base TEXT NOT NULL,
    funcao TEXT NOT NULL, assento TEXT NOT NULL,
    ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0,1)),
    observacoes TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS funcoes (nome TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS assentos (nome TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS motivos_afastamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL, texto TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS bases_legais (
    funcao TEXT PRIMARY KEY, texto TEXT NOT NULL, nota TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS configuracoes (chave TEXT PRIMARY KEY, valor TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sequencias (
    ano INTEGER PRIMARY KEY CHECK (ano BETWEEN 1000 AND 9999),
    ultimo INTEGER NOT NULL CHECK (ultimo >= 0)
);
CREATE TABLE IF NOT EXISTS sequencia_baselines (
    ano INTEGER PRIMARY KEY, baseline INTEGER NOT NULL CHECK (baseline >= 0)
);
CREATE TABLE IF NOT EXISTS portarias (
    id TEXT PRIMARY KEY, numero INTEGER, ano INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Rascunho','Finalizada','Cancelada')),
    payload TEXT NOT NULL, docx BYTEA, pdf BYTEA, criada TEXT NOT NULL,
    atualizada TEXT NOT NULL, cancelamento TEXT NOT NULL DEFAULT '',
    UNIQUE (ano,numero), CHECK (numero IS NULL OR numero > 0),
    CHECK ((status='Rascunho' AND numero IS NULL) OR
           (status!='Rascunho' AND numero IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS substituicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portaria_id TEXT NOT NULL REFERENCES portarias(id), ordem INTEGER NOT NULL,
    payload TEXT NOT NULL, UNIQUE(portaria_id,ordem)
);
CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instante TEXT NOT NULL, acao TEXT NOT NULL, detalhes TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS backup_snapshots (
    referencia TEXT PRIMARY KEY, criada TEXT NOT NULL,
    conteudo BYTEA NOT NULL, sha256 TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TEXT NOT NULL, acao TEXT NOT NULL,
    portaria_id_original TEXT NOT NULL UNIQUE, numero INTEGER, ano INTEGER NOT NULL,
    status_anterior TEXT NOT NULL, motivo TEXT NOT NULL, dados_resumidos TEXT NOT NULL,
    arquivo_docx TEXT NOT NULL, arquivo_pdf TEXT NOT NULL, backup TEXT NOT NULL,
    sequencia_antes INTEGER NOT NULL, sequencia_depois INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS exportacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portaria_id TEXT NOT NULL REFERENCES portarias(id), caminho TEXT NOT NULL UNIQUE,
    formato TEXT NOT NULL CHECK (formato IN ('docx','pdf')), sha256 TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS exportacoes_portaria_idx ON exportacoes(portaria_id);
CREATE TABLE IF NOT EXISTS audit_arquivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL REFERENCES audit_log(id), caminho TEXT NOT NULL,
    quarentena TEXT NOT NULL DEFAULT '', sha256 TEXT NOT NULL,
    estado TEXT NOT NULL, detalhe TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS audit_arquivos_audit_idx ON audit_arquivos(audit_id);

CREATE OR REPLACE FUNCTION proteger_portaria() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status != 'Rascunho' AND (
            current_setting('mpc.delete_id', true) IS DISTINCT FROM OLD.id OR
            NOT EXISTS (SELECT 1 FROM audit_log a JOIN backup_snapshots b
                ON b.referencia=a.backup WHERE a.portaria_id_original=OLD.id)
        ) THEN
            RAISE EXCEPTION 'Use a exclusão administrativa com backup e confirmação'
                USING ERRCODE='23514';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status != 'Rascunho' AND (
        NEW.numero IS DISTINCT FROM OLD.numero OR NEW.ano IS DISTINCT FROM OLD.ano OR
        NEW.payload IS DISTINCT FROM OLD.payload OR NEW.docx IS DISTINCT FROM OLD.docx OR
        NEW.status='Rascunho' OR (OLD.status='Cancelada' AND NEW.status!='Cancelada')
    ) THEN
        RAISE EXCEPTION 'Conteúdo de ato finalizado é imutável' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
-- The versioned initializer runs this script once, under a transaction lock.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='portarias'::regclass
                   AND tgname='manter_portaria') THEN
        CREATE TRIGGER manter_portaria BEFORE DELETE OR UPDATE ON portarias
            FOR EACH ROW EXECUTE FUNCTION proteger_portaria();
    END IF;
END;
$$;
