-- Version 1: equivalent to SQLite user_version 2, in a private app schema.
-- All dates/payloads remain ISO/JSON TEXT to preserve the existing Store contract.
CREATE TABLE IF NOT EXISTS procuradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL, genero TEXT NOT NULL, cargo_base TEXT NOT NULL,
    funcao TEXT NOT NULL, assento TEXT NOT NULL,
    ativo INTEGER NOT NULL DEFAULT 1 CHECK (ativo IN (0,1)),
    observacoes TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS funcoes (nome TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS assentos (nome TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS motivos_afastamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL, texto TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS bases_legais (
    funcao TEXT PRIMARY KEY, texto TEXT NOT NULL, nota TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS configuracoes (chave TEXT PRIMARY KEY, valor TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sequencias (
    ano INTEGER PRIMARY KEY CHECK (ano BETWEEN 1000 AND 9999),
    ultimo INTEGER NOT NULL CHECK (ultimo >= 0)
);
CREATE TABLE IF NOT EXISTS sequencia_baselines (
    ano INTEGER PRIMARY KEY, baseline INTEGER NOT NULL CHECK (baseline >= 0)
);
CREATE TABLE IF NOT EXISTS portarias (
    id TEXT PRIMARY KEY, numero INTEGER, ano INTEGER NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('Rascunho','Finalizada','Cancelada')),
    payload TEXT NOT NULL, docx BYTEA, pdf BYTEA, criada TEXT NOT NULL,
    atualizada TEXT NOT NULL, cancelamento TEXT NOT NULL DEFAULT '',
    UNIQUE (ano,numero), CHECK (numero IS NULL OR numero > 0),
    CHECK ((status='Rascunho' AND numero IS NULL) OR
           (status!='Rascunho' AND numero IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS substituicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portaria_id TEXT NOT NULL REFERENCES portarias(id), ordem INTEGER NOT NULL,
    payload TEXT NOT NULL, UNIQUE(portaria_id,ordem)
);
CREATE TABLE IF NOT EXISTS eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instante TEXT NOT NULL, acao TEXT NOT NULL, detalhes TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS backup_snapshots (
    referencia TEXT PRIMARY KEY, criada TEXT NOT NULL,
    conteudo BYTEA NOT NULL, sha256 TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_hora TEXT NOT NULL, acao TEXT NOT NULL,
    portaria_id_original TEXT NOT NULL UNIQUE, numero INTEGER, ano INTEGER NOT NULL,
    status_anterior TEXT NOT NULL, motivo TEXT NOT NULL, dados_resumidos TEXT NOT NULL,
    arquivo_docx TEXT NOT NULL, arquivo_pdf TEXT NOT NULL, backup TEXT NOT NULL,
    sequencia_antes INTEGER NOT NULL, sequencia_depois INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS exportacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portaria_id TEXT NOT NULL REFERENCES portarias(id), caminho TEXT NOT NULL UNIQUE,
    formato TEXT NOT NULL CHECK (formato IN ('docx','pdf')), sha256 TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS exportacoes_portaria_idx ON exportacoes(portaria_id);
CREATE TABLE IF NOT EXISTS audit_arquivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id BIGINT NOT NULL REFERENCES audit_log(id), caminho TEXT NOT NULL,
    quarentena TEXT NOT NULL DEFAULT '', sha256 TEXT NOT NULL,
    estado TEXT NOT NULL, detalhe TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS audit_arquivos_audit_idx ON audit_arquivos(audit_id);

CREATE TABLE IF NOT EXISTS servidores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL, nome_normalizado TEXT NOT NULL,
    matricula_original TEXT NOT NULL DEFAULT '',
    matricula_normalizada TEXT, cargo TEXT NOT NULL DEFAULT '',
    setor TEXT NOT NULL DEFAULT '', genero TEXT,
    ativo INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS servidores_importacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_email TEXT NOT NULL, arquivo_nome TEXT NOT NULL, arquivo_hash TEXT NOT NULL,
    processado_em TEXT NOT NULL, total_processado INTEGER NOT NULL,
    incluidos INTEGER NOT NULL, atualizados INTEGER NOT NULL, inconsistentes INTEGER NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS servidores_matricula_unica
    ON servidores(matricula_normalizada) WHERE matricula_normalizada IS NOT NULL;
CREATE INDEX IF NOT EXISTS servidores_pesquisa_idx
    ON servidores(nome_normalizado, matricula_normalizada);
CREATE TABLE IF NOT EXISTS memorandos (
    id TEXT PRIMARY KEY, tipo TEXT NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('RASCUNHO','FINALIZADO','CANCELADO')),
    criado_por TEXT NOT NULL, criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL,
    finalizado_em TEXT, numero_oficial TEXT NOT NULL DEFAULT '', payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS memorandos_substituicao (
    memorando_id TEXT PRIMARY KEY REFERENCES memorandos(id) ON DELETE CASCADE,
    data_inicio TEXT NOT NULL, data_fim TEXT NOT NULL,
    gabinete_procurador_id BIGINT REFERENCES procuradores(id),
    gabinete_snapshot TEXT NOT NULL, natureza_funcao TEXT NOT NULL,
    motivo TEXT NOT NULL, motivo_texto TEXT NOT NULL,
    signatario_id BIGINT REFERENCES procuradores(id),
    signatario_nome TEXT NOT NULL, signatario_cargo TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS memorandos_substituicao_etapas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memorando_id TEXT NOT NULL REFERENCES memorandos(id) ON DELETE CASCADE,
    ordem INTEGER NOT NULL,
    substituido_servidor_id BIGINT REFERENCES servidores(id),
    substituido_snapshot TEXT NOT NULL,
    substituto_servidor_id BIGINT REFERENCES servidores(id),
    substituto_snapshot TEXT NOT NULL,
    UNIQUE(memorando_id, ordem)
);
CREATE TABLE IF NOT EXISTS memorandos_arquivos (
    id TEXT PRIMARY KEY,
    memorando_id TEXT NOT NULL REFERENCES memorandos(id) ON DELETE CASCADE,
    nome TEXT NOT NULL, tipo TEXT NOT NULL, tamanho INTEGER NOT NULL,
    sha256 TEXT NOT NULL, criado_em TEXT NOT NULL, conteudo BYTEA NOT NULL
);
CREATE INDEX IF NOT EXISTS memorandos_lista_idx ON memorandos(status, atualizado_em DESC);
CREATE INDEX IF NOT EXISTS memorandos_etapas_idx ON memorandos_substituicao_etapas(memorando_id, ordem);

CREATE TABLE IF NOT EXISTS usuarios_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    perfil TEXT NOT NULL CHECK(perfil IN ('ADMINISTRADOR','USUARIO')),
    ativo INTEGER NOT NULL DEFAULT 1 CHECK(ativo IN (0,1)),
    pode_portarias INTEGER NOT NULL DEFAULT 0 CHECK(pode_portarias IN (0,1)),
    pode_agenda INTEGER NOT NULL DEFAULT 0 CHECK(pode_agenda IN (0,1)),
    pode_oficios INTEGER NOT NULL DEFAULT 0 CHECK(pode_oficios IN (0,1)),
    pode_memorandos INTEGER NOT NULL DEFAULT 0 CHECK(pode_memorandos IN (0,1)),
    pode_admin INTEGER NOT NULL DEFAULT 0 CHECK(pode_admin IN (0,1)),
    protegido INTEGER NOT NULL DEFAULT 0 CHECK(protegido IN (0,1)),
    criado_em TEXT NOT NULL,
    atualizado_em TEXT NOT NULL
);

CREATE OR REPLACE FUNCTION proteger_portaria() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status != 'Rascunho' AND (
            current_setting('mpc.delete_id', true) IS DISTINCT FROM OLD.id OR
            NOT EXISTS (SELECT 1 FROM audit_log a JOIN backup_snapshots b
                ON b.referencia=a.backup WHERE a.portaria_id_original=OLD.id)
        ) THEN
            RAISE EXCEPTION 'Use a exclusão administrativa com backup e confirmação'
                USING ERRCODE='23514';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status != 'Rascunho' AND (
        NEW.numero IS DISTINCT FROM OLD.numero OR NEW.ano IS DISTINCT FROM OLD.ano OR
        NEW.payload IS DISTINCT FROM OLD.payload OR NEW.docx IS DISTINCT FROM OLD.docx OR
        NEW.status='Rascunho' OR (OLD.status='Cancelada' AND NEW.status!='Cancelada')
    ) THEN
        RAISE EXCEPTION 'Conteúdo de ato finalizado é imutável' USING ERRCODE='23514';
    END IF;
    RETURN NEW;
END;
$$;
CREATE TABLE IF NOT EXISTS auditoria_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    usuario_email TEXT NOT NULL DEFAULT '',
    usuario_nome TEXT NOT NULL DEFAULT '',
    sessao_id TEXT,
    evento TEXT NOT NULL,
    modulo TEXT NOT NULL DEFAULT '',
    acao TEXT NOT NULL DEFAULT '',
    entidade_tipo TEXT,
    entidade_id TEXT,
    resultado TEXT NOT NULL DEFAULT 'OK',
    detalhes_json TEXT,
    criado_em TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS auditoria_eventos_criado_em_idx
    ON auditoria_eventos(criado_em DESC, id DESC);
CREATE INDEX IF NOT EXISTS auditoria_eventos_usuario_id_idx ON auditoria_eventos(usuario_id);
CREATE INDEX IF NOT EXISTS auditoria_eventos_usuario_email_idx ON auditoria_eventos(usuario_email);
CREATE INDEX IF NOT EXISTS auditoria_eventos_modulo_idx ON auditoria_eventos(modulo);
CREATE INDEX IF NOT EXISTS auditoria_eventos_evento_idx ON auditoria_eventos(evento);
CREATE INDEX IF NOT EXISTS auditoria_eventos_acao_idx ON auditoria_eventos(acao);
CREATE INDEX IF NOT EXISTS auditoria_eventos_resultado_idx ON auditoria_eventos(resultado);
CREATE INDEX IF NOT EXISTS auditoria_eventos_sessao_idx ON auditoria_eventos(sessao_id);

CREATE TABLE IF NOT EXISTS tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL, titulo TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '',
    categoria TEXT NOT NULL DEFAULT '', prioridade TEXT NOT NULL DEFAULT 'NORMAL'
      CHECK(prioridade IN ('BAIXA','NORMAL','ALTA','URGENTE')),
    status TEXT NOT NULL DEFAULT 'A_FAZER'
      CHECK(status IN ('A_FAZER','EM_ANDAMENTO','AGUARDANDO','CONCLUIDA','CANCELADA')),
    prazo_data TEXT, prazo_hora TEXT, lembrete_em TEXT, observacoes TEXT NOT NULL DEFAULT '',
    criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL, concluido_em TEXT, cancelado_em TEXT
);
CREATE TABLE IF NOT EXISTS tarefas_checklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tarefa_id BIGINT NOT NULL REFERENCES tarefas(id) ON DELETE CASCADE,
    texto TEXT NOT NULL, concluido INTEGER NOT NULL DEFAULT 0 CHECK(concluido IN (0,1)),
    ordem INTEGER NOT NULL, criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS tarefas_lembretes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tarefa_id BIGINT NOT NULL REFERENCES tarefas(id) ON DELETE CASCADE,
    lembrar_em TEXT NOT NULL, criado_em TEXT NOT NULL,
    UNIQUE(tarefa_id, lembrar_em)
);
CREATE INDEX IF NOT EXISTS tarefas_owner_status_prazo_idx ON tarefas(owner_user_id,status,prazo_data);
CREATE INDEX IF NOT EXISTS tarefas_owner_prioridade_idx ON tarefas(owner_user_id,prioridade);
CREATE INDEX IF NOT EXISTS tarefas_checklist_tarefa_idx ON tarefas_checklist(tarefa_id,ordem);
CREATE INDEX IF NOT EXISTS tarefas_lembretes_tarefa_momento_idx ON tarefas_lembretes(tarefa_id,lembrar_em);

-- Relatórios Tramita: imports are immutable file snapshots; operational rows are additive.
CREATE TABLE IF NOT EXISTS tramita_importacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL CHECK(tipo IN ('ENTRADAS','SAIDAS','ESTOQUE')),
    competencia TEXT, data_snapshot TEXT, nome_arquivo TEXT NOT NULL,
    hash_arquivo TEXT NOT NULL UNIQUE, quantidade_registros INTEGER NOT NULL,
    importado_em TEXT NOT NULL, importado_por TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'CONCLUIDA'
);
CREATE TABLE IF NOT EXISTS tramita_movimentacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    importacao_id BIGINT NOT NULL REFERENCES tramita_importacoes(id),
    competencia TEXT NOT NULL, tipo_movimentacao TEXT NOT NULL CHECK(tipo_movimentacao IN ('ENTRADA','SAIDA')),
    protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '', origem TEXT NOT NULL DEFAULT '',
    data_realizacao TEXT, procurador TEXT NOT NULL DEFAULT '', motivo_distribuicao TEXT NOT NULL DEFAULT '',
    data_devolucao TEXT, motivo_devolucao TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS tramita_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    importacao_id BIGINT NOT NULL REFERENCES tramita_importacoes(id), data_snapshot TEXT NOT NULL,
    protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', digital TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '',
    jurisdicionado TEXT NOT NULL DEFAULT '', fase TEXT NOT NULL DEFAULT '', procurador TEXT NOT NULL DEFAULT '',
    dias_com_procurador DOUBLE PRECISION, assistente TEXT NOT NULL DEFAULT '', dias_com_assistente DOUBLE PRECISION,
    dias_no_mpc DOUBLE PRECISION, prescricao TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS tramita_movimentacoes_competencia_idx ON tramita_movimentacoes(competencia, tipo_movimentacao);
CREATE INDEX IF NOT EXISTS tramita_estoque_snapshot_idx ON tramita_estoque(data_snapshot);
CREATE INDEX IF NOT EXISTS tramita_movimentacoes_pagina_idx ON tramita_movimentacoes(competencia,procurador,protocolo,id);
CREATE INDEX IF NOT EXISTS tramita_estoque_procurador_idx ON tramita_estoque(data_snapshot,procurador);

-- Agenda leave is intentionally independent from agenda_compromissos.
CREATE TABLE IF NOT EXISTS agenda_afastamentos (
    id TEXT PRIMARY KEY,
    procurador_id BIGINT NOT NULL REFERENCES procuradores(id),
    motivo TEXT NOT NULL,
    motivo_outro TEXT,
    data_inicio TEXT NOT NULL,
    data_fim TEXT NOT NULL,
    substituto_id BIGINT REFERENCES procuradores(id),
    observacao TEXT,
    cancelado INTEGER NOT NULL DEFAULT 0 CHECK(cancelado IN (0,1)),
    criado_por TEXT,
    criado_em TEXT NOT NULL,
    atualizado_em TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS agenda_afastamentos_procurador_idx
    ON agenda_afastamentos(procurador_id, data_inicio, data_fim);
CREATE INDEX IF NOT EXISTS agenda_afastamentos_periodo_idx
    ON agenda_afastamentos(data_inicio, data_fim);
CREATE TABLE IF NOT EXISTS agenda_afastamentos_viagens (
    afastamento_id TEXT PRIMARY KEY REFERENCES agenda_afastamentos(id) ON DELETE CASCADE,
    aeroporto TEXT NOT NULL, aeroporto_outro TEXT, ida_data TEXT, ida_hora TEXT,
    aeroporto_ida TEXT, aeroporto_ida_outro TEXT, aeroporto_volta TEXT, aeroporto_volta_outro TEXT,
    ida_companhia TEXT, ida_voo TEXT, ida_motorista_hora TEXT,
    volta_data TEXT, volta_chegada_hora TEXT, volta_companhia TEXT, volta_voo TEXT,
    volta_motorista_hora TEXT, motorista_informado INTEGER NOT NULL DEFAULT 0,
    informado_em TEXT, informado_por TEXT, observacao TEXT,
    criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS agenda_viagens_ida_idx ON agenda_afastamentos_viagens(ida_data);
CREATE INDEX IF NOT EXISTS agenda_viagens_volta_idx ON agenda_afastamentos_viagens(volta_data);

-- Additive institutional air-travel logistics.  Legacy leave trips above are
-- intentionally retained for existing databases, but are no longer used by UI.
CREATE TABLE IF NOT EXISTS agenda_compromissos (
    id TEXT PRIMARY KEY, tipo TEXT NOT NULL, inicio TEXT NOT NULL, fim TEXT,
    situacao TEXT NOT NULL, payload TEXT NOT NULL, criada TEXT NOT NULL, atualizada TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS agenda_compromisso_procuradores (
    compromisso_id TEXT NOT NULL REFERENCES agenda_compromissos(id) ON DELETE CASCADE,
    procurador_id BIGINT NOT NULL REFERENCES procuradores(id),
    PRIMARY KEY(compromisso_id, procurador_id)
);
CREATE TABLE IF NOT EXISTS agenda_compromissos_viagens (
    id TEXT PRIMARY KEY,
    compromisso_id TEXT NOT NULL REFERENCES agenda_compromissos(id) ON DELETE CASCADE,
    procurador_id BIGINT NOT NULL REFERENCES procuradores(id),
    aeroporto_ida TEXT, aeroporto_ida_outro TEXT, ida_data TEXT, ida_hora TEXT,
    ida_motorista_hora TEXT, aeroporto_volta TEXT, aeroporto_volta_outro TEXT,
    volta_data TEXT, volta_chegada_hora TEXT, volta_motorista_hora TEXT,
    motorista_informado INTEGER NOT NULL DEFAULT 0 CHECK(motorista_informado IN (0,1)),
    informado_em TEXT, informado_por TEXT, observacao TEXT,
    criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL,
    UNIQUE(compromisso_id, procurador_id)
);
CREATE INDEX IF NOT EXISTS agenda_compromissos_viagens_ida_idx ON agenda_compromissos_viagens(ida_data);
CREATE INDEX IF NOT EXISTS agenda_compromissos_viagens_volta_idx ON agenda_compromissos_viagens(volta_data);

-- The versioned initializer runs this script once, under a transaction lock.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid='portarias'::regclass
                   AND tgname='manter_portaria') THEN
        CREATE TRIGGER manter_portaria BEFORE DELETE OR UPDATE ON portarias
            FOR EACH ROW EXECUTE FUNCTION proteger_portaria();
    END IF;
END;
$$;
