"""Vínculos leves de lembretes, acompanhamento e avisos por registro."""

from datetime import datetime, timedelta, timezone

from database.store import now, schema_key_of, unwrap_store

MARKER = "record_engagement_schema_v1"
_READY = set()
ORIGIN_MODULES = frozenset(
    {"oficio_enviado", "oficio_recebido", "memorando", "representacao", "ouvidoria"}
)


class RecordEngagementStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        with self.store.connection(read_only=True) as c:
            marker = c.execute(
                "SELECT 1 FROM configuracoes WHERE chave=?", (MARKER,)
            ).fetchone()
            if self.store.backend == "postgresql":
                tables = {
                    row[0]
                    for row in c.execute(
                        "SELECT table_name FROM information_schema.tables "
                        "WHERE table_schema=current_schema() AND table_name IN "
                        "('registros_seguidos','avisos_usuario')"
                    )
                }
            else:
                tables = {
                    row[0]
                    for row in c.execute(
                        "SELECT name FROM sqlite_master WHERE type='table' AND name IN "
                        "('registros_seguidos','avisos_usuario')"
                    )
                }
            index_ready = self._reminder_index_ready(c)
        if (
            marker
            and tables == {"registros_seguidos", "avisos_usuario"}
            and index_ready
        ):
            _READY.add(key)
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        user_type = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS registros_seguidos (id {identity},"
                f"usuario_id {user_type} NOT NULL REFERENCES usuarios_acesso(id) ON DELETE CASCADE,"
                "origem_modulo TEXT NOT NULL,origem_id TEXT NOT NULL,criado_em TEXT NOT NULL,"
                "UNIQUE(usuario_id,origem_modulo,origem_id))"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS avisos_usuario (id {identity},"
                f"usuario_id {user_type} NOT NULL REFERENCES usuarios_acesso(id) ON DELETE CASCADE,"
                "tipo TEXT NOT NULL CHECK(tipo IN ('LEMBRETE','ATUALIZACAO')) ,"
                "origem_modulo TEXT NOT NULL,origem_id TEXT NOT NULL,texto TEXT NOT NULL DEFAULT '',"
                "lembrar_em TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDENTE' "
                "CHECK(status IN ('PENDENTE','CONCLUIDO')),chave_evento TEXT,"
                "criado_em TEXT NOT NULL,atualizado_em TEXT NOT NULL,"
                "UNIQUE(usuario_id,chave_evento))"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS registros_seguidos_origem_idx "
                "ON registros_seguidos(origem_modulo,origem_id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS avisos_usuario_pendentes_idx "
                "ON avisos_usuario(usuario_id,status,lembrar_em)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS avisos_usuario_origem_idx "
                "ON avisos_usuario(origem_modulo,origem_id)"
            )
            c.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS avisos_lembrete_ativo_idx "
                "ON avisos_usuario(usuario_id,origem_modulo,origem_id,lembrar_em) "
                "WHERE tipo='LEMBRETE' AND status='PENDENTE'"
            )
            c.execute(
                "INSERT INTO configuracoes(chave,valor) VALUES(?,?) "
                "ON CONFLICT(chave) DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def _reminder_index_ready(self, connection):
        if self.store.backend == "postgresql":
            row = connection.execute(
                "SELECT 1 FROM pg_indexes WHERE schemaname=current_schema() "
                "AND indexname='avisos_lembrete_ativo_idx'"
            ).fetchone()
        else:
            row = connection.execute(
                "SELECT 1 FROM sqlite_master WHERE type='index' "
                "AND name='avisos_lembrete_ativo_idx'"
            ).fetchone()
        return bool(row)

    @staticmethod
    def _module(module, *, allow_task=False):
        allowed = ORIGIN_MODULES | ({"tarefa"} if allow_task else set())
        if module not in allowed:
            raise ValueError("Módulo de origem inválido.")
        return module

    def authorize_origin(self, module, identifier, user_id):
        self._module(module, allow_task=True)
        if module == "tarefa":
            from database.tarefas import TarefasStore

            row = TarefasStore(self.store).get(identifier, user_id)
            if not row:
                raise ValueError("Acesso não autorizado a este registro.")
            return row
        from database.internal_collaboration import InternalCollaborationStore

        return InternalCollaborationStore(self.store).authorize_origin(
            module, identifier, user_id
        )

    def is_following(self, user_id, module, identifier):
        self._module(module)
        with self.store.connection(read_only=True) as c:
            return bool(
                c.execute(
                    "SELECT 1 FROM registros_seguidos WHERE usuario_id=? "
                    "AND origem_modulo=? AND origem_id=?",
                    (user_id, module, str(identifier)),
                ).fetchone()
            )

    def follow(self, user_id, module, identifier):
        self._module(module)
        self.authorize_origin(module, identifier, user_id)
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            inserted = c.execute(
                "INSERT INTO registros_seguidos(usuario_id,origem_modulo,origem_id,criado_em) "
                "VALUES(?,?,?,?) ON CONFLICT(usuario_id,origem_modulo,origem_id) DO NOTHING",
                (user_id, module, str(identifier), now()),
            )
            return getattr(inserted, "rowcount", 1) != 0

    def unfollow(self, user_id, module, identifier):
        self._module(module)
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            deleted = c.execute(
                "DELETE FROM registros_seguidos WHERE usuario_id=? AND origem_modulo=? AND origem_id=?",
                (user_id, module, str(identifier)),
            )
            return getattr(deleted, "rowcount", 0) != 0

    def create_reminder(self, user_id, module, identifier, remind_at, text=""):
        self._module(module, allow_task=True)
        self.authorize_origin(module, identifier, user_id)
        try:
            moment = datetime.fromisoformat(str(remind_at))
        except (TypeError, ValueError):
            raise ValueError("Informe uma data válida para o lembrete.") from None
        if moment.tzinfo is None:
            raise ValueError("O lembrete precisa de data e fuso horário válidos.")
        text = (text or "").strip()
        if len(text) > 300:
            raise ValueError("O texto do lembrete deve ter até 300 caracteres.")
        stamp = now()
        moment_key = moment.astimezone(timezone.utc).isoformat()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            inserted = c.execute(
                "INSERT INTO avisos_usuario(usuario_id,tipo,origem_modulo,origem_id,texto,"
                "lembrar_em,status,chave_evento,criado_em,atualizado_em) "
                "VALUES(?,'LEMBRETE',?,?,?,?, 'PENDENTE',NULL,?,?) "
                "ON CONFLICT(usuario_id,origem_modulo,origem_id,lembrar_em) "
                "WHERE tipo='LEMBRETE' AND status='PENDENTE' DO NOTHING",
                (
                    user_id,
                    module,
                    str(identifier),
                    text,
                    moment_key,
                    stamp,
                    stamp,
                ),
            )
            if getattr(inserted, "rowcount", 0):
                return inserted.lastrowid
            existing = c.execute(
                "SELECT id FROM avisos_usuario WHERE usuario_id=? AND tipo='LEMBRETE' "
                "AND origem_modulo=? AND origem_id=? AND lembrar_em=? AND status='PENDENTE'",
                (user_id, module, str(identifier), moment_key),
            ).fetchone()
            if not existing:
                raise ValueError("Não foi possível gravar o lembrete.")
            return existing["id"]

    def list_origin_reminders(self, user_id, module, identifier):
        self.authorize_origin(module, identifier, user_id)
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    "SELECT id,texto,lembrar_em,status FROM avisos_usuario "
                    "WHERE usuario_id=? AND tipo='LEMBRETE' AND origem_modulo=? AND origem_id=? "
                    "ORDER BY lembrar_em,id LIMIT 100",
                    (user_id, module, str(identifier)),
                )
            ]

    def reschedule(self, reminder_id, user_id, remind_at):
        try:
            moment = datetime.fromisoformat(str(remind_at))
        except (TypeError, ValueError):
            raise ValueError("Informe uma data válida para o lembrete.") from None
        if moment.tzinfo is None:
            raise ValueError("O lembrete precisa de data e fuso horário válidos.")
        moment_key = moment.astimezone(timezone.utc).isoformat()
        try:
            with self.store.connection() as c:
                c.execute("BEGIN IMMEDIATE")
                updated = c.execute(
                    "UPDATE avisos_usuario SET lembrar_em=?,status='PENDENTE',atualizado_em=? "
                    "WHERE id=? AND usuario_id=? AND tipo='LEMBRETE'",
                    (moment_key, now(), reminder_id, user_id),
                )
                if getattr(updated, "rowcount", 0) == 0:
                    raise ValueError("Lembrete não encontrado.")
        except Exception as exc:
            if type(exc).__name__ in {"IntegrityError", "UniqueViolation"}:
                raise ValueError(
                    "Já existe um lembrete pendente nesse horário."
                ) from None
            raise

    def remind_tomorrow(self, reminder_id, user_id, reference=None):
        reference = reference or datetime.now().astimezone()
        return self.reschedule(reminder_id, user_id, reference + timedelta(days=1))

    def conclude(self, notice_id, user_id):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            updated = c.execute(
                "UPDATE avisos_usuario SET status='CONCLUIDO',atualizado_em=? "
                "WHERE id=? AND usuario_id=? AND status='PENDENTE'",
                (now(), notice_id, user_id),
            )
            if getattr(updated, "rowcount", 0) == 0:
                raise ValueError("Aviso não encontrado.")

    def due(self, user_id, moment=None, limit=100):
        moment = (moment or datetime.now().astimezone()).astimezone(timezone.utc)
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    "SELECT id,tipo,origem_modulo,origem_id,texto,lembrar_em,criado_em "
                    "FROM avisos_usuario WHERE usuario_id=? AND status='PENDENTE' "
                    "AND lembrar_em<=? ORDER BY lembrar_em,id LIMIT ?",
                    (user_id, moment.isoformat(), limit),
                )
            ]

    def emit(self, module, identifier, actor_id, event_key, text):
        """Insert one compact notice per follower; one logical key is idempotent."""
        self._module(module)
        key = (event_key or "").strip()
        if not key:
            raise ValueError("Informe a chave lógica do evento.")
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            inserted = c.execute(
                "INSERT INTO avisos_usuario(usuario_id,tipo,origem_modulo,origem_id,texto,"
                "lembrar_em,status,chave_evento,criado_em,atualizado_em) "
                "SELECT usuario_id,'ATUALIZACAO',origem_modulo,origem_id,?,?,'PENDENTE',?,?,? "
                "FROM registros_seguidos WHERE origem_modulo=? AND origem_id=? AND usuario_id<>? "
                "ON CONFLICT(usuario_id,chave_evento) DO NOTHING",
                (
                    (text or "Atualização relevante no registro.")[:300],
                    stamp,
                    key,
                    stamp,
                    stamp,
                    module,
                    str(identifier),
                    actor_id if actor_id is not None else -1,
                ),
            )
        return max(0, getattr(inserted, "rowcount", 0))

    @staticmethod
    def detach_origin(connection, module, identifier):
        connection.execute(
            "DELETE FROM registros_seguidos WHERE origem_modulo=? AND origem_id=?",
            (module, str(identifier)),
        )
        connection.execute(
            "UPDATE avisos_usuario SET status='CONCLUIDO',atualizado_em=? "
            "WHERE origem_modulo=? AND origem_id=? AND status='PENDENTE'",
            (now(), module, str(identifier)),
        )


def ensure_schema(store):
    RecordEngagementStore(store)
