"""Additive Representações schema. Listing never selects document bytes."""

import uuid

from database.store import now, schema_key_of, unwrap_store

MARKER = "representacoes_schema_v1"
_READY = set()
COLUMNS = (
    "id,titulo,objeto,origem,data_abertura,representado,tema,prioridade,"
    "situacao,fase_processual,numero_processo,data_protocolo,relator,"
    "possui_medida_cautelar,observacoes,criado_em,criado_por,atualizado_em,atualizado_por"
)
MEMBER_COLUMNS = "id,representacao_id,membro_tipo,membro_id,papel,criado_em"
PROGRESS_COLUMNS = "id,representacao_id,data,tipo,descricao,criado_em,criado_por"
DOCUMENT_META = (
    "id,representacao_id,andamento_id,tipo_documento,descricao,data_documento,"
    "nome_arquivo,mime_type,tamanho,criado_em,criado_por"
)


class RepresentacoesStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        binary = "BYTEA" if self.store.backend == "postgresql" else "BLOB"
        fk = "BIGINT" if self.store.backend == "postgresql" else "INTEGER"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS representacoes ("
                f"id {identity},"
                "titulo TEXT NOT NULL,"
                "objeto TEXT NOT NULL DEFAULT '',"
                "origem TEXT NOT NULL,"
                "data_abertura TEXT NOT NULL,"
                "representado TEXT NOT NULL DEFAULT '',"
                "tema TEXT NOT NULL DEFAULT '',"
                "prioridade TEXT NOT NULL DEFAULT 'NORMAL',"
                "situacao TEXT NOT NULL,"
                "fase_processual TEXT,"
                "numero_processo TEXT,"
                "data_protocolo TEXT,"
                "relator TEXT,"
                "possui_medida_cautelar INTEGER NOT NULL DEFAULT 0 CHECK(possui_medida_cautelar IN (0,1)),"
                "observacoes TEXT NOT NULL DEFAULT '',"
                "criado_em TEXT NOT NULL,"
                "criado_por TEXT NOT NULL,"
                "atualizado_em TEXT NOT NULL,"
                "atualizado_por TEXT NOT NULL)"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS representacao_integrantes ("
                f"id {identity},"
                f"representacao_id {fk} NOT NULL REFERENCES representacoes(id) ON DELETE CASCADE,"
                "membro_tipo TEXT NOT NULL CHECK(membro_tipo IN ('PROCURADOR','SERVIDOR')),"
                f"membro_id {fk} NOT NULL,"
                "papel TEXT NOT NULL,"
                "criado_em TEXT NOT NULL,"
                "UNIQUE(representacao_id,membro_tipo,membro_id,papel))"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS representacao_andamentos ("
                f"id {identity},"
                f"representacao_id {fk} NOT NULL REFERENCES representacoes(id) ON DELETE CASCADE,"
                "data TEXT NOT NULL,"
                "tipo TEXT NOT NULL,"
                "descricao TEXT NOT NULL DEFAULT '',"
                "criado_em TEXT NOT NULL,"
                "criado_por TEXT NOT NULL)"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS representacao_documentos ("
                f"id TEXT PRIMARY KEY,"
                f"representacao_id {fk} NOT NULL REFERENCES representacoes(id) ON DELETE CASCADE,"
                f"andamento_id {fk} REFERENCES representacao_andamentos(id) ON DELETE SET NULL,"
                "tipo_documento TEXT NOT NULL,"
                "descricao TEXT NOT NULL DEFAULT '',"
                "data_documento TEXT,"
                "nome_arquivo TEXT NOT NULL,"
                "mime_type TEXT NOT NULL,"
                "tamanho INTEGER NOT NULL,"
                f"arquivo {binary} NOT NULL,"
                "criado_em TEXT NOT NULL,"
                "criado_por TEXT NOT NULL)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS representacoes_situacao_idx "
                "ON representacoes(situacao, data_abertura DESC, id DESC)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS representacoes_fase_idx "
                "ON representacoes(fase_processual)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS representacoes_processo_idx "
                "ON representacoes(numero_processo)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS representacao_integrantes_rep_idx "
                "ON representacao_integrantes(representacao_id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS representacao_andamentos_rep_idx "
                "ON representacao_andamentos(representacao_id, data DESC, id DESC)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS representacao_documentos_rep_idx "
                "ON representacao_documentos(representacao_id, criado_em DESC)"
            )
            if self.store.backend == "postgresql":
                existing = {
                    r[0]
                    for r in c.execute(
                        "SELECT column_name FROM information_schema.columns "
                        "WHERE table_schema=current_schema() AND table_name='representacoes'"
                    )
                }
            else:
                existing = {r[1] for r in c.execute("PRAGMA table_info(representacoes)")}
            if "possui_medida_cautelar" not in existing:
                c.execute(
                    "ALTER TABLE representacoes ADD COLUMN possui_medida_cautelar "
                    "INTEGER NOT NULL DEFAULT 0"
                )
            c.execute(
                "INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO NOTHING",
                (MARKER, "1"),
            )
        _READY.add(key)

    def create(self, record, members, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            inserted = c.execute(
                "INSERT INTO representacoes(titulo,objeto,origem,data_abertura,"
                "representado,tema,prioridade,situacao,fase_processual,numero_processo,"
                "data_protocolo,relator,observacoes,criado_em,criado_por,atualizado_em,"
                "atualizado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    record["titulo"],
                    record.get("objeto") or "",
                    record["origem"],
                    record["data_abertura"],
                    record.get("representado") or "",
                    record.get("tema") or "",
                    record["prioridade"],
                    record["situacao"],
                    record.get("fase_processual"),
                    None,
                    None,
                    None,
                    record.get("observacoes") or "",
                    stamp,
                    actor,
                    stamp,
                    actor,
                ),
            )
            identifier = inserted.lastrowid
            self._replace_members(c, identifier, members, stamp)
            self._add_progress(
                c,
                identifier,
                record["data_abertura"],
                "CRIADA",
                "",
                stamp,
                actor,
            )
        return self.get(identifier)

    def update(self, identifier, record, members, actor):
        current = self.get(identifier)
        if current is None:
            raise ValueError("Representação não encontrada.")
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                "UPDATE representacoes SET titulo=?,objeto=?,origem=?,data_abertura=?,"
                "representado=?,tema=?,prioridade=?,observacoes=?,atualizado_em=?,"
                "atualizado_por=? WHERE id=?",
                (
                    record["titulo"],
                    record.get("objeto") or "",
                    record["origem"],
                    record["data_abertura"],
                    record.get("representado") or "",
                    record.get("tema") or "",
                    record["prioridade"],
                    record.get("observacoes") or "",
                    stamp,
                    actor,
                    identifier,
                ),
            )
            self._replace_members(c, identifier, members, stamp)
        return self.get(identifier)

    def set_status(self, identifier, situacao, fase, actor, note=""):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                "UPDATE representacoes SET situacao=?,fase_processual=?,atualizado_em=?,"
                "atualizado_por=? WHERE id=?",
                (situacao, fase, stamp, actor, identifier),
            )
            if note:
                self._add_progress(
                    c, identifier, stamp[:10], "SITUACAO", note, stamp, actor
                )
        return self.get(identifier)

    def register_protocol(self, identifier, payload, actor, upload=None):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            row = c.execute(
                f"SELECT {COLUMNS} FROM representacoes WHERE id=?", (identifier,)
            ).fetchone()
            if not row:
                raise ValueError("Representação não encontrada.")
            if row["numero_processo"]:
                raise ValueError("Esta representação já possui protocolo.")
            c.execute(
                "UPDATE representacoes SET numero_processo=?,data_protocolo=?,relator=?,"
                "possui_medida_cautelar=?,situacao=?,fase_processual=?,atualizado_em=?,"
                "atualizado_por=? WHERE id=?",
                (
                    payload["numero_processo"],
                    payload["data_protocolo"],
                    payload["relator"],
                    1 if payload.get("possui_medida_cautelar") else 0,
                    "PROTOCOLADA",
                    payload.get("fase_processual") or "INSTRUCAO",
                    stamp,
                    actor,
                    identifier,
                ),
            )
            self._add_progress(
                c,
                identifier,
                payload["data_protocolo"],
                "PROTOCOLADA",
                "Representação protocolada. Processo "
                + payload["numero_processo"]
                + ". Relator: "
                + payload["relator"]
                + ".",
                stamp,
                actor,
            )
            if upload:
                name, mime, content = upload
                c.execute(
                    "INSERT INTO representacao_documentos(id,representacao_id,andamento_id,"
                    "tipo_documento,descricao,data_documento,nome_arquivo,mime_type,tamanho,"
                    "arquivo,criado_em,criado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",
                    (
                        uuid.uuid4().hex,
                        identifier,
                        None,
                        "REPRESENTACAO_FINAL",
                        payload.get("observacao") or "PDF final da Representação",
                        payload["data_protocolo"],
                        name,
                        mime,
                        len(content),
                        content,
                        stamp,
                        actor,
                    ),
                )
        return self.get(identifier)

    def add_progress(self, identifier, data, tipo, descricao, actor):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if not c.execute(
                "SELECT id FROM representacoes WHERE id=?", (identifier,)
            ).fetchone():
                raise ValueError("Representação não encontrada.")
            self._add_progress(c, identifier, data, tipo, descricao, stamp, actor)
            c.execute(
                "UPDATE representacoes SET atualizado_em=?,atualizado_por=? WHERE id=?",
                (stamp, actor, identifier),
            )
        return self.progress(identifier)

    def add_document(self, identifier, meta, content, actor):
        stamp = now()
        file_id = uuid.uuid4().hex
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if not c.execute(
                "SELECT id FROM representacoes WHERE id=?", (identifier,)
            ).fetchone():
                raise ValueError("Representação não encontrada.")
            c.execute(
                "INSERT INTO representacao_documentos(id,representacao_id,andamento_id,"
                "tipo_documento,descricao,data_documento,nome_arquivo,mime_type,tamanho,"
                "arquivo,criado_em,criado_por) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    file_id,
                    identifier,
                    meta.get("andamento_id"),
                    meta["tipo_documento"],
                    meta.get("descricao") or "",
                    meta.get("data_documento"),
                    meta["nome_arquivo"],
                    meta["mime_type"],
                    len(content),
                    content,
                    stamp,
                    actor,
                ),
            )
            c.execute(
                "UPDATE representacoes SET atualizado_em=?,atualizado_por=? WHERE id=?",
                (stamp, actor, identifier),
            )
        return file_id

    def delete(self, identifier, actor=""):
        stamp = now()
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            row = c.execute(
                "SELECT numero_processo,situacao FROM representacoes WHERE id=?",
                (identifier,),
            ).fetchone()
            if not row:
                raise ValueError("Representação não encontrada.")
            if row["numero_processo"] or row["situacao"] in (
                "PROTOCOLADA",
                "EM_TRAMITACAO",
                "JULGADA",
                "ENCERRADA",
            ):
                raise ValueError(
                    "Representação protocolada não pode ser excluída. Utilize encerramento, cancelamento ou arquivamento."
                )
            self._unlink_ouvidoria(c, identifier, stamp, actor or "")
            c.execute("DELETE FROM representacoes WHERE id=?", (identifier,))
        return True

    def _ouvidoria_table_exists(self, connection):
        if self.store.backend == "postgresql":
            found = connection.execute(
                "SELECT 1 FROM information_schema.tables "
                "WHERE table_schema=current_schema() AND table_name='ouvidoria_manifestacoes'"
            ).fetchone()
        else:
            found = connection.execute(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name='ouvidoria_manifestacoes'"
            ).fetchone()
        return bool(found)

    def _unlink_ouvidoria(self, connection, identifier, stamp, actor):
        if not self._ouvidoria_table_exists(connection):
            return
        linked = connection.execute(
            "SELECT id, resultado FROM ouvidoria_manifestacoes WHERE representacao_id=?",
            (identifier,),
        ).fetchall()
        for item in linked:
            connection.execute(
                "UPDATE ouvidoria_manifestacoes SET representacao_id=NULL,"
                "resultado=CASE WHEN resultado='PROJETO_REPRESENTACAO' THEN NULL ELSE resultado END,"
                "atualizado_em=?,atualizado_por=? WHERE id=?",
                (stamp, actor, item["id"]),
            )
            connection.execute(
                "INSERT INTO ouvidoria_andamentos("
                "manifestacao_id,data,tipo,descricao,criado_em,criado_por) "
                "VALUES(?,?,?,?,?,?)",
                (
                    item["id"],
                    stamp[:10],
                    "PROJETO_REPRESENTACAO_EXCLUIDO",
                    "Projeto de Representação excluído.",
                    stamp,
                    actor,
                ),
            )

    def get(self, identifier):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                f"SELECT {COLUMNS} FROM representacoes WHERE id=?", (identifier,)
            ).fetchone()
            if not row:
                return None
            record = dict(row)
            record["possui_medida_cautelar"] = bool(record.get("possui_medida_cautelar"))
            record["integrantes"] = [
                dict(item)
                for item in c.execute(
                    f"SELECT {MEMBER_COLUMNS} FROM representacao_integrantes "
                    "WHERE representacao_id=? ORDER BY papel,id",
                    (identifier,),
                )
            ]
            return record

    def list(self, filters=None, limit=50, offset=0):
        filters = filters or {}
        clauses = []
        args = []
        mapping = {
            "situacao": "situacao",
            "fase_processual": "fase_processual",
            "origem": "origem",
            "prioridade": "prioridade",
        }
        for key, column in mapping.items():
            if filters.get(key):
                clauses.append(column + "=?")
                args.append(filters[key])
        if filters.get("tema"):
            clauses.append("LOWER(tema) LIKE LOWER(?)")
            args.append("%" + filters["tema"].strip() + "%")
        if filters.get("representado"):
            clauses.append("LOWER(representado) LIKE LOWER(?)")
            args.append("%" + filters["representado"].strip() + "%")
        if filters.get("relator"):
            clauses.append("LOWER(relator) LIKE LOWER(?)")
            args.append("%" + filters["relator"].strip() + "%")
        if filters.get("numero_processo"):
            clauses.append("LOWER(COALESCE(numero_processo,'')) LIKE LOWER(?)")
            args.append("%" + filters["numero_processo"].strip() + "%")
        if filters.get("ano"):
            clauses.append("substr(data_abertura,1,4)=?")
            args.append(str(filters["ano"]))
        text = (filters.get("pesquisa") or "").strip()
        if text:
            clauses.append(
                "(LOWER(titulo) LIKE LOWER(?) OR LOWER(objeto) LIKE LOWER(?) "
                "OR LOWER(representado) LIKE LOWER(?) OR LOWER(COALESCE(numero_processo,'')) LIKE LOWER(?))"
            )
            args.extend(["%" + text + "%"] * 4)
        if filters.get("procurador_id"):
            clauses.append(
                "EXISTS (SELECT 1 FROM representacao_integrantes i "
                "WHERE i.representacao_id=representacoes.id AND i.membro_tipo='PROCURADOR' "
                "AND i.membro_id=? AND i.papel='PROCURADOR_RESPONSAVEL')"
            )
            args.append(filters["procurador_id"])
        if filters.get("assessor_id"):
            clauses.append(
                "EXISTS (SELECT 1 FROM representacao_integrantes i "
                "WHERE i.representacao_id=representacoes.id AND i.membro_tipo='SERVIDOR' "
                "AND i.membro_id=? AND i.papel='ASSESSOR')"
            )
            args.append(filters["assessor_id"])
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        with self.store.connection(read_only=True) as c:
            rows = c.execute(
                f"SELECT {COLUMNS} FROM representacoes{where} "
                "ORDER BY data_abertura DESC, id DESC LIMIT ? OFFSET ?",
                (*args, limit, offset),
            ).fetchall()
            records = [dict(row) for row in rows]
            for record in records:
                record["possui_medida_cautelar"] = bool(record.get("possui_medida_cautelar"))
            ids = [row["id"] for row in records]
            members = {}
            latest = {}
            if ids:
                placeholders = ",".join("?" * len(ids))
                for item in c.execute(
                    f"SELECT {MEMBER_COLUMNS} FROM representacao_integrantes "
                    f"WHERE representacao_id IN ({placeholders}) ORDER BY papel,id",
                    ids,
                ):
                    members.setdefault(item["representacao_id"], []).append(dict(item))
                for item in c.execute(
                    "SELECT representacao_id,data,tipo,descricao FROM ("
                    "SELECT representacao_id,data,tipo,descricao,"
                    "ROW_NUMBER() OVER (PARTITION BY representacao_id "
                    "ORDER BY data DESC, id DESC) AS rn "
                    f"FROM representacao_andamentos WHERE representacao_id IN ({placeholders})"
                    ") ranked WHERE rn=1",
                    ids,
                ):
                    latest[item["representacao_id"]] = dict(item)
            for record in records:
                record["integrantes"] = members.get(record["id"], [])
                record["ultimo_andamento"] = latest.get(record["id"])
            return records

    def overview(self):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT "
                "SUM(CASE WHEN situacao IN ('IDEIA','PESQUISA','ELABORACAO','MINUTA_REVISAO','APROVADA') THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN situacao='AGUARDANDO_PROTOCOLO' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN situacao='EM_TRAMITACAO' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN fase_processual='MPC' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN fase_processual='PAUTA' THEN 1 ELSE 0 END),"
                "SUM(CASE WHEN situacao='JULGADA' THEN 1 ELSE 0 END) "
                "FROM representacoes"
            ).fetchone()
        keys = (
            "preparacao",
            "aguardando_protocolo",
            "tramitacao",
            "mpc",
            "pauta",
            "julgadas",
        )
        return dict(zip(keys, [int(value or 0) for value in row]))

    def progress(self, identifier):
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    f"SELECT {PROGRESS_COLUMNS} FROM representacao_andamentos "
                    "WHERE representacao_id=? ORDER BY data DESC, id DESC",
                    (identifier,),
                )
            ]

    def documents(self, identifier):
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    f"SELECT {DOCUMENT_META} FROM representacao_documentos "
                    "WHERE representacao_id=? ORDER BY COALESCE(data_documento,criado_em) DESC, id DESC",
                    (identifier,),
                )
            ]

    def download(self, file_id):
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT nome_arquivo,mime_type,arquivo FROM representacao_documentos WHERE id=?",
                (file_id,),
            ).fetchone()
            if not row:
                raise ValueError("Documento não encontrado.")
            return {
                "nome": row["nome_arquivo"],
                "tipo": row["mime_type"],
                "conteudo": bytes(row["arquivo"]),
            }

    def _replace_members(self, c, identifier, members, stamp):
        c.execute(
            "DELETE FROM representacao_integrantes WHERE representacao_id=?",
            (identifier,),
        )
        for member in members:
            c.execute(
                "INSERT INTO representacao_integrantes(representacao_id,membro_tipo,"
                "membro_id,papel,criado_em) VALUES(?,?,?,?,?)",
                (
                    identifier,
                    member["membro_tipo"],
                    member["membro_id"],
                    member["papel"],
                    stamp,
                ),
            )

    def _add_progress(self, c, identifier, data, tipo, descricao, stamp, actor):
        c.execute(
            "INSERT INTO representacao_andamentos(representacao_id,data,tipo,descricao,"
            "criado_em,criado_por) VALUES(?,?,?,?,?,?)",
            (identifier, data, tipo, descricao, stamp, actor),
        )


def ensure_schema(store):
    RepresentacoesStore(store)
