"""Personal task persistence. Every query is scoped by ``owner_user_id``."""

from datetime import date, datetime, time

from database.store import now, schema_key_of, unwrap_store

MARKER = "tarefas_schema_v3"
_READY = set()
ACTIVE = ("A_FAZER", "EM_ANDAMENTO", "AGUARDANDO")
HISTORY = ("CONCLUIDA", "CANCELADA")


def effective_deadline(row, tzinfo):
    """Local deadline: explicit hour, otherwise the end of the stated day."""
    if not row.get("prazo_data"):
        return None
    due_time = time.fromisoformat(row["prazo_hora"]) if row.get("prazo_hora") else time.max
    return datetime.combine(date.fromisoformat(row["prazo_data"]), due_time, tzinfo)


class TarefasStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        key = schema_key_of(self.store)
        if key in _READY:
            return
        identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.store.backend == "postgresql" else "INTEGER PRIMARY KEY"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(f"CREATE TABLE IF NOT EXISTS tarefas (id {identity}, owner_user_id BIGINT NOT NULL, titulo TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', categoria TEXT NOT NULL DEFAULT '', prioridade TEXT NOT NULL DEFAULT 'NORMAL' CHECK(prioridade IN ('BAIXA','NORMAL','ALTA','URGENTE')), status TEXT NOT NULL DEFAULT 'A_FAZER' CHECK(status IN ('A_FAZER','EM_ANDAMENTO','AGUARDANDO','CONCLUIDA','CANCELADA')), prazo_data TEXT, prazo_hora TEXT, lembrete_em TEXT, observacoes TEXT NOT NULL DEFAULT '', criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL, concluido_em TEXT, cancelado_em TEXT)")
            if self.store.backend == "postgresql":
                columns = {
                    row[0]
                    for row in c.execute(
                        "SELECT column_name FROM information_schema.columns "
                        "WHERE table_schema=current_schema() AND table_name='tarefas'"
                    )
                }
            else:
                columns = {row[1] for row in c.execute("PRAGMA table_info(tarefas)")}
            if "origem_modulo" not in columns:
                c.execute(
                    "ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS origem_modulo TEXT"
                    if self.store.backend == "postgresql"
                    else "ALTER TABLE tarefas ADD COLUMN origem_modulo TEXT"
                )
            if "origem_id" not in columns:
                c.execute(
                    "ALTER TABLE tarefas ADD COLUMN IF NOT EXISTS origem_id TEXT"
                    if self.store.backend == "postgresql"
                    else "ALTER TABLE tarefas ADD COLUMN origem_id TEXT"
                )
            c.execute(f"CREATE TABLE IF NOT EXISTS tarefas_checklist (id {identity}, tarefa_id BIGINT NOT NULL REFERENCES tarefas(id) ON DELETE CASCADE, texto TEXT NOT NULL, concluido INTEGER NOT NULL DEFAULT 0 CHECK(concluido IN (0,1)), ordem INTEGER NOT NULL, criado_em TEXT NOT NULL, atualizado_em TEXT NOT NULL)")
            c.execute(f"CREATE TABLE IF NOT EXISTS tarefas_lembretes (id {identity}, tarefa_id BIGINT NOT NULL REFERENCES tarefas(id) ON DELETE CASCADE, lembrar_em TEXT NOT NULL, criado_em TEXT NOT NULL, UNIQUE(tarefa_id,lembrar_em))")
            c.execute("CREATE INDEX IF NOT EXISTS tarefas_owner_status_prazo_idx ON tarefas(owner_user_id,status,prazo_data)")
            c.execute("CREATE INDEX IF NOT EXISTS tarefas_owner_prioridade_idx ON tarefas(owner_user_id,prioridade)")
            c.execute("CREATE INDEX IF NOT EXISTS tarefas_origem_idx ON tarefas(origem_modulo,origem_id)")
            c.execute("CREATE INDEX IF NOT EXISTS tarefas_checklist_tarefa_idx ON tarefas_checklist(tarefa_id,ordem)")
            c.execute("CREATE INDEX IF NOT EXISTS tarefas_lembretes_tarefa_momento_idx ON tarefas_lembretes(tarefa_id,lembrar_em)")
            # Compatibility with the original single reminder field.  Do not
            # remove it: existing installations may still contain the value.
            c.execute("INSERT INTO tarefas_lembretes(tarefa_id,lembrar_em,criado_em) SELECT id,lembrete_em,criado_em FROM tarefas WHERE lembrete_em IS NOT NULL AND lembrete_em!='' AND NOT EXISTS (SELECT 1 FROM tarefas_lembretes tl WHERE tl.tarefa_id=tarefas.id AND tl.lembrar_em=tarefas.lembrete_em)")
            c.execute("INSERT INTO configuracoes(chave,valor) VALUES(?,?) ON CONFLICT(chave) DO NOTHING", (MARKER, "1"))
        _READY.add(key)

    @staticmethod
    def _row(row):
        return dict(row) if row else None

    def create(self, owner_user_id, values):
        title = (values.get("titulo") or "").strip()
        if not title:
            raise ValueError("Informe o título da tarefa.")
        raw_reminders = values.get("lembretes", ([values["lembrete_em"]] if values.get("lembrete_em") else ()))
        stamp = now(); reminders = self._validate_reminders(raw_reminders, values.get("prazo_data"), values.get("prazo_hora"))
        origin_module = values.get("origem_modulo") or None
        origin_id = values.get("origem_id") or None
        if bool(origin_module) != bool(origin_id):
            raise ValueError("A origem da tarefa está incompleta.")
        if origin_module:
            from database.record_engagement import RecordEngagementStore

            if origin_module == "tarefa":
                raise ValueError("Uma tarefa não pode ter outra tarefa como origem.")
            RecordEngagementStore(self.store).authorize_origin(
                origin_module, origin_id, owner_user_id
            )
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            identifier = c.execute("INSERT INTO tarefas(owner_user_id,titulo,descricao,categoria,prioridade,status,prazo_data,prazo_hora,lembrete_em,observacoes,criado_em,atualizado_em,origem_modulo,origem_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)", (owner_user_id,title,(values.get("descricao") or "").strip(),(values.get("categoria") or "").strip(),values.get("prioridade") or "NORMAL","A_FAZER",values.get("prazo_data"),values.get("prazo_hora"),None,(values.get("observacoes") or "").strip(),stamp,stamp,origin_module,str(origin_id) if origin_id else None)).lastrowid
            c.executemany("INSERT INTO tarefas_lembretes(tarefa_id,lembrar_em,criado_em) VALUES(?,?,?)", [(identifier, reminder, stamp) for reminder in reminders])
        return self.get(identifier, owner_user_id)

    def get(self, identifier, owner_user_id):
        with self.store.connection(read_only=True) as c:
            return self._row(c.execute("SELECT * FROM tarefas WHERE id=? AND owner_user_id=?", (identifier, owner_user_id)).fetchone())

    def update(self, identifier, owner_user_id, values):
        allowed = ("titulo","descricao","categoria","prioridade","status","prazo_data","prazo_hora","lembrete_em","observacoes")
        data = {k: values[k] for k in allowed if k in values}
        if "titulo" in data and not str(data["titulo"]).strip():
            raise ValueError("Informe o título da tarefa.")
        if not data or not self.get(identifier, owner_user_id):
            return None
        raw_reminders = values.get("lembretes", ([values["lembrete_em"]] if values.get("lembrete_em") else None))
        reminders = self._validate_reminders(raw_reminders, data.get("prazo_data"), data.get("prazo_hora")) if raw_reminders is not None else None
        data["atualizado_em"] = now()
        assignments = ",".join(f"{key}=?" for key in data)
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(f"UPDATE tarefas SET {assignments} WHERE id=? AND owner_user_id=?", (*data.values(), identifier, owner_user_id))
            if reminders is not None:
                c.execute("DELETE FROM tarefas_lembretes WHERE tarefa_id=?", (identifier,))
                c.executemany("INSERT INTO tarefas_lembretes(tarefa_id,lembrar_em,criado_em) VALUES(?,?,?)", [(identifier, reminder, data["atualizado_em"]) for reminder in reminders])
        return self.get(identifier, owner_user_id)

    def change_status(self, identifier, owner_user_id, status):
        record, _changed = self.transition_status(identifier, owner_user_id, status)
        return record

    def transition_status(self, identifier, owner_user_id, status):
        if status not in (*ACTIVE, *HISTORY):
            return None, False
        stamp = now()
        concluded = stamp if status == "CONCLUIDA" else None
        cancelled = stamp if status == "CANCELADA" else None
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            current = c.execute(
                "SELECT * FROM tarefas WHERE id=? AND owner_user_id=?",
                (identifier, owner_user_id),
            ).fetchone()
            if not current:
                return None, False
            if current["status"] == status:
                return self._row(current), False
            c.execute("UPDATE tarefas SET status=?,concluido_em=?,cancelado_em=?,atualizado_em=? WHERE id=? AND owner_user_id=?", (status, concluded, cancelled, stamp, identifier, owner_user_id))
            changed = c.execute(
                "SELECT * FROM tarefas WHERE id=? AND owner_user_id=?",
                (identifier, owner_user_id),
            ).fetchone()
        return self._row(changed), True

    def delete(self, identifier, owner_user_id):
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            row = c.execute("SELECT id FROM tarefas WHERE id=? AND owner_user_id=?", (identifier, owner_user_id)).fetchone()
            if not row: return False
            from database.record_engagement import RecordEngagementStore

            RecordEngagementStore.detach_origin(c, "tarefa", identifier)
            c.execute("DELETE FROM tarefas WHERE id=? AND owner_user_id=?", (identifier, owner_user_id))
            return True

    def list_related(self, module, identifier, actor_id):
        from database.record_engagement import RecordEngagementStore

        RecordEngagementStore(self.store).authorize_origin(module, identifier, actor_id)
        with self.store.connection(read_only=True) as c:
            return [
                dict(row)
                for row in c.execute(
                    "SELECT t.id,t.titulo,t.prazo_data,t.prazo_hora,t.status,"
                    "COALESCE(u.nome,'Usuário indisponível') AS responsavel "
                    "FROM tarefas t LEFT JOIN usuarios_acesso u ON u.id=t.owner_user_id "
                    "WHERE t.origem_modulo=? AND t.origem_id=? "
                    "ORDER BY t.atualizado_em DESC,t.id DESC LIMIT 100",
                    (module, str(identifier)),
                )
            ]

    @staticmethod
    def detach_origin(connection, module, identifier):
        connection.execute(
            "UPDATE tarefas SET origem_modulo=NULL,origem_id=NULL,atualizado_em=? "
            "WHERE origem_modulo=? AND origem_id=?",
            (now(), module, str(identifier)),
        )

    def reminders(self, identifier, owner_user_id):
        if not self.get(identifier, owner_user_id): return []
        with self.store.connection(read_only=True) as c:
            return [dict(r) for r in c.execute("SELECT * FROM tarefas_lembretes WHERE tarefa_id=? ORDER BY lembrar_em,id", (identifier,))]

    @staticmethod
    def _validate_reminders(reminders, due_date, due_time=None):
        values = sorted(set(str(value) for value in (reminders or ()) if value))
        if len(values) > 3: raise ValueError("Uma tarefa pode ter no máximo 3 lembretes.")
        parsed = []
        for value in values:
            try: moment = datetime.fromisoformat(value)
            except ValueError: raise ValueError("Todo lembrete precisa ter data e hora válidas.") from None
            if moment.tzinfo is None: raise ValueError("Todo lembrete precisa ter data e hora.")
            parsed.append(moment)
        if len(parsed) != len(reminders or ()): raise ValueError("Não são permitidos lembretes duplicados.")
        if due_date:
            due = datetime.combine(date.fromisoformat(due_date), time.fromisoformat(due_time) if due_time else time.max, parsed[0].tzinfo if parsed else None)
            if any(moment > due for moment in parsed): raise ValueError("O lembrete não pode ser posterior ao prazo.")
        return [moment.isoformat() for moment in sorted(parsed)]

    def situation_counts(self, owner_user_id, today=None):
        today = (today or date.today()).isoformat()
        with self.store.connection(read_only=True) as c:
            row=c.execute("SELECT SUM(CASE WHEN prazo_data<? THEN 1 ELSE 0 END),SUM(CASE WHEN prazo_data=? THEN 1 ELSE 0 END),SUM(CASE WHEN prazo_data>? THEN 1 ELSE 0 END),SUM(CASE WHEN status='EM_ANDAMENTO' THEN 1 ELSE 0 END),SUM(CASE WHEN status='AGUARDANDO' THEN 1 ELSE 0 END) FROM tarefas WHERE owner_user_id=? AND status IN ('A_FAZER','EM_ANDAMENTO','AGUARDANDO')",(today,today,today,owner_user_id)).fetchone()
        return dict(zip(("atrasadas","hoje","proximas","em_andamento","aguardando"),[int(x or 0) for x in row]))

    def _list(self, owner, statuses, filters, limit, offset):
        filters=filters or {}; clauses=["t.owner_user_id=?", "t.status IN ("+",".join("?"*len(statuses))+")"]; args=[owner,*statuses]
        text=(filters.get("pesquisa") or "").strip()
        if text: clauses.append("(t.titulo LIKE ? OR t.descricao LIKE ? OR t.categoria LIKE ? OR t.observacoes LIKE ?)"); args += ["%"+text+"%"]*4
        for key in ("prioridade","status","categoria"):
            if filters.get(key): clauses.append("t."+key+"=?"); args.append(filters[key])
        if filters.get("prazo") == "sem_prazo": clauses.append("t.prazo_data IS NULL")
        if filters.get("prazo") == "atrasadas": clauses.append("t.prazo_data<?"); args.append(date.today().isoformat())
        if filters.get("prazo") == "hoje": clauses.append("t.prazo_data=?"); args.append(date.today().isoformat())
        where=" WHERE "+" AND ".join(clauses)
        order="CASE WHEN t.prazo_data IS NOT NULL AND t.prazo_data<? THEN 0 ELSE 1 END, CASE t.prioridade WHEN 'URGENTE' THEN 0 WHEN 'ALTA' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END, CASE WHEN t.prazo_data IS NULL THEN 1 ELSE 0 END, t.prazo_data, t.criado_em DESC" if statuses==ACTIVE else "t.atualizado_em DESC"
        values=[*args]; values += [date.today().isoformat()] if statuses==ACTIVE else []
        with self.store.connection(read_only=True) as c:
            rows=c.execute("SELECT t.* FROM tarefas t"+where+" ORDER BY "+order+" LIMIT ? OFFSET ?",(*values,limit,offset)).fetchall()
        records = [dict(r) for r in rows]
        identifiers = [record["id"] for record in records]
        if len(identifiers) != len(set(identifiers)):
            raise RuntimeError("A consulta de tarefas retornou IDs duplicados.")
        return records
    def list_active(self, owner, filters=None, limit=100, offset=0): return self._list(owner,ACTIVE,filters,limit,offset)
    def list_history(self, owner, filters=None, limit=30, offset=0): return self._list(owner,HISTORY,filters,limit,offset)
    def alert_window(self, owner, now_local):
        horizon = (now_local.date().fromordinal(now_local.date().toordinal() + 7)).isoformat()
        with self.store.connection(read_only=True) as c:
            rows=c.execute("SELECT t.*,MIN(tl.lembrar_em) AS lembrete_atingido_em FROM tarefas t LEFT JOIN tarefas_lembretes tl ON tl.tarefa_id=t.id AND tl.lembrar_em<=? WHERE t.owner_user_id=? AND t.status IN ('A_FAZER','EM_ANDAMENTO','AGUARDANDO') AND ((t.prazo_data IS NOT NULL AND t.prazo_data<=?) OR tl.id IS NOT NULL) GROUP BY t.id LIMIT 50",(now_local.isoformat(),owner,horizon)).fetchall()
        return [dict(r) for r in rows]
