"""Persistência aditiva para os relatórios exportados pelo Tramita."""

from collections import defaultdict
from datetime import date, datetime
from statistics import median
from database.store import unwrap_store
from threading import RLock

_SCHEMA_LOCK = RLock()


class TramitaReportsStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        # Only a successful commit may mark this Store ready. The portal keeps
        # this object in the session; another Store still validates its database.
        with _SCHEMA_LOCK:
            if getattr(self.store, "_tramita_schema_ready", False):
                return
            self._initialize_schema()
            self.store._tramita_schema_ready = True

    def _initialize_schema(self):
        identity = (
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if self.store.backend == "postgresql"
            else "INTEGER PRIMARY KEY"
        )
        with self.store.connection() as c:
            if self.store.backend == "sqlite":
                self._migrate_sqlite_hash_constraint(c)
            c.execute("BEGIN IMMEDIATE")
            c.execute(
                f"CREATE TABLE IF NOT EXISTS tramita_importacoes (id {identity}, tipo TEXT NOT NULL CHECK(tipo IN ('ENTRADAS','SAIDAS','ESTOQUE')), competencia TEXT, data_snapshot TEXT, nome_arquivo TEXT NOT NULL, hash_arquivo TEXT NOT NULL, quantidade_registros INTEGER NOT NULL, quantidade_inserida INTEGER NOT NULL DEFAULT 0, quantidade_duplicada INTEGER NOT NULL DEFAULT 0, origem_historica TEXT NOT NULL DEFAULT 'LEGADO', importado_em TEXT NOT NULL, importado_por TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'CONCLUIDA')"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS tramita_movimentacoes (id {identity}, importacao_id INTEGER NOT NULL REFERENCES tramita_importacoes(id), competencia TEXT NOT NULL, tipo_movimentacao TEXT NOT NULL CHECK(tipo_movimentacao IN ('ENTRADA','SAIDA')), protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '', origem TEXT NOT NULL DEFAULT '', data_realizacao TEXT, procurador TEXT NOT NULL DEFAULT '', procurador_original TEXT NOT NULL DEFAULT '', motivo_distribuicao TEXT NOT NULL DEFAULT '', data_devolucao TEXT, motivo_devolucao TEXT NOT NULL DEFAULT '', data_evento TEXT, classificacao_producao TEXT NOT NULL DEFAULT '', chave_evento TEXT NOT NULL DEFAULT '')"
            )
            c.execute(
                f"CREATE TABLE IF NOT EXISTS tramita_estoque (id {identity}, importacao_id INTEGER NOT NULL REFERENCES tramita_importacoes(id), data_snapshot TEXT NOT NULL, protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', digital TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '', jurisdicionado TEXT NOT NULL DEFAULT '', fase TEXT NOT NULL DEFAULT '', procurador TEXT NOT NULL DEFAULT '', dias_com_procurador REAL, assistente TEXT NOT NULL DEFAULT '', dias_com_assistente REAL, dias_no_mpc REAL, prescricao TEXT NOT NULL DEFAULT '')"
            )
            self._ensure_columns(c)
            c.execute(
                "CREATE INDEX IF NOT EXISTS tramita_movimentacoes_competencia_idx ON tramita_movimentacoes(competencia, tipo_movimentacao)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS tramita_movimentacoes_evento_idx ON tramita_movimentacoes(data_evento, tipo_movimentacao, procurador)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS tramita_importacoes_origem_historica_idx ON tramita_importacoes(origem_historica)"
            )
            c.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS tramita_importacoes_estoque_snapshot_unico "
                "ON tramita_importacoes(data_snapshot) "
                "WHERE tipo='ESTOQUE' AND data_snapshot IS NOT NULL"
            )
            c.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS tramita_movimentacoes_chave_unica ON tramita_movimentacoes(chave_evento) WHERE chave_evento<>''"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS tramita_estoque_snapshot_idx ON tramita_estoque(data_snapshot)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS tramita_movimentacoes_pagina_idx ON tramita_movimentacoes(competencia,procurador,protocolo,id)"
            )
            c.execute(
                "CREATE INDEX IF NOT EXISTS tramita_estoque_procurador_idx ON tramita_estoque(data_snapshot,procurador)"
            )

    def _migrate_sqlite_hash_constraint(self, connection):
        """Remove the legacy global hash constraint without changing child rows.

        SQLite represents the original column-level ``UNIQUE`` as an automatic
        index, which cannot be dropped in place.  Rebuilding only the parent
        table preserves the primary keys referenced by stock and movement rows.
        """
        table = connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name='tramita_importacoes'"
        ).fetchone()
        if not table:
            return
        unique_hash = False
        for index in connection.execute("PRAGMA index_list(tramita_importacoes)"):
            if not index[2]:
                continue
            name = str(index[1]).replace('"', '""')
            columns = [
                row[2] for row in connection.execute(f'PRAGMA index_info("{name}")')
            ]
            if columns == ["hash_arquivo"]:
                unique_hash = True
                break
        if not unique_hash:
            return
        duplicates = connection.execute(
            "SELECT data_snapshot,COUNT(*) FROM tramita_importacoes "
            "WHERE tipo='ESTOQUE' AND data_snapshot IS NOT NULL "
            "GROUP BY data_snapshot HAVING COUNT(*)>1"
        ).fetchall()
        if duplicates:
            dates = ", ".join(str(row[0]) for row in duplicates)
            raise RuntimeError(
                "Migração do estoque interrompida: há mais de uma fotografia "
                f"para a(s) data(s) {dates}."
            )

        # A legacy SQLite table needs a parent-table rebuild.  Preserve a
        # verified, restorable copy before any DDL; Store.backup uses SQLite's
        # online backup API instead of copying a potentially open database file.
        self.store.automatic_backup("antes_migracao_estoque_snapshot")
        old_count = connection.execute(
            "SELECT COUNT(*) FROM tramita_importacoes"
        ).fetchone()[0]
        existing_columns = {
            row[1]
            for row in connection.execute("PRAGMA table_info(tramita_importacoes)")
        }
        inserted_count = (
            "quantidade_inserida" if "quantidade_inserida" in existing_columns else "0"
        )
        duplicate_count = (
            "quantidade_duplicada"
            if "quantidade_duplicada" in existing_columns
            else "0"
        )
        historical_origin = (
            "origem_historica" if "origem_historica" in existing_columns else "'LEGADO'"
        )
        connection.execute("PRAGMA foreign_keys=OFF")
        try:
            connection.execute("BEGIN IMMEDIATE")
            connection.execute(
                "CREATE TABLE tramita_importacoes_nova ("
                "id INTEGER PRIMARY KEY,"
                "tipo TEXT NOT NULL CHECK(tipo IN ('ENTRADAS','SAIDAS','ESTOQUE')),"
                "competencia TEXT,data_snapshot TEXT,nome_arquivo TEXT NOT NULL,"
                "hash_arquivo TEXT NOT NULL,quantidade_registros INTEGER NOT NULL,"
                "quantidade_inserida INTEGER NOT NULL DEFAULT 0,"
                "quantidade_duplicada INTEGER NOT NULL DEFAULT 0,"
                "origem_historica TEXT NOT NULL DEFAULT 'LEGADO',"
                "importado_em TEXT NOT NULL,importado_por TEXT NOT NULL DEFAULT '',"
                "status TEXT NOT NULL DEFAULT 'CONCLUIDA')"
            )
            connection.execute(
                "INSERT INTO tramita_importacoes_nova "
                "SELECT id,tipo,competencia,data_snapshot,nome_arquivo,hash_arquivo,"
                f"quantidade_registros,{inserted_count},{duplicate_count},"
                f"{historical_origin},importado_em,importado_por,status "
                "FROM tramita_importacoes"
            )
            new_count = connection.execute(
                "SELECT COUNT(*) FROM tramita_importacoes_nova"
            ).fetchone()[0]
            orphan = connection.execute(
                "SELECT 1 FROM ("
                "SELECT importacao_id FROM tramita_movimentacoes "
                "UNION ALL SELECT importacao_id FROM tramita_estoque"
                ") filhos LEFT JOIN tramita_importacoes_nova pai "
                "ON pai.id=filhos.importacao_id WHERE pai.id IS NULL LIMIT 1"
            ).fetchone()
            if new_count != old_count or orphan:
                raise RuntimeError("Validação da migração de importações falhou.")
            connection.execute("DROP TABLE tramita_importacoes")
            connection.execute(
                "ALTER TABLE tramita_importacoes_nova RENAME TO tramita_importacoes"
            )
            connection.execute("COMMIT")
        finally:
            connection.execute("PRAGMA foreign_keys=ON")
        violations = connection.execute("PRAGMA foreign_key_check").fetchone()
        if violations:
            raise RuntimeError(
                "A migração deixou uma referência de importação inválida."
            )

    def _ensure_columns(self, connection):
        """Add reporting fields to databases created by the prior monthly view."""
        if self.store.backend == "postgresql":
            columns = {
                row[0]
                for row in connection.execute(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_schema=current_schema() AND table_name='tramita_movimentacoes'"
                )
            }
            import_columns = {
                row[0]
                for row in connection.execute(
                    "SELECT column_name FROM information_schema.columns "
                    "WHERE table_schema=current_schema() AND table_name='tramita_importacoes'"
                )
            }
        else:
            columns = {
                row[1]
                for row in connection.execute(
                    "PRAGMA table_info(tramita_movimentacoes)"
                )
            }
            import_columns = {
                row[1]
                for row in connection.execute("PRAGMA table_info(tramita_importacoes)")
            }
        additions = {
            "procurador_original": "TEXT NOT NULL DEFAULT ''",
            "data_evento": "TEXT",
            "classificacao_producao": "TEXT NOT NULL DEFAULT ''",
            "chave_evento": "TEXT NOT NULL DEFAULT ''",
        }
        for name, definition in additions.items():
            if name not in columns:
                connection.execute(
                    f"ALTER TABLE tramita_movimentacoes ADD COLUMN {name} {definition}"
                )
        import_additions = {
            "quantidade_inserida": "INTEGER NOT NULL DEFAULT 0",
            "quantidade_duplicada": "INTEGER NOT NULL DEFAULT 0",
            "origem_historica": "TEXT NOT NULL DEFAULT 'LEGADO'",
        }
        for name, definition in import_additions.items():
            if name not in import_columns:
                connection.execute(
                    f"ALTER TABLE tramita_importacoes ADD COLUMN {name} {definition}"
                )
        self._backfill_event_fields(connection)

    def _backfill_event_fields(self, connection):
        from services.tramita_reports import (
            movement_event_key,
            production_classification,
        )

        rows = connection.execute(
            "SELECT id,tipo_movimentacao,protocolo,procurador,data_realizacao,"
            "motivo_distribuicao,data_devolucao,motivo_devolucao,"
            "data_evento,classificacao_producao,chave_evento FROM tramita_movimentacoes "
            "WHERE data_evento IS NULL"
        ).fetchall()
        seen = set()
        for item in rows:
            row = dict(item)
            kind = "ENTRADAS" if row["tipo_movimentacao"] == "ENTRADA" else "SAIDAS"
            event_date = (
                row["data_realizacao"] if kind == "ENTRADAS" else row["data_devolucao"]
            )
            key = movement_event_key(kind, row) if event_date else ""
            # Existing duplicate legacy records remain auditable. Their empty key
            # prevents a migration failure and they are never created again.
            if key and key in seen:
                key = ""
            seen.add(key)
            classification = production_classification(row["motivo_devolucao"]) or ""
            connection.execute(
                "UPDATE tramita_movimentacoes SET data_evento=?,classificacao_producao=?,"
                "chave_evento=? WHERE id=?",
                (event_date, classification, key, row["id"]),
            )

    def imported_hash(self, file_hash, kind=None):
        where, values = ["hash_arquivo=?"], [file_hash]
        if kind is not None:
            where.append("tipo=?")
            values.append(kind)
        with self.store.connection(read_only=True) as c:
            return (
                c.execute(
                    "SELECT id FROM tramita_importacoes WHERE " + " AND ".join(where),
                    values,
                ).fetchone()
                is not None
            )

    def stock_snapshot_state(self, snapshot_date, file_hash):
        """Describe the operational stock snapshot for one reference date."""
        with self.store.connection(read_only=True) as c:
            row = c.execute(
                "SELECT id,hash_arquivo,quantidade_registros FROM tramita_importacoes "
                "WHERE tipo='ESTOQUE' AND data_snapshot=?",
                (snapshot_date,),
            ).fetchone()
        if not row:
            return {"status": "new"}
        current = dict(row)
        return {
            "status": "current" if current["hash_arquivo"] == file_hash else "replace",
            "import_id": current["id"],
            "hash_arquivo": current["hash_arquivo"],
            "quantidade_registros": current["quantidade_registros"],
        }

    def import_rows(
        self,
        *,
        kind,
        file_name,
        file_hash,
        actor,
        competence=None,
        snapshot_date=None,
        rows=(),
    ):
        rows = list(rows)
        if kind != "ESTOQUE" and self.imported_hash(file_hash, kind):
            raise ValueError("Este arquivo já foi importado anteriormente.")
        from database.store import now

        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if (
                kind != "ESTOQUE"
                and c.execute(
                    "SELECT 1 FROM tramita_importacoes WHERE hash_arquivo=? AND tipo=?",
                    (file_hash, kind),
                ).fetchone()
            ):
                raise ValueError("Este arquivo já foi importado anteriormente.")
            prepared, duplicates = self._prepared_events(c, kind, rows)
            if kind in ("ENTRADAS", "SAIDAS"):
                inserted = c.execute(
                    "INSERT INTO tramita_importacoes(tipo,competencia,data_snapshot,nome_arquivo,hash_arquivo,quantidade_registros,quantidade_inserida,quantidade_duplicada,importado_em,importado_por) VALUES(?,?,?,?,?,?,?,?,?,?)",
                    (
                        kind,
                        competence,
                        snapshot_date,
                        file_name,
                        file_hash,
                        len(rows),
                        len(prepared),
                        duplicates,
                        now(),
                        actor or "",
                    ),
                )
                import_id = inserted.lastrowid
                self._insert_events(c, import_id, prepared)
            else:
                existing = c.execute(
                    "SELECT id,hash_arquivo FROM tramita_importacoes "
                    "WHERE tipo='ESTOQUE' AND data_snapshot=?",
                    (snapshot_date,),
                ).fetchone()
                if existing and existing[1] == file_hash:
                    return existing[0]
                if existing:
                    import_id = existing[0]
                    c.execute(
                        "DELETE FROM tramita_estoque WHERE importacao_id=?",
                        (import_id,),
                    )
                    c.execute(
                        "UPDATE tramita_importacoes SET competencia=?,nome_arquivo=?,"
                        "hash_arquivo=?,quantidade_registros=?,quantidade_inserida=?,"
                        "quantidade_duplicada=?,importado_em=?,importado_por=? WHERE id=?",
                        (
                            competence,
                            file_name,
                            file_hash,
                            len(rows),
                            len(prepared),
                            duplicates,
                            now(),
                            actor or "",
                            import_id,
                        ),
                    )
                else:
                    inserted = c.execute(
                        "INSERT INTO tramita_importacoes(tipo,competencia,data_snapshot,nome_arquivo,hash_arquivo,quantidade_registros,quantidade_inserida,quantidade_duplicada,importado_em,importado_por) VALUES(?,?,?,?,?,?,?,?,?,?)",
                        (
                            kind,
                            competence,
                            snapshot_date,
                            file_name,
                            file_hash,
                            len(rows),
                            len(prepared),
                            duplicates,
                            now(),
                            actor or "",
                        ),
                    )
                    import_id = inserted.lastrowid
                self._insert_stock_rows(c, import_id, snapshot_date, rows)
        return import_id

    @staticmethod
    def _insert_stock_rows(connection, import_id, snapshot_date, rows):
        connection.executemany(
            "INSERT INTO tramita_estoque(importacao_id,data_snapshot,protocolo,tipo,digital,subcategoria,jurisdicionado,fase,procurador,dias_com_procurador,assistente,dias_com_assistente,dias_no_mpc,prescricao) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            [
                (
                    import_id,
                    snapshot_date,
                    row["protocolo"],
                    row["tipo"],
                    row["digital"],
                    row["subcategoria"],
                    row["jurisdicionado"],
                    row["fase"],
                    row["procurador"],
                    row["dias_com_procurador"],
                    row["assistente"],
                    row["dias_com_assistente"],
                    row["dias_no_mpc"],
                    row["prescricao"],
                )
                for row in rows
            ],
        )

    def import_historical_rows(
        self, *, kind, file_name, file_hash, actor, source_competence, rows
    ):
        """Reconcile one immutable historical source by its event identity.

        The source hash is retained for audit, but never decides whether the
        events are complete.  This permits repairing a prior interrupted
        import whose file record exists while one or more events do not.
        """
        rows = list(rows)
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            existing = c.execute(
                "SELECT id FROM tramita_importacoes WHERE hash_arquivo=? "
                "AND tipo=? AND origem_historica='REFERENCIA_TRAMITA_2026'",
                (file_hash, kind),
            ).fetchone()
            from database.store import now

            if existing:
                import_id = existing[0]
                c.execute(
                    "UPDATE tramita_importacoes SET tipo=?,competencia=?,nome_arquivo=?,"
                    "origem_historica='REFERENCIA_TRAMITA_2026' WHERE id=?",
                    (kind, source_competence, file_name, import_id),
                )
            else:
                inserted = c.execute(
                    "INSERT INTO tramita_importacoes("
                    "tipo,competencia,nome_arquivo,hash_arquivo,quantidade_registros,"
                    "quantidade_inserida,quantidade_duplicada,origem_historica,importado_em,importado_por) "
                    "VALUES(?,?,?,?,?,?,?,?,?,?)",
                    (
                        kind,
                        source_competence,
                        file_name,
                        file_hash,
                        len(rows),
                        0,
                        0,
                        "REFERENCIA_TRAMITA_2026",
                        now(),
                        actor or "",
                    ),
                )
                import_id = inserted.lastrowid
            prepared, duplicates = self._prepared_events(
                c, kind, rows, reconcile_import_id=import_id
            )
            self._insert_events(c, import_id, prepared)
            stored = c.execute(
                "SELECT COUNT(*) FROM tramita_movimentacoes WHERE importacao_id=?",
                (import_id,),
            ).fetchone()[0]
            c.execute(
                "UPDATE tramita_importacoes SET quantidade_registros=?,quantidade_inserida=?,"
                "quantidade_duplicada=? WHERE id=?",
                (len(rows), stored, duplicates, import_id),
            )
        return {
            "file_name": file_name,
            "source_rows": len(rows),
            "inserted": len(prepared),
            "duplicates": duplicates,
            "already_imported": bool(existing),
        }

    def _prepared_events(self, connection, kind, rows, reconcile_import_id=None):
        from services.tramita_reports import (
            movement_event_key,
            production_classification,
        )

        if kind not in ("ENTRADAS", "SAIDAS"):
            return [], 0
        movement = "ENTRADA" if kind == "ENTRADAS" else "SAIDA"
        existing = {
            row["chave_evento"]: row
            for row in connection.execute(
                "SELECT id,importacao_id,chave_evento FROM tramita_movimentacoes "
                "WHERE chave_evento<>''"
            )
        }
        prepared, duplicates = [], 0
        for row in rows:
            event_date = (
                row.get("data_realizacao")
                if kind == "ENTRADAS"
                else row.get("data_devolucao")
            )
            if not event_date:
                duplicates += 1
                continue
            key = movement_event_key(kind, row)
            if key in existing:
                duplicates += 1
                # A matching legacy event is the same recorded fact.  Link it
                # to the verified reference import instead of duplicating it.
                if (
                    reconcile_import_id is not None
                    and existing[key]["importacao_id"] != reconcile_import_id
                ):
                    connection.execute(
                        "UPDATE tramita_movimentacoes SET importacao_id=? WHERE id=?",
                        (reconcile_import_id, existing[key]["id"]),
                    )
                continue
            existing[key] = {"importacao_id": reconcile_import_id}
            prepared.append(
                (
                    event_date[:7],
                    movement,
                    row["protocolo"],
                    row.get("tipo", ""),
                    row.get("subcategoria", ""),
                    row.get("origem", ""),
                    row.get("data_realizacao"),
                    row.get("procurador", ""),
                    row.get("procurador_original", row.get("procurador", "")),
                    row.get("motivo_distribuicao", ""),
                    row.get("data_devolucao"),
                    row.get("motivo_devolucao", ""),
                    event_date,
                    production_classification(row.get("motivo_devolucao", "")) or "",
                    key,
                )
            )
        return prepared, duplicates

    @staticmethod
    def _insert_events(connection, import_id, rows):
        connection.executemany(
            "INSERT INTO tramita_movimentacoes("
            "importacao_id,competencia,tipo_movimentacao,protocolo,tipo,subcategoria,origem,"
            "data_realizacao,procurador,procurador_original,motivo_distribuicao,"
            "data_devolucao,motivo_devolucao,data_evento,classificacao_producao,chave_evento) "
            "VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
            [(import_id, *row) for row in rows],
        )

    def competences(self):
        with self.store.connection(read_only=True) as c:
            return [
                r[0]
                for r in c.execute(
                    "SELECT DISTINCT substr(m.data_evento,1,7) FROM tramita_movimentacoes m "
                    "JOIN tramita_importacoes i ON i.id=m.importacao_id "
                    "WHERE m.data_evento IS NOT NULL AND i.origem_historica='REFERENCIA_TRAMITA_2026' ORDER BY 1 DESC"
                )
            ]

    def historical_years(self):
        with self.store.connection(read_only=True) as c:
            return [
                int(row[0])
                for row in c.execute(
                    "SELECT DISTINCT substr(m.data_evento,1,4) FROM tramita_movimentacoes m "
                    "JOIN tramita_importacoes i ON i.id=m.importacao_id "
                    "WHERE m.data_evento IS NOT NULL AND i.origem_historica='REFERENCIA_TRAMITA_2026' ORDER BY 1 DESC"
                )
            ]

    def months_for_year(self, year):
        prefix = f"{int(year):04d}-"
        with self.store.connection(read_only=True) as c:
            return [
                int(row[0][5:7])
                for row in c.execute(
                    "SELECT DISTINCT substr(m.data_evento,1,7) FROM tramita_movimentacoes m "
                    "JOIN tramita_importacoes i ON i.id=m.importacao_id "
                    "WHERE m.data_evento LIKE ? AND i.origem_historica='REFERENCIA_TRAMITA_2026' ORDER BY 1",
                    (prefix + "%",),
                )
            ]

    def historical_coverage(self, year):
        """Describe actual historical coverage without inferring months from files."""
        months = self.months_for_year(year)
        last = max(months) if months else None
        expected = list(range(1, last + 1)) if last else []
        missing = [month for month in expected if month not in months]
        return {
            "months": months,
            "last_month": last,
            "missing_months": missing,
            "complete_through_last_month": not missing,
        }

    def historical_audit(self, year):
        """Return the event matrix, retaining the import lineage for diagnosis."""
        prefix = f"{int(year):04d}-"
        rows = self._read(
            "SELECT substr(m.data_evento,1,7) AS period, i.origem_historica,"
            "m.tipo_movimentacao,m.classificacao_producao,COUNT(*) AS total "
            "FROM tramita_movimentacoes m JOIN tramita_importacoes i "
            "ON i.id=m.importacao_id WHERE m.data_evento LIKE ? "
            "GROUP BY 1,2,3,4 ORDER BY 1,2,3,4",
            (prefix + "%",),
        )
        return rows

    def period_report(self, start, end):
        """Aggregate all indicators once for a half-open calendar period.

        Distribution is dated by its distribution timestamp.  Production is
        dated by its return timestamp and limited to Parecer/Cota.  This keeps
        an October return out of September even if its original distribution
        appears in the September source file.
        """
        return self.period_data(start, end)["report"]

    def period_data(self, start, end):
        """Return one period's approved events and its existing aggregate.

        The UI uses the event set only for visual derivations such as duration
        bands and heatmaps; it does not persist or reinterpret any event.
        """
        rows = self._read(
            "SELECT tipo_movimentacao,procurador,data_realizacao,data_devolucao,"
            "classificacao_producao,data_evento,protocolo FROM tramita_movimentacoes m "
            "JOIN tramita_importacoes i ON i.id=m.importacao_id "
            "WHERE m.data_evento>=? AND m.data_evento<? "
            "AND i.origem_historica='REFERENCIA_TRAMITA_2026'",
            (start, end),
        )
        return {"report": self._aggregate_period(rows), "events": rows}

    @staticmethod
    def _aggregate_period(rows):
        groups = defaultdict(list)
        groups["__total__"] = rows
        for row in rows:
            groups[row["procurador"] or "Não identificado"].append(row)

        def metrics(items):
            entries = sum(row["tipo_movimentacao"] == "ENTRADA" for row in items)
            productive = [
                row
                for row in items
                if row["tipo_movimentacao"] == "SAIDA"
                and row["classificacao_producao"] in ("PARECER", "COTA")
            ]
            days = []
            for row in productive:
                if row["data_realizacao"] and row["data_devolucao"]:
                    days.append(
                        (
                            datetime.fromisoformat(row["data_devolucao"])
                            - datetime.fromisoformat(row["data_realizacao"])
                        ).total_seconds()
                        / 86400
                    )
            opinions = sum(
                row["classificacao_producao"] == "PARECER" for row in productive
            )
            quotas = sum(row["classificacao_producao"] == "COTA" for row in productive)
            production = len(productive)
            nonproductive_returns = sum(
                row["tipo_movimentacao"] == "SAIDA"
                and row["classificacao_producao"] not in ("PARECER", "COTA")
                for row in items
            )
            return {
                "distributed": entries,
                "production": production,
                "opinions": opinions,
                "quotas": quotas,
                "nonproductive_returns": nonproductive_returns,
                "production_rate": production / entries * 100 if entries else None,
                "median_days": median(days) if days else None,
            }

        total = metrics(groups.pop("__total__"))
        by_procurador = [
            {"procurador": person, **metrics(items)} for person, items in groups.items()
        ]
        return {
            "summary": total,
            "by_procurador": sorted(by_procurador, key=lambda row: row["procurador"]),
        }

    def monthly_reports(self, year, months=None):
        months = months or self.months_for_year(year)
        start, end = date(int(year), 1, 1), date(int(year) + 1, 1, 1)
        rows = self._read(
            "SELECT tipo_movimentacao,procurador,data_realizacao,data_devolucao,"
            "classificacao_producao,data_evento FROM tramita_movimentacoes m "
            "JOIN tramita_importacoes i ON i.id=m.importacao_id "
            "WHERE m.data_evento>=? AND m.data_evento<? "
            "AND i.origem_historica='REFERENCIA_TRAMITA_2026'",
            (start.isoformat(), end.isoformat()),
        )
        by_month = defaultdict(list)
        for row in rows:
            by_month[int(row["data_evento"][5:7])].append(row)
        return [
            {"month": int(month), **self._aggregate_period(by_month[int(month)])}
            for month in months
        ]

    def quarterly_reports(self, year, quarters=None):
        """Aggregate all requested quarters from a single annual event read."""
        quarters = quarters or (1, 2, 3, 4)
        start, end = date(int(year), 1, 1), date(int(year) + 1, 1, 1)
        rows = self._read(
            "SELECT m.tipo_movimentacao,m.procurador,m.data_realizacao,m.data_devolucao,"
            "m.classificacao_producao,m.data_evento FROM tramita_movimentacoes m "
            "JOIN tramita_importacoes i ON i.id=m.importacao_id "
            "WHERE m.data_evento>=? AND m.data_evento<? "
            "AND i.origem_historica='REFERENCIA_TRAMITA_2026'",
            (start.isoformat(), end.isoformat()),
        )
        by_quarter = defaultdict(list)
        for row in rows:
            by_quarter[(int(row["data_evento"][5:7]) - 1) // 3 + 1].append(row)
        return [
            {
                "quarter": int(quarter),
                **self._aggregate_period(by_quarter[int(quarter)]),
            }
            for quarter in quarters
        ]

    def latest_snapshot(self):
        with self.store.connection(read_only=True) as c:
            row = c.execute("SELECT MAX(data_snapshot) FROM tramita_estoque").fetchone()
            return row[0] if row and row[0] else None

    def _read(self, sql, values=()):
        with self.store.connection(read_only=True) as c:
            return [dict(row) for row in c.execute(sql, values)]

    def production_summary(self, competence):
        year, month = (int(part) for part in competence.split("-"))
        start = date(year, month, 1)
        end = date(year + (month == 12), 1 if month == 12 else month + 1, 1)
        report = self.period_report(start.isoformat(), end.isoformat())
        # Compatibility adapter for integrations still using the former API.
        return {
            row["procurador"]: {
                "entries": row["distributed"],
                "exits": row["production"],
                "opinions": row["opinions"],
                "quotas": row["quotas"],
                "days": 0,
                "timed": 0,
            }
            for row in report["by_procurador"]
        }

    @staticmethod
    def _where(base, value, filters, allowed):
        clauses, values = [base + "=?"], [value]
        for field, choice in filters.items():
            if field not in allowed:
                raise ValueError("Filtro de relatório inválido.")
            if choice is not None:
                clauses.append(field + "=?")
                values.append(choice)
        return " AND ".join(clauses), values

    def movement_facets(self, competence, procurador=None):
        where, values = self._where(
            "competencia", competence, {"procurador": procurador}, ("procurador",)
        )
        return self._read(
            "SELECT 'subcategoria' AS field,subcategoria AS value,COUNT(*) AS n "
            "FROM tramita_movimentacoes WHERE " + where + " GROUP BY subcategoria "
            "UNION ALL SELECT 'origem',origem,COUNT(*) FROM tramita_movimentacoes WHERE "
            + where
            + " GROUP BY origem",
            values + values,
        )

    def movement_page(self, competence, filters, offset=0, limit=100):
        where, values = self._where(
            "competencia",
            competence,
            filters,
            ("procurador", "subcategoria", "origem", "tipo_movimentacao"),
        )
        return self._read(
            "SELECT protocolo,subcategoria,origem,procurador,tipo_movimentacao,"
            "data_realizacao,data_devolucao,motivo_devolucao FROM tramita_movimentacoes WHERE "
            + where
            + " ORDER BY protocolo,id LIMIT ? OFFSET ?",
            [*values, limit + 1, offset],
        )

    def stock_summary(self, snapshot):
        return self._read(
            "SELECT procurador,COUNT(*) AS n,COUNT(dias_com_procurador) AS timed,"
            "SUM(dias_com_procurador) AS days,MAX(dias_com_procurador) AS maximum,"
            "SUM(CASE WHEN dias_com_procurador>30 THEN 1 ELSE 0 END) AS over30,"
            "SUM(CASE WHEN dias_com_procurador>60 THEN 1 ELSE 0 END) AS over60,"
            "SUM(CASE WHEN dias_com_procurador>90 THEN 1 ELSE 0 END) AS over90 "
            "FROM tramita_estoque WHERE data_snapshot=? GROUP BY procurador",
            (snapshot,),
        )

    def stock_visual_data(self, snapshot):
        """Read the current stock once for derived visual summaries."""
        return self._read(
            "SELECT protocolo,procurador,dias_com_procurador "
            "FROM tramita_estoque WHERE data_snapshot=?",
            (snapshot,),
        )

    def stock_options(self, snapshot, filters):
        # One batch query for cascading facets; each facet uses only its predecessors.
        fields = ("subcategoria", "jurisdicionado", "fase", "assistente")
        parts, parameters = [], []
        preceding = {"procurador": filters.get("procurador")}
        for field in fields:
            where, values = self._where(
                "data_snapshot", snapshot, preceding, ("procurador", *fields)
            )
            parts.append(
                f"SELECT '{field}' AS field,{field} AS value FROM tramita_estoque WHERE "
                + where
                + f" AND {field}<>'' GROUP BY {field}"
            )
            parameters.extend(values)
            preceding[field] = filters.get(field)
        return self._read(" UNION ALL ".join(parts), parameters)

    @staticmethod
    def _band_sql():
        return (
            "CASE WHEN dias_com_procurador IS NULL THEN NULL "
            "WHEN dias_com_procurador<=7 THEN '0–7 dias' "
            "WHEN dias_com_procurador<=15 THEN '8–15 dias' "
            "WHEN dias_com_procurador<=30 THEN '16–30 dias' "
            "WHEN dias_com_procurador<=60 THEN '31–60 dias' "
            "WHEN dias_com_procurador<=90 THEN '61–90 dias' ELSE 'Mais de 90 dias' END"
        )

    def stock_details(self, snapshot, filters, band=None, offset=0, limit=100):
        where, values = self._where(
            "data_snapshot",
            snapshot,
            filters,
            ("procurador", "subcategoria", "jurisdicionado", "fase", "assistente"),
        )
        band_sql = self._band_sql()
        if band is not None:
            where += " AND (" + band_sql + ")=?"
            values.append(band)
        # Two bounded results, one connection; no per-row calls.
        with self.store.connection(read_only=True) as c:
            bands = [
                dict(r)
                for r in c.execute(
                    "SELECT "
                    + band_sql
                    + " AS faixa,COUNT(*) AS n FROM tramita_estoque WHERE "
                    + where
                    + " GROUP BY "
                    + band_sql,
                    values,
                )
            ]
            rows = [
                dict(r)
                for r in c.execute(
                    "SELECT protocolo,procurador,subcategoria,jurisdicionado,fase,dias_com_procurador,"
                    "dias_no_mpc,assistente,prescricao FROM tramita_estoque WHERE "
                    + where
                    + " ORDER BY COALESCE(NULLIF(dias_com_procurador,0),-1) DESC,id LIMIT ? OFFSET ?",
                    [*values, limit + 1, offset],
                )
            ]
        return bands, rows


def ensure_schema(store):
    TramitaReportsStore(store)
