"""Persistência aditiva para os relatórios exportados pelo Tramita."""

from database.store import unwrap_store
from threading import RLock

_SCHEMA_LOCK = RLock()


class TramitaReportsStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        # Only a successful commit may mark this Store ready. The portal keeps
        # this object in the session; another Store still validates its database.
        with _SCHEMA_LOCK:
            if getattr(self.store, "_tramita_schema_ready", False):
                return
            self._initialize_schema()
            self.store._tramita_schema_ready = True

    def _initialize_schema(self):
        identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.store.backend == "postgresql" else "INTEGER PRIMARY KEY"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(f"CREATE TABLE IF NOT EXISTS tramita_importacoes (id {identity}, tipo TEXT NOT NULL CHECK(tipo IN ('ENTRADAS','SAIDAS','ESTOQUE')), competencia TEXT, data_snapshot TEXT, nome_arquivo TEXT NOT NULL, hash_arquivo TEXT NOT NULL UNIQUE, quantidade_registros INTEGER NOT NULL, importado_em TEXT NOT NULL, importado_por TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'CONCLUIDA')")
            c.execute(f"CREATE TABLE IF NOT EXISTS tramita_movimentacoes (id {identity}, importacao_id INTEGER NOT NULL REFERENCES tramita_importacoes(id), competencia TEXT NOT NULL, tipo_movimentacao TEXT NOT NULL CHECK(tipo_movimentacao IN ('ENTRADA','SAIDA')), protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '', origem TEXT NOT NULL DEFAULT '', data_realizacao TEXT, procurador TEXT NOT NULL DEFAULT '', motivo_distribuicao TEXT NOT NULL DEFAULT '', data_devolucao TEXT, motivo_devolucao TEXT NOT NULL DEFAULT '')")
            c.execute(f"CREATE TABLE IF NOT EXISTS tramita_estoque (id {identity}, importacao_id INTEGER NOT NULL REFERENCES tramita_importacoes(id), data_snapshot TEXT NOT NULL, protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', digital TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '', jurisdicionado TEXT NOT NULL DEFAULT '', fase TEXT NOT NULL DEFAULT '', procurador TEXT NOT NULL DEFAULT '', dias_com_procurador REAL, assistente TEXT NOT NULL DEFAULT '', dias_com_assistente REAL, dias_no_mpc REAL, prescricao TEXT NOT NULL DEFAULT '')")
            c.execute("CREATE INDEX IF NOT EXISTS tramita_movimentacoes_competencia_idx ON tramita_movimentacoes(competencia, tipo_movimentacao)")
            c.execute("CREATE INDEX IF NOT EXISTS tramita_estoque_snapshot_idx ON tramita_estoque(data_snapshot)")
            c.execute("CREATE INDEX IF NOT EXISTS tramita_movimentacoes_pagina_idx ON tramita_movimentacoes(competencia,procurador,protocolo,id)")
            c.execute("CREATE INDEX IF NOT EXISTS tramita_estoque_procurador_idx ON tramita_estoque(data_snapshot,procurador)")

    def imported_hash(self, file_hash):
        with self.store.connection(read_only=True) as c:
            return c.execute("SELECT id FROM tramita_importacoes WHERE hash_arquivo=?", (file_hash,)).fetchone() is not None

    def import_rows(self, *, kind, file_name, file_hash, actor, competence=None, snapshot_date=None, rows=()):
        rows = list(rows)
        if self.imported_hash(file_hash):
            raise ValueError("Este arquivo já foi importado anteriormente.")
        from database.store import now
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if c.execute("SELECT 1 FROM tramita_importacoes WHERE hash_arquivo=?", (file_hash,)).fetchone():
                raise ValueError("Este arquivo já foi importado anteriormente.")
            inserted = c.execute("INSERT INTO tramita_importacoes(tipo,competencia,data_snapshot,nome_arquivo,hash_arquivo,quantidade_registros,importado_em,importado_por) VALUES(?,?,?,?,?,?,?,?)", (kind, competence, snapshot_date, file_name, file_hash, len(rows), now(), actor or ""))
            import_id = inserted.lastrowid
            if kind in ("ENTRADAS", "SAIDAS"):
                movement = "ENTRADA" if kind == "ENTRADAS" else "SAIDA"
                c.executemany("INSERT INTO tramita_movimentacoes(importacao_id,competencia,tipo_movimentacao,protocolo,tipo,subcategoria,origem,data_realizacao,procurador,motivo_distribuicao,data_devolucao,motivo_devolucao) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)", [(import_id, competence, movement, row["protocolo"], row["tipo"], row["subcategoria"], row["origem"], row["data_realizacao"], row["procurador"], row["motivo_distribuicao"], row["data_devolucao"], row["motivo_devolucao"]) for row in rows])
            else:
                c.executemany("INSERT INTO tramita_estoque(importacao_id,data_snapshot,protocolo,tipo,digital,subcategoria,jurisdicionado,fase,procurador,dias_com_procurador,assistente,dias_com_assistente,dias_no_mpc,prescricao) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [(import_id, snapshot_date, row["protocolo"], row["tipo"], row["digital"], row["subcategoria"], row["jurisdicionado"], row["fase"], row["procurador"], row["dias_com_procurador"], row["assistente"], row["dias_com_assistente"], row["dias_no_mpc"], row["prescricao"]) for row in rows])
        return import_id

    def competences(self):
        with self.store.connection(read_only=True) as c:
            return [r[0] for r in c.execute("SELECT DISTINCT competencia FROM tramita_movimentacoes ORDER BY competencia DESC")]

    def latest_snapshot(self):
        with self.store.connection(read_only=True) as c:
            row = c.execute("SELECT MAX(data_snapshot) FROM tramita_estoque").fetchone()
            return row[0] if row and row[0] else None

    def _read(self, sql, values=()):
        with self.store.connection(read_only=True) as c:
            return [dict(row) for row in c.execute(sql, values)]

    def production_summary(self, competence):
        # Group raw result labels in SQL, normalize only those labels in Python
        # so accented/case/whitespace variants retain the existing semantics.
        from services.tramita_reports import is_result

        elapsed = (
            "EXTRACT(EPOCH FROM (CAST(NULLIF(data_devolucao,'') AS timestamp) - "
            "CAST(NULLIF(data_realizacao,'') AS timestamp))) / 86400.0"
            if self.store.backend == "postgresql"
            else "julianday(data_devolucao) - julianday(data_realizacao)"
        )
        rows = self._read(
            "SELECT procurador,tipo_movimentacao,motivo_devolucao,COUNT(*) AS n,"
            f"SUM({elapsed}) AS days,COUNT({elapsed}) AS timed "
            "FROM tramita_movimentacoes WHERE competencia=? "
            "GROUP BY procurador,tipo_movimentacao,motivo_devolucao", (competence,),
        )
        grouped = {}
        for row in rows:
            item = grouped.setdefault(row["procurador"], dict(entries=0, exits=0, opinions=0, quotas=0, days=0, timed=0))
            if row["tipo_movimentacao"] == "ENTRADA":
                item["entries"] += row["n"]
            else:
                item["exits"] += row["n"]
                item["opinions"] += row["n"] * is_result(row["motivo_devolucao"], "Analisado Com Parecer")
                item["quotas"] += row["n"] * is_result(row["motivo_devolucao"], "Analisado Com Cota")
                item["days"] += float(row["days"] or 0)
                item["timed"] += row["timed"]
        return grouped

    @staticmethod
    def _where(base, value, filters, allowed):
        clauses, values = [base + "=?"], [value]
        for field, choice in filters.items():
            if field not in allowed:
                raise ValueError("Filtro de relatório inválido.")
            if choice is not None:
                clauses.append(field + "=?")
                values.append(choice)
        return " AND ".join(clauses), values

    def movement_facets(self, competence, procurador=None):
        where, values = self._where("competencia", competence, {"procurador": procurador}, ("procurador",))
        return self._read(
            "SELECT 'subcategoria' AS field,subcategoria AS value,COUNT(*) AS n "
            "FROM tramita_movimentacoes WHERE " + where + " GROUP BY subcategoria "
            "UNION ALL SELECT 'origem',origem,COUNT(*) FROM tramita_movimentacoes WHERE "
            + where + " GROUP BY origem", values + values,
        )

    def movement_page(self, competence, filters, offset=0, limit=100):
        where, values = self._where("competencia", competence, filters, ("procurador", "subcategoria", "origem", "tipo_movimentacao"))
        return self._read(
            "SELECT protocolo,subcategoria,origem,procurador,tipo_movimentacao,"
            "data_realizacao,data_devolucao,motivo_devolucao FROM tramita_movimentacoes WHERE "
            + where + " ORDER BY protocolo,id LIMIT ? OFFSET ?", [*values, limit + 1, offset],
        )

    def stock_summary(self, snapshot):
        return self._read(
            "SELECT procurador,COUNT(*) AS n,COUNT(dias_com_procurador) AS timed,"
            "SUM(dias_com_procurador) AS days,MAX(dias_com_procurador) AS maximum,"
            "SUM(CASE WHEN dias_com_procurador>30 THEN 1 ELSE 0 END) AS over30,"
            "SUM(CASE WHEN dias_com_procurador>60 THEN 1 ELSE 0 END) AS over60,"
            "SUM(CASE WHEN dias_com_procurador>90 THEN 1 ELSE 0 END) AS over90 "
            "FROM tramita_estoque WHERE data_snapshot=? GROUP BY procurador", (snapshot,),
        )

    def stock_options(self, snapshot, filters):
        # One batch query for cascading facets; each facet uses only its predecessors.
        fields = ("subcategoria", "jurisdicionado", "fase", "assistente")
        parts, parameters = [], []
        preceding = {"procurador": filters.get("procurador")}
        for field in fields:
            where, values = self._where("data_snapshot", snapshot, preceding, ("procurador", *fields))
            parts.append(f"SELECT '{field}' AS field,{field} AS value FROM tramita_estoque WHERE " + where + f" AND {field}<>'' GROUP BY {field}")
            parameters.extend(values)
            preceding[field] = filters.get(field)
        return self._read(" UNION ALL ".join(parts), parameters)

    @staticmethod
    def _band_sql():
        return ("CASE WHEN dias_com_procurador IS NULL THEN NULL "
                "WHEN dias_com_procurador<=7 THEN '0–7 dias' "
                "WHEN dias_com_procurador<=15 THEN '8–15 dias' "
                "WHEN dias_com_procurador<=30 THEN '16–30 dias' "
                "WHEN dias_com_procurador<=60 THEN '31–60 dias' "
                "WHEN dias_com_procurador<=90 THEN '61–90 dias' ELSE 'Mais de 90 dias' END")

    def stock_details(self, snapshot, filters, band=None, offset=0, limit=100):
        where, values = self._where("data_snapshot", snapshot, filters, ("procurador", "subcategoria", "jurisdicionado", "fase", "assistente"))
        band_sql = self._band_sql()
        if band is not None:
            where += " AND (" + band_sql + ")=?"
            values.append(band)
        # Two bounded results, one connection; no per-row calls.
        with self.store.connection(read_only=True) as c:
            bands = [dict(r) for r in c.execute("SELECT " + band_sql + " AS faixa,COUNT(*) AS n FROM tramita_estoque WHERE " + where + " GROUP BY " + band_sql, values)]
            rows = [dict(r) for r in c.execute(
                "SELECT protocolo,procurador,subcategoria,jurisdicionado,fase,dias_com_procurador,"
                "dias_no_mpc,assistente,prescricao FROM tramita_estoque WHERE " + where
                + " ORDER BY COALESCE(NULLIF(dias_com_procurador,0),-1) DESC,id LIMIT ? OFFSET ?",
                [*values, limit + 1, offset],
            )]
        return bands, rows


def ensure_schema(store):
    TramitaReportsStore(store)
