"""Persistência aditiva para os relatórios exportados pelo Tramita."""

from database.store import unwrap_store


class TramitaReportsStore:
    def __init__(self, store):
        self.store = unwrap_store(store)
        self.ensure_schema()

    def ensure_schema(self):
        identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if self.store.backend == "postgresql" else "INTEGER PRIMARY KEY"
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            c.execute(f"CREATE TABLE IF NOT EXISTS tramita_importacoes (id {identity}, tipo TEXT NOT NULL CHECK(tipo IN ('ENTRADAS','SAIDAS','ESTOQUE')), competencia TEXT, data_snapshot TEXT, nome_arquivo TEXT NOT NULL, hash_arquivo TEXT NOT NULL UNIQUE, quantidade_registros INTEGER NOT NULL, importado_em TEXT NOT NULL, importado_por TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'CONCLUIDA')")
            c.execute(f"CREATE TABLE IF NOT EXISTS tramita_movimentacoes (id {identity}, importacao_id INTEGER NOT NULL REFERENCES tramita_importacoes(id), competencia TEXT NOT NULL, tipo_movimentacao TEXT NOT NULL CHECK(tipo_movimentacao IN ('ENTRADA','SAIDA')), protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '', origem TEXT NOT NULL DEFAULT '', data_realizacao TEXT, procurador TEXT NOT NULL DEFAULT '', motivo_distribuicao TEXT NOT NULL DEFAULT '', data_devolucao TEXT, motivo_devolucao TEXT NOT NULL DEFAULT '')")
            c.execute(f"CREATE TABLE IF NOT EXISTS tramita_estoque (id {identity}, importacao_id INTEGER NOT NULL REFERENCES tramita_importacoes(id), data_snapshot TEXT NOT NULL, protocolo TEXT NOT NULL, tipo TEXT NOT NULL DEFAULT '', digital TEXT NOT NULL DEFAULT '', subcategoria TEXT NOT NULL DEFAULT '', jurisdicionado TEXT NOT NULL DEFAULT '', fase TEXT NOT NULL DEFAULT '', procurador TEXT NOT NULL DEFAULT '', dias_com_procurador REAL, assistente TEXT NOT NULL DEFAULT '', dias_com_assistente REAL, dias_no_mpc REAL, prescricao TEXT NOT NULL DEFAULT '')")
            c.execute("CREATE INDEX IF NOT EXISTS tramita_movimentacoes_competencia_idx ON tramita_movimentacoes(competencia, tipo_movimentacao)")
            c.execute("CREATE INDEX IF NOT EXISTS tramita_estoque_snapshot_idx ON tramita_estoque(data_snapshot)")

    def imported_hash(self, file_hash):
        with self.store.connection(read_only=True) as c:
            return c.execute("SELECT id FROM tramita_importacoes WHERE hash_arquivo=?", (file_hash,)).fetchone() is not None

    def import_rows(self, *, kind, file_name, file_hash, actor, competence=None, snapshot_date=None, rows=()):
        rows = list(rows)
        if self.imported_hash(file_hash):
            raise ValueError("Este arquivo já foi importado anteriormente.")
        from database.store import now
        with self.store.connection() as c:
            c.execute("BEGIN IMMEDIATE")
            if c.execute("SELECT 1 FROM tramita_importacoes WHERE hash_arquivo=?", (file_hash,)).fetchone():
                raise ValueError("Este arquivo já foi importado anteriormente.")
            inserted = c.execute("INSERT INTO tramita_importacoes(tipo,competencia,data_snapshot,nome_arquivo,hash_arquivo,quantidade_registros,importado_em,importado_por) VALUES(?,?,?,?,?,?,?,?)", (kind, competence, snapshot_date, file_name, file_hash, len(rows), now(), actor or ""))
            import_id = inserted.lastrowid
            if kind in ("ENTRADAS", "SAIDAS"):
                movement = "ENTRADA" if kind == "ENTRADAS" else "SAIDA"
                c.executemany("INSERT INTO tramita_movimentacoes(importacao_id,competencia,tipo_movimentacao,protocolo,tipo,subcategoria,origem,data_realizacao,procurador,motivo_distribuicao,data_devolucao,motivo_devolucao) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)", [(import_id, competence, movement, row["protocolo"], row["tipo"], row["subcategoria"], row["origem"], row["data_realizacao"], row["procurador"], row["motivo_distribuicao"], row["data_devolucao"], row["motivo_devolucao"]) for row in rows])
            else:
                c.executemany("INSERT INTO tramita_estoque(importacao_id,data_snapshot,protocolo,tipo,digital,subcategoria,jurisdicionado,fase,procurador,dias_com_procurador,assistente,dias_com_assistente,dias_no_mpc,prescricao) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)", [(import_id, snapshot_date, row["protocolo"], row["tipo"], row["digital"], row["subcategoria"], row["jurisdicionado"], row["fase"], row["procurador"], row["dias_com_procurador"], row["assistente"], row["dias_com_assistente"], row["dias_no_mpc"], row["prescricao"]) for row in rows])
        return import_id

    def competences(self):
        with self.store.connection(read_only=True) as c:
            return [r[0] for r in c.execute("SELECT DISTINCT competencia FROM tramita_movimentacoes ORDER BY competencia DESC")]

    def latest_snapshot(self):
        with self.store.connection(read_only=True) as c:
            row = c.execute("SELECT MAX(data_snapshot) FROM tramita_estoque").fetchone()
            return row[0] if row and row[0] else None


def ensure_schema(store):
    TramitaReportsStore(store)
