[theme]
primaryColor = "#9B1724"
backgroundColor = "#F6F5F4"
secondaryBackgroundColor = "#F3F4F8"
textColor = "#202832"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false


[client]
toolbarMode = "minimal"
