[theme]
primaryColor = "#9B1724"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F5F7"
textColor = "#202832"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false


[client]
toolbarMode = "minimal"
